import assert from 'node:assert/strict';import {Readable} from 'node:stream';import {createAccounts} from '../lib/accounts.mjs';import {createUserAdminHandler} from '../api/admin-users.mjs';
const owner='00000000-0000-0000-0000-000000000001',member='00000000-0000-0000-0000-000000000002',origin='https://reposhelf.test',calls=[];let failure;
const accounts=createAccounts({config:{origin,url:'https://fixture.supabase.co',key:'public-test-key',serviceKey:'private-service-secret'},fetcher:async(url,options)=>{const path=new URL(url).pathname,token=options.headers.Authorization?.slice(7),body=options.body&&JSON.parse(options.body);calls.push({path,body,token});if(path==='/auth/v1/user')return token==='owner'||token==='member'?Response.json({id:token==='owner'?owner:member,user_metadata:{user_name:'owner',admin:true}}):Response.json({}, {status:401});if(path.endsWith('reposhelf_is_admin'))return Response.json(token==='owner');if(path.endsWith('reposhelf_list_users'))return failure?Response.json({code:'PGRST202'},{status:404}):Response.json({items:[{id:member,username:'member',github_id:'42',admin:false}],total:1,nextCursor:null});if(path.endsWith('reposhelf_set_admin'))return failure?Response.json({code:failure},{status:409}):Response.json({id:body.target_user,admin:body.enabled,changed:true});throw Error('Unexpected provider request') }});
const handler=createUserAdminHandler({accounts,env:{REPOSHELF_API_KEY:'hidden-agent-secret-long-enough-for-api'}});
async function run(url,{token,method='GET',body,requestOrigin=origin}={}){const req=Readable.from(body===undefined?[]:[JSON.stringify(body)]);Object.assign(req,{url,method,headers:{origin:requestOrigin,...token?{cookie:'__Host-reposhelf-access='+token}:{}}});const res={status:0,headers:{},getHeader(k){return this.headers[k]},setHeader(k,v){this.headers[k]=v},writeHead(status,h){this.status=status;Object.assign(this.headers,h)},end(text){this.data=JSON.parse(text)}};await handler(req,res);return res}
assert.equal((await run('/api/admin-users')).status,401);assert.equal((await run('/api/admin-users?action=setup',{token:'member'})).status,403);assert.equal((await run('/api/admin-users',{token:'member',method:'PUT',body:{id:owner,admin:true,expectedAdmin:true}})).status,403);
let r=await run('/api/admin-users?action=setup',{token:'owner'});assert.equal(r.status,200);assert(r.data.agentKeyConfigured);assert(r.data.supabase.analyticsKeyConfigured);assert(!JSON.stringify(r.data).includes('hidden-agent-secret'));assert(!JSON.stringify(r.data).includes('private-service-secret'));assert(!JSON.stringify(r.data).includes('public-test-key'));assert.match(r.headers['Cache-Control'],/private/);
r=await run('/api/admin-users?q=member&limit=5',{token:'owner'});assert.equal(r.data.items[0].id,member);assert.equal(r.data.currentUserId,owner);assert.equal(calls.at(-1).body.search_text,'member');assert.equal(calls.at(-1).body.page_size,5);assert.equal(calls.at(-1).token,'owner');assert.equal((await run('/api/admin-users?limit=1000',{token:'owner'})).status,400);
r=await run('/api/admin-users',{token:'owner',method:'PUT',body:{id:member,admin:true,expectedAdmin:false}});assert.equal(r.status,200);assert.equal(calls.at(-1).body.target_user,member);assert.equal(calls.at(-1).body.expected_admin,false);assert.equal((await run('/api/admin-users',{token:'owner',method:'PUT',body:{id:owner,admin:false,expectedAdmin:true}})).status,409);assert.equal((await run('/api/admin-users',{token:'owner',method:'PUT',body:{id:member,admin:true,expectedAdmin:false},requestOrigin:'https://attacker.test'})).status,403);assert.equal((await run('/api/admin-users',{token:'owner',method:'PUT',body:{id:member,admin:null,expectedAdmin:false}})).status,400);
failure='40001';r=await run('/api/admin-users',{token:'owner',method:'PUT',body:{id:member,admin:true,expectedAdmin:false}});assert.equal(r.status,409);assert.equal(r.data.error.code,'role_conflict');failure='PT409';r=await run('/api/admin-users',{token:'owner',method:'PUT',body:{id:member,admin:false,expectedAdmin:true}});assert.equal(r.data.error.code,'protected_admin');failure='missing_migration';r=await run('/api/admin-users',{token:'owner'});assert.equal(r.status,503);assert.equal(r.data.error.code,'migration_required');
console.log('PASS: admin-only users/setup, verified roles despite spoofed profile metadata, private flags without secrets, validated search and role updates, same-origin protection, own-role guard, conflict handling and migration guidance.');
