import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {pathToFileURL} from 'node:url';
import {createAdminResponseCache} from '../lib/admin-response-cache.mjs';
import {createAdminSummary,createAdminSummaryStore,summaryRanking} from '../lib/admin-summary.mjs';
import {createAnalyticsHandler} from '../api/analytics.mjs';
import {createSyncLogHandler} from '../api/sync-log.mjs';
let now=0,calls=0;const cache=createAdminResponseCache({ttl:100,now:()=>now,max:2}),load=async()=>++calls;
assert.deepEqual(await Promise.all([cache.get('a',load),cache.get('a',load)]),[1,1]);assert.equal(calls,1);assert.equal(await cache.get('a',load),1);assert.equal(await cache.get('b',load),2);assert.equal(await cache.get('a',load,{refresh:true}),3);now=101;assert.equal(await cache.get('a',load),4);
let failures=0;for(let i=0;i<2;i++)await assert.rejects(cache.get('bad',async()=>{failures++;throw Error('transient')}));assert.equal(failures,2,'Failures are retried, not cached');
const at=Date.parse('2026-10-08T10:00:00Z'),date=new Date(at).toISOString(),demo='https://demo.example';
const row={full:'team/app',name:'App',category:'Productivity',subjects:['Mobile'],platforms:['Android'],demo,availability:'available',lastCheckedAt:date,stars:100,forks:20,metrics:[{at:new Date(at-7*86400000).toISOString(),stars:20,forks:10}],demoHealth:{url:demo,status:'working',checkedAt:date},screenshots:[{kind:'demo',src:'https://example.org/preview.jpg',url:demo,capturedAt:date}],readmeSnapshot:{status:'saved'},agentContext:{documents:[]}};
const summary=createAdminSummary([row,{...row,full:'team/gone',availability:'unavailable'}],{now:at,version:'v',snapshots:{catalog:date}});
assert.equal(summary.coverage.availableProjects,1);assert.equal(summary.coverage.readmesSaved,1);assert.equal(summaryRanking(summary,{sort:'stars',limit:1}).items[0].id,row.full);assert(!JSON.stringify(summary).includes('agentContext'));
const dir=await mkdtemp(tmpdir()+'/reposhelf-summary-'),root=pathToFileURL(dir+'/');try{await mkdir(new URL('data/',root));await writeFile(new URL('data/admin-summary.json',root),JSON.stringify(summary));let remoteCalls=0;const store=createAdminSummaryStore({root,checkpoint:{json:async()=>{remoteCalls++;return {...summary,generatedAt:new Date(at+1000).toISOString(),catalogVersion:'new'}}}});assert.equal((await store.read()).catalogVersion,'new');assert.equal((await store.read()).catalogVersion,'new');assert.equal(remoteCalls,1,'Summary lookup cached without loading the catalogue')}finally{await rm(dir,{recursive:true,force:true})}
let permitted=true,user='owner',db=0,reads=0;const accounts={config:{origin:'https://reposhelf.test'},admin:async()=>{if(!permitted)throw Object.assign(Error('Forbidden'),{status:403});return {id:user,token:user}},request:async path=>{db++;return path.includes('reposhelf_analytics')?{daily:[]}:{} }};
const catalog={info:async()=>{throw Error('Full catalogue was loaded')},popularity:async()=>{throw Error('Growth was recomputed')}};
const handler=createAnalyticsHandler({accounts,catalog,summaries:{read:async()=>{reads++;return summary}},growth:async()=>[]});
async function call(handler,url){const res={writeHead(status,headers){this.status=status;this.headers=headers},end(body){this.data=JSON.parse(body)}};await handler({method:'GET',url,headers:{}},res);return res}
let response=await call(handler,'/api/analytics?days=30');assert.equal(response.status,200);assert.equal(response.data.coverage.availableProjects,1);const initial=db;await call(handler,'/api/analytics?days=30');assert.equal(db,initial);assert.equal(reads,1);assert.match(response.headers['Cache-Control'],/no-store/);
permitted=false;assert.equal((await call(handler,'/api/analytics?days=30')).status,403,'Cached admin data never bypasses current authorization');permitted=true;user='other';await call(handler,'/api/analytics?days=30');assert(db>initial,'Administrators have isolated cache entries');const next=db;await call(handler,'/api/analytics?days=30&refresh=1');assert(db>next,'Manual refresh bypasses response cache');assert.equal((await call(handler,'/api/analytics?action=popularity&sort=stars&limit=1')).data.items.length,1);assert.equal((await call(handler,'/api/analytics?action=popularity&limit=500')).status,400);
let syncReads=0;const sync=createSyncLogHandler({accounts,saved:async()=>{syncReads++;return []},checkpoint:{reports:async()=>[],json:async()=>null},fetcher:async()=>Response.json({workflow_runs:[],total_count:0})});await call(sync,'/api/sync-log');await call(sync,'/api/sync-log');assert.equal(syncReads,1);permitted=false;assert.equal((await call(sync,'/api/sync-log')).status,403);permitted=true;await call(sync,'/api/sync-log?refresh=1');assert.equal(syncReads,2);
console.log('PASS: precomputed coverage/rankings, latest summary selection, zero full-catalogue analytics reads, per-admin caches, authorization on hits, concurrent deduplication, expiration, transient retry and manual refresh.');
