import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {randomUUID} from 'node:crypto';
async function scenario({consent=false,dnt=false,gpc=false,holdAuth=false,status=202,initialAdmin=false}={}){const local=new Map(),session=new Map(),listeners=new Map(),posts=[];if(consent)local.set('reposhelf.analytics.consent.v1','yes');let admin=initialAdmin,responseStatus=status,releaseAuth;const storage=m=>({getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)});const context={console,URL,AbortSignal,Map,Set,Date,JSON,Event,crypto:{randomUUID},location:{pathname:'/',origin:'https://reposhelf.test'},navigator:{doNotTrack:dnt?'1':null,globalPrivacyControl:gpc},document:{addEventListener(){}},localStorage:storage(local),sessionStorage:storage(session),setTimeout(){return 1},clearTimeout(){},fetch:async(path,opts)=>{if(path==='/api/analytics'){posts.push(JSON.parse(opts.body));return {ok:responseStatus>=200&&responseStatus<300,status:responseStatus}}if(path.startsWith('/api/auth')){if(holdAuth)await new Promise(resolve=>{releaseAuth=resolve});return {ok:true,json:async()=>({enabled:true,analyticsEnabled:true,user:admin?{id:'owner',admin:true}:null})}};return {ok:true,json:async()=>({items:[]})}}};context.window={addEventListener:(k,v)=>listeners.set(k,v),dispatchEvent(){}};vm.createContext(context);vm.runInContext(readFileSync('dist/account.js','utf8'),context);for(let i=0;i<10;i++)await Promise.resolve();const A=context.window.RepoAccount;assert.equal(A.ready,!holdAuth);return {A,local,session,posts,privacy:()=>listeners.get('reposhelf-privacy')(),setAdmin:()=>{admin=true},release:()=>{holdAuth=false;releaseAuth()},setStatus:value=>{responseStatus=value}}}
let s=await scenario();assert.equal(s.local.size,0,'No identifiers before consent');assert.equal(s.A.track('search'),false);s.local.set('reposhelf.analytics.consent.v1','yes');s.privacy();for(let i=0;i<10;i++)await Promise.resolve();assert.equal(s.posts.length,1);assert.equal(s.posts[0].events[0].kind,'page_view');assert(s.posts[0].visitor);s.privacy();assert.equal(s.posts.length,1,'Consent event does not duplicate first page view');s.A.track('listing_view','team/example');s.local.delete('reposhelf.analytics.consent.v1');s.privacy();assert.equal(s.posts.length,1,'Withdrawal drops queued events');
for(const flag of ['dnt','gpc']){s=await scenario({consent:true,[flag]:true});assert.equal(s.A.track('page_view'),false);assert.equal(s.local.size,1,'Privacy signal prevents visitor identifier creation');s.privacy();assert.equal(s.posts.length,0)}
s=await scenario({consent:true});const before=s.posts.length;s.A.track('listing_view','team/example');s.setAdmin();await s.A.refresh();s.privacy();assert.equal(s.posts.length,before,'Admin sign-in discards queued guest activity');console.log('PASS: opt-in first page view, no identifiers before consent, withdrawal drops queued events, DNT/GPC and administrator exclusion.');

s=await scenario({consent:true,status:429});const event=s.posts[0].events[0].id;s.A.track('listing_view','team/retry');s.setStatus(202);s.privacy();for(let i=0;i<15;i++)await Promise.resolve();assert(s.posts[1].events.some(e=>e.id===event),'Throttled events retry with their original ID');assert(s.posts[1].events.some(e=>e.project==='team/retry'));
s=await scenario({consent:true,holdAuth:true});assert.equal(s.A.track('listing_view','team/early'),true);s.release();for(let i=0;i<25;i++)await Promise.resolve();assert(s.posts.flatMap(p=>p.events).some(e=>e.project==='team/early'),'Consented early views wait for verified account readiness');
s=await scenario({consent:true,holdAuth:true,initialAdmin:true});s.A.track('listing_view','team/admin');s.release();for(let i=0;i<25;i++)await Promise.resolve();assert.equal(s.posts.length,0,'Early admin views are discarded after identity verification');
s=await scenario({holdAuth:true});assert.equal(s.A.track('listing_view','team/no-consent'),false);s.release();for(let i=0;i<20;i++)await Promise.resolve();s.local.set('reposhelf.analytics.consent.v1','yes');s.privacy();for(let i=0;i<15;i++)await Promise.resolve();assert(!s.posts.flatMap(p=>p.events).some(e=>e.project==='team/no-consent'),'No backfill for clicks before consent');console.log('PASS: throttling retains idempotent events, early consented views wait for account readiness, and early admin/pre-consent activity stays excluded.');
