import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
import {Readable} from 'node:stream';
import {createBrowseIndex,generateBrowseIndex} from '../lib/browse-index.mjs';
import {createBrowseService} from '../lib/browse-service.mjs';
import {createEditorialHandler} from '../api/editorial.mjs';
import {createAccounts} from '../lib/accounts.mjs';
const require=createRequire(import.meta.url),E=require('../dist/editorial.js'),S=require('../dist/storefront.js');
const now=Date.now(),repos=Array.from({length:130},(_,i)=>({full:`team/project-${i}`,name:`Project ${i}`,description:'A visual planning tool.',category:i%2?'Design':'Productivity',topics:['react'],technologies:['React'],demo:i%3?'https://demo.example.org':null,availability:i===129?'unavailable':'available',created:new Date(now-i*86400000).toISOString(),stars:i,forks:i/2,lastCheckedAt:new Date(now).toISOString(),metrics:[{at:new Date(now-7*86400000).toISOString(),stars:0,forks:0}],overview:{kind:'readme',paragraphs:['Searchable collaboration context.'],features:['A detailed feature'],sourceUrl:'https://github.com/team/project/README.md'},agentContext:{documents:[{name:'LICENSE'}]},screenshots:[{src:'https://example.org/preview.jpg',kind:'readme'},{src:'https://example.org/extra.jpg',kind:'readme'}]}));
const spaces={repositories:[{full:'hf:team/linked',source:'huggingface',spaceId:'team/linked',githubFull:repos[0].full,name:'Linked',demo:'https://huggingface.co/spaces/team/linked',availability:'available'},{full:'hf:team/space',source:'huggingface',spaceId:'team/space',name:'An AI Space',description:'Try AI',demo:'https://huggingface.co/spaces/team/space',category:'AI & machine learning',availability:'available',likes:20}]};
const community={mentions:[{full:repos[1].full,source:'hackernews',id:'42',url:'https://news.ycombinator.com/item?id=42',publishedAt:new Date(now).toISOString(),title:'Show HN',points:20}]},dir=await mkdtemp(tmpdir()+'/reposhelf-browse-'),root=pathToFileURL(dir+'/');
try{
 await mkdir(new URL('dist/',root));for(const [name,data] of Object.entries({'catalog.json':{updatedAt:new Date(now).toISOString(),repositories:repos},'spaces.json':spaces,'community.json':community}))await writeFile(new URL('dist/'+name,root),JSON.stringify(data));
 const generated=await generateBrowseIndex(root),index=generated.index,service=createBrowseService({root});
 assert(index.repositories.length>=130,'No catalogue ceiling');assert(!index.repositories.some(r=>r.full==='hf:team/linked'),'Linked Spaces remain deduplicated');assert.equal(index.repositories.find(r=>r.full===repos[0].full).demo,spaces.repositories[0].demo);
 assert(index.repositories.every(r=>!r.overview&&!r.agentContext&&!r.metrics));assert.equal(index.repositories.find(r=>r.full===repos[1].full).screenshots.length,1);assert.deepEqual(S.trend(index.repositories.find(r=>r.full===repos[1].full)),S.trend(repos[1]));
 const first=await service.search({q:'collaboration',demos:false,sort:'name'});assert.equal(first.total,129);assert.equal(first.items.length,48);assert(!JSON.stringify(first.items).includes('searchText'));assert(!JSON.stringify(first.items).includes('paragraphs'));assert(!first.items.some(r=>r.availability==='unavailable'));assert.equal(first.facets.categories.Design,64);let ids=[...first.items.map(r=>r.full)],cursor=first.nextCursor;while(cursor){const page=await service.search({q:'collaboration',demos:false,sort:'name',cursor});ids.push(...page.items.map(r=>r.full));cursor=page.nextCursor}assert.equal(ids.length,129);assert.equal(new Set(ids).size,129);assert.equal(first.total,129);
 await assert.rejects(()=>service.search({q:'different',demos:false,sort:'name',cursor:first.nextCursor}),e=>e.code==='invalid_cursor');await assert.rejects(()=>service.search({limit:500}),e=>e.status===400);await assert.rejects(()=>service.search({source:'unknown'}),e=>e.status===400);await assert.rejects(()=>service.detail('../../secret'),e=>e.status===400);await assert.rejects(()=>service.detail('team/project-129'),e=>e.status===404);
 const filtered=await service.search({demos:false,q:'collaboration',exclude:[repos[1].full]});assert.equal(filtered.total,128);assert(!filtered.items.some(r=>r.full===repos[1].full));const space=await service.search({source:'huggingface'});assert(space.items.some(r=>r.full==='hf:team/space'));assert(space.items.some(r=>r.full===repos[0].full));
 const editorial={rows:[{...E.defaults()[1],mode:'daily',category:'Design',items:[]},{...E.defaults()[0],items:[repos[1].full]}]},one=await service.search({storefront:true,demos:false,seed:'a'},editorial),two=await service.search({storefront:true,demos:false,seed:'b'},editorial);assert.deepEqual(one.shelves[editorial.rows[0].id],two.shelves[editorial.rows[0].id]);assert.deepEqual(one.shelves[editorial.rows[1].id],[repos[1].full]);assert(one.shelfItems.some(r=>r.full===repos[1].full&&r.communityPosts?.length));assert(one.shelfItems.length<=150);
 const detail=await service.detail(repos[1].full);assert.equal(detail.repo.overview.paragraphs[0],'Searchable collaboration context.');assert.equal(detail.repo.screenshots.length,2);assert.equal(detail.repo.communityPosts.length,1);
 // Prove serving generated metadata does not depend on reading the monoliths.
 await rm(new URL('dist/catalog.json',root));await rm(new URL('dist/spaces.json',root));const independent=createBrowseService({root});assert.equal((await independent.search({q:'collaboration',demos:false})).total,129);assert((await independent.detail(repos[1].full)).repo.agentContext);
 const changed=JSON.parse(await readFile(new URL('data/browse/index.json',root)));changed.version='another-version';await writeFile(new URL('data/browse/index.json',root),JSON.stringify(changed));await assert.rejects(()=>createBrowseService({root}).search({q:'collaboration',demos:false,sort:'name',cursor:first.nextCursor}),e=>e.code==='catalog_changed');
 const accounts=createAccounts({config:{origin:'https://reposhelf.test'},legal:{active:false}});let handler=createEditorialHandler({accounts,browse:independent});
 async function call(url,body,origin='https://reposhelf.test'){const req=Readable.from(body?[JSON.stringify(body)]:[]);req.url=url;req.method=body?'POST':'GET';req.headers={origin};let result;const res={writeHead(status){this.status=status},end(value){result={status:this.status,data:JSON.parse(value)}}};await handler(req,res);return result}
 assert.equal((await call('/api/editorial?action=browse',{demos:false})).status,200);assert.equal((await call('/api/editorial?action=browse&manage=1',{demos:false})).status,503);assert.equal((await call('/api/editorial?action=browse',{demos:false},'https://evil.test')).status,403);assert.equal((await call('/api/editorial?action=detail&id='+repos[1].full)).status,200);
 handler=createEditorialHandler({accounts:{ready:true,config:{origin:'https://reposhelf.test'},origin(){},request:async()=>{throw Error('Temporary settings failure')}},browse:independent});const degraded=await call('/api/editorial?action=browse',{storefront:true,demos:false});assert.equal(degraded.status,200);assert(degraded.data.items.length>0);assert(degraded.data.editorialNotice.includes('Catalogue search is still available'));
 console.log('PASS: compact independent index, on-demand rich details, full-library facets, cross-provider deduplication, stable pagination/cursors, unavailable hiding, private exclusion, shelf ordering and origin/admin guards.');
}finally{await rm(dir,{recursive:true,force:true})}
