import assert from 'node:assert/strict';
import {discoveryQueries,searchRotation,searchCooldown} from '../scripts/discovery-search.mjs';
import {retryDelay,browserLane,balancedBrowserWork} from '../scripts/browser-work-policy.mjs';
import {runBrowserQueues} from '../scripts/browser-queues.mjs';
const now=Date.parse('2026-10-05T12:00:00Z'),queries=discoveryQueries(now);
assert.equal(new Set(queries).size,queries.length);
assert(queries.some(q=>q.includes('topic:threejs')));assert(queries.some(q=>q.includes('stars:0')));assert(queries.some(q=>q.includes('created:2020-')));
const first=searchRotation({},now),task=first.next();first.complete(task,{items:Array(100).fill({}),total_count:2500});
const saved=first.finish(),second=searchRotation(saved,now);assert.notEqual(second.next().q,task.q,'Closely spaced syncs continue to another query');
saved.cursor=0;assert.equal(searchRotation(saved,now).next().page,2,'Pagination survives workflow boundaries');
const tenth={...task,page:10};first.complete(tenth,{items:Array(100).fill({}),total_count:3000});assert.equal(first.state.pages[task.q],1);
const retry=searchRotation({},now),failed=retry.next();retry.retry(failed);assert.equal(retry.next().q,failed.q,'Throttled query resumes after its cooldown');
const primary=searchCooldown({status:403,rateRemaining:'0',rateReset:String((now+120000)/1000)},now);assert.equal(primary.reason,'primary_rate_limit');assert(Date.parse(primary.nextAllowedAt)>now+120000);
assert.equal(searchCooldown({status:403,rateRemaining:'10'},now).reason,'secondary_rate_limit');assert.equal(Date.parse(searchCooldown({status:429,retryAfter:'600'},now).nextAllowedAt),now+601000);
assert.equal(retryDelay('access_restricted',3),7*86400000);assert.equal(retryDelay('network_or_timeout',3),86400000);assert.equal(retryDelay('network_or_timeout',6),3*86400000);
const fresh={full:'team/new',demo:'https://demo.org'},failedEntry={...fresh,full:'team/repeated',demoHealth:{url:fresh.demo,consecutiveTemporaryFailures:5}},stale={...fresh,full:'team/stale',demoHealth:{url:fresh.demo,checkedAt:'2026-09-01'},screenshots:[{kind:'demo',url:fresh.demo}]};
assert.equal(browserLane(fresh),'admission');assert.equal(browserLane(stale),'maintenance');assert.equal(browserLane(failedEntry),'repair');assert.equal(browserLane({...failedEntry,demoReport:{id:9}}),'admission');
const work=balancedBrowserWork([fresh,failedEntry],[fresh,stale]);assert.equal(work.queues.admission.length,1);assert.equal(work.original.get(fresh.full),'previews');
let clock=0;const visits={admission:0,maintenance:0,repair:0},queues=Object.fromEntries(Object.keys(visits).map(l=>[l,Array.from({length:100},(_,i)=>({full:l+'/'+i}))]));
await runBrowserQueues(queues,async(r,lane)=>{visits[lane]++;clock+=1000},{deadline:100000,now:()=>clock,concurrency:()=>1,weights:work.weights});
assert(visits.admission>=55&&visits.admission<=65);assert(visits.maintenance>=25&&visits.maintenance<=35);assert(visits.repair>=5&&visits.repair<=15);
clock=0;let borrowed=0;await runBrowserQueues({admission:[],maintenance:[],repair:queues.repair},async()=>{borrowed++;clock++},{deadline:90,now:()=>clock,concurrency:()=>1,weights:work.weights});assert.equal(borrowed,90,'Idle capacity is borrowed without a fixed repair record cap');
console.log('PASS: durable varied discovery, pagination, throttle cooldowns and time-weighted admission/maintenance/repair lanes.');
