const test=(name,fn)=>{fn();console.log('PASS:',name)};const assert=require('node:assert/strict');const D=require('../dist/discovery.js');
const target='https://myapp.vercel.app/';
test('discovers Markdown, HTML, badge, reference, and bare demo links',()=>{
for(const text of [`[Live Demo](${target})`,`<a href="${target}">Try online</a>`,`[![Live Demo](https://shields.io/badge/demo)](${target})`,`[Playground][demo]\n\n[demo]: ${target}`,`## Live demo\n\n${target}`,`Live site: ${target}`,`[View live](${target})`])assert.equal(D.extractDemo(text),target,text);
});
test('does not treat docs, images, videos, deploy buttons, or example URLs as demos',()=>{for(const text of ['[Docs](https://docs.myapp.com)','[Demo](https://youtube.com/watch?v=123)','Demo: https://myapp.com/screenshot.png','[Demo](https://example.com)','[Demo](https://vercel.com/new/clone)','[Demo](javascript:alert(1))','```\nDemo: https://sample.app\n```'])assert.equal(D.extractDemo(text),null,text);assert.equal(D.extractDemo('[Website](https://myapp.com)','https://myapp.com'),null)});
test('discovery covers multiple signals without a mandatory webapp topic',()=>{const queries=D.searchQueries();assert(queries.length>=5);assert(queries.some(q=>q.includes('in:readme')));assert(!queries.some(q=>q.includes('topic:webapp')));const specific=D.searchQueries({query:'weather',category:'Design'});assert(specific[0].includes('weather'));assert(!specific[0].includes('topic:design'))});
test('all-repository toggle removes demo-specific qualifiers',()=>{const queries=D.searchQueries({demos:false});assert(queries.every(q=>!q.includes('demo')&&!q.includes('playground')))});
test('newest uses a recent creation window and popularity metadata preserves forks',()=>{assert(D.searchQueries({newest:true})[0].includes('created:>='));const r=D.mapRepo({full_name:'someone/app',name:'app',description:'A notes app',default_branch:'master',forks_count:50,stargazers_count:100});assert.equal(r.forks,50);assert.equal(r.branch,'master');assert.equal(r.category,'Productivity')});
