import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {createServer} from 'node:http';
import {createUnifiedHandler} from '../api/agent.mjs';
import {createXPipelineStatus} from '../lib/x-pipeline-status.mjs';
import {createXWorkflowControl} from '../lib/x-workflow-control.mjs';
import {publicRepository} from '../lib/submissions.mjs';
import {waitForCollector} from '../scripts/wait-x-collector.mjs';
const require=createRequire(import.meta.url),B=require('../dist/browse.js'),T=require('../dist/taxonomy.js');
for(const [description,category] of [['A command-line fuzzy finder','Developer tools'],['React state management','Developer tools'],['Home automation with local control','Productivity'],['Universal swarm intelligence engine','AI & machine learning']])assert.equal(T.annotate({name:'Example',description,category:'Other'}).category,category);
assert.equal(T.annotate({name:'Dance planner',description:'Plan dance events',topics:['python','react'],category:'Other'}).category,'Other','Dependency topics alone do not imply developer purpose');
const rows=[{full:'a/one',name:'One',category:'Design',subjects:['Mobile'],stars:100,forks:5},{full:'b/two',name:'Two',category:'Design',subjects:['Mobile'],stars:20,forks:2}];
const options={storefront:true,publicPools:true},editorial={rows:[{id:'design',builtin_key:'category:design',category:'Design',mode:'popular',enabled:true,items:[]},{id:'all',builtin_key:'category:all',category:'All projects',mode:'popular',enabled:true,items:[]}],builtinSetupRequired:false};
const orders={'':B.order(rows,'popular').map(r=>r.full),Design:B.order(rows,'popular').map(r=>r.full)};
assert.deepEqual(B.select(rows,{...options,precomputed:orders},editorial),B.select(rows,options,editorial));
assert.deepEqual(B.select(rows.slice(1),{...options,precomputed:orders},editorial),B.select(rows.slice(1),options,editorial),'Changed membership falls back to current ranking');
const service={info:async()=>({source:'same-service'}),search:async()=>({projects:[]})},key='x'.repeat(32),handler=createUnifiedHandler({service,auth:{key,local:true},gate:{check:async()=>({allowed:true})}}),server=createServer(handler);
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{const base='http://127.0.0.1:'+server.address().port;
 const rest=await fetch(base+'/api/agent?path=catalog',{headers:{Authorization:'Bearer '+key}});assert.equal(rest.status,200);assert.equal((await rest.json()).source,'same-service');
 const denied=await fetch(base+'/api/agent?protocol=mcp',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});assert.equal(denied.status,401);
 const mcp=await fetch(base+'/api/agent?protocol=mcp',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json',Accept:'application/json, text/event-stream'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'get_catalog_info',arguments:{}}})});assert.equal(mcp.status,200);const text=await mcp.text(),payload=text.startsWith('event:')?JSON.parse(text.split('\n').find(line=>line.startsWith('data:')).slice(5)):JSON.parse(text);assert.equal(payload.result.structuredContent.source,'same-service');
}finally{await new Promise(resolve=>server.close(resolve))}
let calls=0,at=0;const saved={revision:'v1',checkedAt:'2026-10-09T00:00:00Z',accepted:8,held:1},status=createXPipelineStatus({now:()=>at,checkpoint:{json:async path=>path.includes('x-intake')?saved:{commit:'abc',lastPublishedAt:'2026-10-09T01:00:00Z'}},fetcher:async url=>{calls++;if(url.includes('/runs?'))return Response.json({workflow_runs:[{id:1,status:'completed',conclusion:'success'}]});if(url.includes('summary.json'))return Response.json({runId:'1',collection:{postsRead:50},validation:{qualityReady:8}});return Response.json(saved)}});
const result=await status();assert.equal(result.intake.accepted,8);assert.equal(result.publication.status,'published');assert.equal(result.countsCurrent,true);const firstCalls=calls;await Promise.all([status(),status()]);assert.equal(calls,firstCalls);at=31000;await status();assert(calls>firstCalls);
const partial=createXWorkflowControl({token:'test',fetcher:async url=>url.includes('x-intake.yml/dispatches')?new Response(null,{status:403}):url.endsWith('/dispatches')?new Response(null,{status:204}):Response.json({workflow_runs:[]})});const dispatch=await partial.scan();assert.equal(dispatch.requested,true);assert.equal(dispatch.chained,false);assert.match(dispatch.reason,/Do not repeat/);
let attempts=[];const repo=await publicRepository('team/public',{token:'revoked',fetcher:async(url,options)=>{attempts.push(options.headers);return attempts.length===1?new Response(null,{status:401}):Response.json({id:1,private:false,full_name:'team/public'})}});assert.equal(repo.name,'team/public');assert.equal(attempts.length,2);assert(!attempts[1].Authorization);
let waited=0,clock=Date.parse('2026-10-09T06:20:00Z');const completed={id:22,created_at:'2026-10-09T06:17:00Z',status:'completed',conclusion:'success'};
assert.equal((await waitForCollector({now:()=>clock,sleep:async ms=>{clock+=ms},fetcher:async()=>Response.json({workflow_runs:[waited++?completed:{...completed,status:'queued'}, {id:21,created_at:'2026-10-09T02:00:00Z',status:'completed',conclusion:'success'}]})})).id,22,'Scheduled import waits for today’s collector rather than an older manual run');
await assert.rejects(waitForCollector({now:()=>clock,fetcher:async()=>Response.json({workflow_runs:[{...completed,conclusion:'failure'}]})}),/did not succeed/);
await assert.rejects(waitForCollector({now:()=>clock,timeoutMs:1,sleep:async ms=>{clock+=ms},fetcher:async()=>Response.json({workflow_runs:[]})}),/timed out/);
let paidDispatches=0;const importing=createXWorkflowControl({token:'test',fetcher:async url=>{if(url.endsWith('/dispatches'))paidDispatches++;return Response.json({workflow_runs:url.includes('x-intake.yml')?[{status:'in_progress'}]:[]})}});assert.equal((await importing.scan()).requested,false);assert.equal(paidDispatches,0);
console.log('PASS: exact ribbons, shared REST/MCP authentication, cached X status, successful collector chaining, failure/timeouts, duplicate import protection and public submission fallback.');
