import assert from 'node:assert/strict';import {Readable} from 'node:stream';import {createForksHandler} from '../api/forks.mjs';
let githubStatus=200,rows=[],state={page:1,page_offset:0,recheck_id:0},githubCalls=[],patches=[],leaseBusy=false;
const person={id:'00000000-0000-0000-0000-000000000001',githubId:'42',token:'owner'};
const accounts={config:{origin:'https://reposhelf.test',serviceKey:'secret'},origin(req){if(req.headers.origin!==this.config.origin)throw Object.assign(Error('Origin rejected'),{status:403})},async user(req){if(req.headers.cookie!=='owner')throw Object.assign(Error('Sign in'),{status:401});return person},async request(path,opts={}){if(path.includes('reposhelf_begin_fork_sync'))return leaseBusy?null:{...state};if(path.includes('reposhelf_save_verified_fork')){assert(opts.service);const row=opts.body.entry;rows=rows.filter(r=>r.github_fork_id!==row.github_fork_id).concat(row);return null}if(path.includes('fork_sync_state')){if(opts.method==='PATCH'){patches.push(opts.body);state={...state,...opts.body};return null}return [state]}if(path.includes('user_forks')){if(opts.method==='PATCH'){rows[0]={...rows[0],...opts.body};return null}if(path.includes('github_fork_id=gt.'))return rows.filter(r=>r.github_fork_id>state.recheck_id).slice(0,1);return rows}throw Error(path)}};
const parent={id:10,full_name:'team/canvas',name:'Canvas',description:'A useful project',stargazers_count:8,forks_count:2};
let details={id:20,fork:true,full_name:'real-owner/canvas',owner:{id:42},parent};let repoList=[{id:20,fork:true,owner:{id:42}}];
const handler=createForksHandler({accounts,fetcher:async url=>{githubCalls.push(url);if(githubStatus!==200)return Response.json({}, {status:githubStatus});if(url.endsWith('/user/42'))return Response.json({id:42,login:'real-owner'});if(url.includes('/users/real-owner/repos'))return Response.json(repoList);if(url.endsWith('/repositories/20'))return Response.json(details);throw Error(url)}});
async function run(method='POST',cookie='owner',body={username:'attacker',verified:true},origin=accounts.config.origin){const req=Readable.from([JSON.stringify(body)]);Object.assign(req,{url:'/api/forks',method,headers:{cookie,origin}});const res={headers:{},getHeader(k){return this.headers[k]},setHeader(k,v){this.headers[k]=v},writeHead(s,h){this.status=s;Object.assign(this.headers,h)},end(b){this.data=JSON.parse(b)}};await handler(req,res);return res}
assert.equal((await run('GET','')).status,401);assert.equal((await run('POST','owner',{},'https://attacker.test')).status,403);
let r=await run();assert.equal(r.status,200);assert.equal(r.data.complete,true);assert.equal(rows.length,1);assert.equal(rows[0].github_owner_id,'42');assert(githubCalls.every(u=>!u.includes('attacker')));
r=await run('GET');assert.equal(r.data.items[0].url,'https://github.com/real-owner/canvas');assert.equal(r.data.items[0].verified,true);
leaseBusy=true;assert.equal((await run()).status,409);leaseBusy=false;
githubStatus=429;r=await run();assert.equal(r.status,429);assert.equal(rows.length,1);assert.equal(rows[0].available,true);assert(patches.at(-1).last_error.includes('preserved'));
githubStatus=200;details={...details,owner:{id:99}};await run();assert.equal(rows[0].available,false,'Ownership change makes fork unavailable');
details={...details,owner:{id:42}};state.recheck_id=0;await run();assert.equal(rows[0].available,true,'Public fork restored');
repoList=Array.from({length:100},(_,i)=>({id:20,fork:true,owner:{id:42}}));rows=[];state={page:1,page_offset:0,recheck_id:0};r=await run();assert.equal(r.data.complete,false);assert.equal(state.page_offset,3,'Bounded batch persists progress');assert.equal(state.page,1);
person.githubId=null;assert.equal((await run()).status,403);
console.log('PASS: authenticated same-origin fork sync, immutable GitHub identity, no client verification claims, cross-device read shape, leases, resumable scans, temporary retention, ownership loss and restoration.');
