import assert from 'node:assert/strict';import {Readable} from 'node:stream';import {createAccounts} from '../lib/accounts.mjs';import {createAuthHandler} from '../api/auth.mjs';
const base='https://reposhelf.test',supa='https://fixture.supabase.co',calls=[];
const people={googler:{id:'00000000-0000-0000-0000-0000000000a1',identities:[{provider:'google',identity_data:{email:'private@example.org',name:'Gia Googler'}}],user_metadata:{name:'Gia Googler',email:'private@example.org'}},linked:{id:'00000000-0000-0000-0000-0000000000a2',identities:[{provider:'google',identity_data:{}},{provider:'github',identity_data:{sub:'77',user_name:'ghlinked'}}],user_metadata:{}},hubber:{id:'00000000-0000-0000-0000-0000000000a3',identities:[{provider:'github',identity_data:{sub:'88',user_name:'hubber'}}],user_metadata:{}}};
let session={access_token:'googler',refresh_token:'r',expires_in:3600,provider_token:'PROVIDER-SECRET'},linkReply={url:'https://github.com/login/oauth/authorize?client_id=x'};
const make=(google)=>createAccounts({legal:{active:false},config:{url:supa,key:'public-key',serviceKey:'server-key',origin:base,google},fetcher:async(url,opts)=>{const u=new URL(url),token=opts.headers.Authorization?.replace('Bearer ',''),body=opts.body&&JSON.parse(opts.body);calls.push({path:u.pathname,search:u.search,token,body});if(u.pathname==='/auth/v1/user')return people[token]?Response.json(people[token]):Response.json({},{status:401});if(u.pathname==='/auth/v1/token')return Response.json(session);if(u.pathname==='/auth/v1/user/identities/authorize')return linkReply?Response.json(linkReply):Response.json({code:'manual_linking_disabled'},{status:400});return Response.json({})}});
async function run(accounts,url,{cookie='',origin=base}={}){const req=Readable.from([]);Object.assign(req,{url,method:'GET',headers:{origin,cookie}});const res={headers:{},setHeader(k,v){this.headers[k.toLowerCase()]=v},getHeader(k){return this.headers[k.toLowerCase()]},writeHead(s,h={}){this.status=s;for(const [k,v] of Object.entries(h))this.headers[k.toLowerCase()]=v},end(b){if(b)try{this.data=JSON.parse(b)}catch{}}};await createAuthHandler(accounts)(req,res);return res}
const cookiesOf=res=>[].concat(res.headers['set-cookie']||[]);const val=(res,name)=>decodeURIComponent((cookiesOf(res).find(c=>c.includes(`-${name}=`))||'').split(';')[0].split('=').slice(1).join('='));
// Google is off until the operator enables it
let accounts=make(false),r=await run(accounts,'/api/auth?action=start&provider=google');assert.equal(r.status,302);assert.equal(r.headers.location,'/?signin=failed');assert.equal(cookiesOf(r).length,0,'No handshake cookies are set when Google is off');
assert.equal((await run(accounts,'/api/auth')).data.googleEnabled,false);
// Google flow: provider is sent to Supabase and the handshake is tagged
accounts=make(true);r=await run(accounts,'/api/auth?action=start&provider=google');const redirect=new URL(r.headers.location);assert.equal(redirect.origin,supa);assert.equal(redirect.searchParams.get('provider'),'google');assert(val(r,'verifier').endsWith('~google'));
assert.equal((await run(accounts,'/api/auth')).data.googleEnabled,true);
r=await run(accounts,'/api/auth?action=start&provider=facebook');assert.equal(new URL(r.headers.location).searchParams.get('provider'),'github','Unknown providers fall back to GitHub');
// The Google access token is never stored as a GitHub token; a GitHub flow does store its token
const verifierCookie=flow=>`__Host-reposhelf-verifier=${encodeURIComponent('v3rifier~'+flow)}`;
r=await run(accounts,'/api/auth?action=callback&code=abc',{cookie:verifierCookie('google')});assert.equal(r.status,302);assert.notEqual(r.headers.location,'/?signin=failed');const googleCookie=cookiesOf(r).find(c=>c.includes('-github='));assert(googleCookie.includes('Max-Age=0')&&!googleCookie.includes('PROVIDER-SECRET'),'Google token is discarded');assert(!cookiesOf(r).join(' ').includes('PROVIDER-SECRET'));assert.equal(calls.findLast(c=>c.path==='/auth/v1/token').body.code_verifier,'v3rifier');
r=await run(accounts,'/api/auth?action=callback&code=abc',{cookie:verifierCookie('github')});assert(val(r,'github')==='PROVIDER-SECRET','A GitHub sign-in keeps its provider token for fork verification');
r=await run(accounts,'/api/auth?action=callback&code=abc',{cookie:'__Host-reposhelf-verifier=legacyverifier'});assert.equal(r.headers.location==='/?signin=failed',false,'A handshake started before this change still completes');
// Session shape for Google-only, linked and GitHub users
const session_of=async token=>(await run(accounts,'/api/auth',{cookie:`__Host-reposhelf-access=${token}`})).data.user;
let u=await session_of('googler');assert.equal(u.githubConnected,false);assert.deepEqual(u.providers,['google']);assert.equal(u.name,'Gia Googler');assert(!JSON.stringify(u).includes('private@example.org'),'The email address is never exposed as a display name');assert.equal(u.avatarUrl,null);
u=await session_of('linked');assert.equal(u.githubConnected,true);assert.deepEqual(u.providers.sort(),['github','google']);assert.equal(u.name,'ghlinked');
u=await session_of('hubber');assert.deepEqual(u.providers,['github']);
// Linking GitHub needs a signed-in session and manual linking enabled in Supabase
r=await run(accounts,'/api/auth?action=link-github&return=%2Fsubmissions.html');assert.equal(r.status,401,'Linking requires a session');
r=await run(accounts,'/api/auth?action=link-github&return=%2Fsubmissions.html',{cookie:'__Host-reposhelf-access=googler'});assert.equal(r.status,302);assert.equal(r.headers.location,linkReply.url);assert(val(r,'verifier').endsWith('~link-github'));assert.equal(val(r,'return'),'/submissions.html');const link=calls.findLast(c=>c.path==='/auth/v1/user/identities/authorize');assert.equal(link.token,'googler','The signed-in user token authorises the link');assert(link.search.includes('provider=github')&&link.search.includes('skip_http_redirect=true')&&link.search.includes('code_challenge='));
r=await run(accounts,'/api/auth?action=callback&code=abc',{cookie:verifierCookie('link-github')+'; __Host-reposhelf-return=%2Faccount.html'});assert.equal(r.status,302);assert(val(r,'github')==='PROVIDER-SECRET','Linking GitHub stores the GitHub token');
linkReply=null;r=await run(accounts,'/api/auth?action=link-github',{cookie:'__Host-reposhelf-access=googler'});assert.equal(r.headers.location,'/account.html?link=failed','Disabled manual linking fails gracefully');
linkReply={url:'https://evil.example/phish'};r=await run(accounts,'/api/auth?action=link-github',{cookie:'__Host-reposhelf-access=googler'});assert.equal(r.headers.location,'/account.html?link=failed','Unexpected link destinations are refused');
console.log('PASS: Google sign-in is opt-in, tags the handshake, never stores a Google token as GitHub access, hides emails, and links GitHub safely.');
