import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {pathToFileURL} from 'node:url';import {createRequire} from 'node:module';import {Readable} from 'node:stream';
import {applyListingControls,createListingControls} from '../lib/listing-policy.mjs';import {qualityOverview} from '../lib/catalog-quality.mjs';import {generateBrowseIndex} from '../lib/browse-index.mjs';import {createBrowseService} from '../lib/browse-service.mjs';import {createCatalogService} from '../lib/catalog-service.mjs';import {createEditorialHandler} from '../api/editorial.mjs';
const Q=createRequire(import.meta.url)('../dist/quality.js'),now=Date.now(),r={full:'team/app',name:'An app',description:'Author description',category:'Design',availability:'available',demo:'https://demo.example.org',lastCheckedAt:new Date(now).toISOString(),demoHealth:{url:'https://demo.example.org',status:'working',checkedAt:new Date(now).toISOString()},screenshots:[{src:'https://demo.example.org/preview.jpg',kind:'demo',url:'https://demo.example.org',capturedAt:new Date(now).toISOString()}]};
assert(Q.featuredEligible(r));assert(!Q.featuredEligible({...r,screenshots:[]}));assert(!Q.featuredEligible({...r,demoHealth:{...r.demoHealth,checkedAt:new Date(now-8*86400000).toISOString()}}));assert(!Q.featuredEligible({...r,demoHealth:{...r.demoHealth,error:true}}));assert(!Q.featuredEligible({...r,demo:'https://changed.example.org'}));{const hour=3600000,snapshotAt=now-60*hour,checked=new Date(snapshotAt-10*hour).toISOString(),aged={...r,lastCheckedAt:checked,demoHealth:{...r.demoHealth,checkedAt:checked}};
assert.equal(Q.publishedEligible(aged,now),false,'Evidence 70 hours old fails when judged against the visitor clock');
assert.equal(Q.publishedEligible(aged,Q.evidenceTime(new Date(snapshotAt).toISOString(),now)),true,'The same listing stays published when judged at the catalogue snapshot time');
assert.equal(Q.evidenceTime(new Date(now-100*hour).toISOString(),now),now,'A snapshot older than 72 hours falls back to the real clock');
assert.equal(Q.evidenceTime(new Date(now+hour).toISOString(),now),now,'A snapshot in the future is ignored');assert.equal(Q.evidenceTime('not a date',now),now);assert.equal(Q.evidenceTime(undefined,now),now);
assert.equal(Q.evidenceTime(new Date(snapshotAt).toISOString(),now),snapshotAt);}
assert(!Q.featuredEligible({...r,lastCheckedAt:new Date(now-3*86400000).toISOString()}),'Featuring requires the listing to be publishable, including a repository check in the last 48 hours');
let controls=[{project_id:r.full,visibility:'visible',description:'Editorial description',revision:1,preview_rejected:true,rejected_preview:r.screenshots[0].src,rejected_at:new Date(now+1000).toISOString()}];const edited=applyListingControls([r],controls)[0];assert.equal(edited.authorDescription,r.description);assert.equal(edited.description,'Editorial description');assert.equal(edited.screenshots.length,0);assert.equal(applyListingControls([{...r,screenshots:[{...r.screenshots[0],capturedAt:new Date(now+2000).toISOString()}]}],controls)[0].screenshots.length,1,'Fresh recapture recovers rejected preview');assert.equal(qualityOverview([r],controls).coverage.screenshot,1);
const dir=await mkdtemp(tmpdir()+'/reposhelf-launch-'),root=pathToFileURL(dir+'/');try{await mkdir(new URL('dist/',root));await writeFile(new URL('dist/catalog.json',root),JSON.stringify({repositories:[r]}));await generateBrowseIndex(root);const browse=createBrowseService({root,controls:async()=>controls}),catalog=createCatalogService({root,controls:async()=>controls});assert.equal((await browse.detail(r.full)).repo.description,'Editorial description');controls=[{project_id:r.full,visibility:'hidden'}];assert.equal((await browse.search({q:'team/app'})).total,0);await assert.rejects(browse.detail(r.full),e=>e.status===404);await assert.rejects(catalog.project({id:r.full}),e=>e.status===404);assert.equal((await catalog.search({q:'team/app'})).total,0);controls=[];assert.equal((await browse.search({q:'team/app'})).total,1,'Restoring visibility restores existing entry');await mkdir(new URL('data/',root),{recursive:true});await writeFile(new URL('data/listing-controls.json',root),JSON.stringify({items:[{project_id:'excalidraw/excalidraw',visibility:'excluded'}]}));const index=await generateBrowseIndex(root);assert(!index.index.repositories.some(r=>r.full==='excalidraw/excalidraw'),'Hard-coded picks cannot resurrect excluded listings');
let admin=false,person=true,calls=[];const accounts={ready:true,config:{origin:'https://reposhelf.test'},legal:{active:false},origin(req){if(req.headers.origin!==this.config.origin)throw Object.assign(Error('Origin'),{status:403})},async user(){if(!person)throw Object.assign(Error('Sign in'),{status:401});return {githubId:'1',id:'member',token:'member'}},async admin(){if(!admin)throw Object.assign(Error('Admin'),{status:403});return {id:'admin',token:'admin'}},async request(path,opts){calls.push({path,opts});if(path.endsWith('reposhelf_report_listing'))return {id:'receipt',status:'open'};return []}};const handler=createEditorialHandler({checkpoint:{json:async()=>null},accounts,browse});async function call(action,body,headers={}){const req=Readable.from([]);Object.assign(req,{method:body?'POST':'GET',url:'/api/editorial?action='+action,body,headers:{origin:accounts.config.origin,...headers}});const res={writeHead(status){this.status=status},end(body){this.data=JSON.parse(body)}};await handler(req,res);return res}
assert.equal((await call('report',{id:r.full,reason:'broken_demo',explanation:'Example issue'})).status,202);assert.equal(calls.at(-1).opts.token,'member');assert.equal((await call('report',{id:r.full,reason:'invalid',explanation:''})).status,400);assert.equal((await call('report',{id:r.full,reason:'broken_demo',explanation:''},{origin:'https://evil.test'})).status,403);assert.equal((await call('reports')).status,403);person=false;assert.equal((await call('report',{id:r.full,reason:'broken_demo',explanation:''})).status,401);admin=true;assert.equal((await call('reports')).status,200);
let expires=0,available=true;const retained=createListingControls({root,now:()=>expires,accounts:{ready:true,request:async()=>{if(!available)throw Error('Temporary');return [{project_id:r.full,visibility:'excluded'}]}}});assert.equal((await retained())[0].visibility,'excluded');expires=40000;available=false;assert.equal((await retained())[0].visibility,'excluded','Temporary storage errors retain cached decisions');
}finally{await rm(dir,{recursive:true,force:true})}
console.log('PASS: featured freshness/preview gates, editorial provenance, rejected-preview recovery, hidden listings across storefront/API, durable default-pick exclusions, report privacy/auth/origin and temporary moderation retention.');
