import assert from 'node:assert/strict';import {Readable} from 'node:stream';import {createAuthHandler} from '../api/auth.mjs';import {legalConfig,legalStatus,requireLegal,LEGAL_VERSION} from '../lib/legal.mjs';import {createCollectionHandler,bookmarkSnapshot} from '../api/collection.mjs';
const config={operator:'Test operator',country:'Test country',contactEmail:'legal@example.org',active:true,acceptance:true,version:LEGAL_VERSION};assert.equal(legalConfig({},{}).active,false);assert.equal(legalConfig({REPOSHELF_OPERATOR_NAME:'Test',REPOSHELF_OPERATOR_COUNTRY:'GB',REPOSHELF_CONTACT_EMAIL:'invalid'}).active,false);
const draft=legalConfig({});assert.equal(draft.serviceName,'RepoShelf');assert.equal(draft.country,'United Kingdom');assert.equal(draft.operator,'');assert.equal(draft.active,false);assert.equal(legalConfig({REPOSHELF_CONTACT_EMAIL:'privacy@example.org'}).active,false,'A dedicated email must not activate documents without a legal operator');
assert.equal(legalConfig({REPOSHELF_OPERATOR_NAME:'Test',REPOSHELF_CONTACT_EMAIL:'legal@example.org'}).acceptance,false,'Sign-in acceptance is off unless REPOSHELF_REQUIRE_ACCEPTANCE=1');assert.equal(legalConfig({REPOSHELF_OPERATOR_NAME:'Test',REPOSHELF_CONTACT_EMAIL:'legal@example.org',REPOSHELF_REQUIRE_ACCEPTANCE:'1'}).acceptance,true);
let accepted=false,calls=[],stored=[];const person={id:'00000000-0000-0000-0000-000000000001',token:'member',name:'maker',githubId:'42'};
const accounts={legal:config,config:{origin:'https://reposhelf.test',serviceKey:'secret'},ready:true,user:async()=>person,isAdmin:async()=>false,origin(req){if(req.headers.origin!==this.config.origin)throw Object.assign(Error('Rejected origin'),{status:403})},request:async(path,opts={})=>{calls.push({path,...opts});if(path.includes('legal_acceptances'))return accepted?[{accepted_at:'2026-10-03T12:00:00Z'}]:[];if(path.includes('reposhelf_accept_legal')){accepted=true;return '2026-10-03T12:00:00Z'}if(path.includes('reposhelf_save_bookmark')){stored.push(opts.body);return null}if(path.includes('user_likes'))return stored.map(x=>({project_id:x.project,project_snapshot:x.snapshot}));return null}};
{const passive={...config,acceptance:false},before=calls.length,status=await legalStatus(accounts,person,passive);assert.deepEqual(status,{active:true,required:false,acceptance:false,version:LEGAL_VERSION});assert.equal(calls.length,before,'No database read when acceptance is off');await requireLegal(accounts,person,passive)}
assert.equal((await legalStatus(accounts,person,config)).required,true);await assert.rejects(()=>requireLegal(accounts,person,config),e=>e.status===428);
async function run(handler,url,{method='GET',body,origin=accounts.config.origin}={}){const req=Readable.from(body?[JSON.stringify(body)]:[]);Object.assign(req,{url,method,headers:{origin}});const res={writeHead(s){this.status=s},end(body){this.data=JSON.parse(body)}};await handler(req,res);return res}
const auth=createAuthHandler(accounts,config);let r=await run(auth,'/api/auth');assert(r.data.legal.required);assert(!JSON.stringify(r.data).includes('secret'));
assert.equal((await run(auth,'/api/auth?action=accept-legal',{method:'POST',body:{terms:LEGAL_VERSION,privacy:LEGAL_VERSION,agree:false}})).status,400);assert.equal((await run(auth,'/api/auth?action=accept-legal',{method:'POST',body:{terms:LEGAL_VERSION,privacy:LEGAL_VERSION,agree:true},origin:'https://attacker.test'})).status,403);
r=await run(auth,'/api/auth?action=accept-legal',{method:'POST',body:{terms:LEGAL_VERSION,privacy:LEGAL_VERSION,agree:true}});assert.equal(r.status,200);assert.equal((await legalStatus(accounts,person,config)).required,false);assert.equal((await run(auth,'/api/auth')).data.legal.required,false);
accepted=false;await assert.rejects(()=>requireLegal(accounts,person),e=>e.status===428);accepted=true;const bookmarks=createCollectionHandler({accounts,catalog:{project:async()=>{throw Object.assign(Error('Not indexed'),{status:404})}}});r=await run(bookmarks,'/api/collection',{method:'PUT',body:{id:'new/project',repo:{name:'New project',demo:'https://demo.example.org',verified:true,admin:true}}});assert.equal(r.status,200);assert.equal(stored[0].snapshot.name,'New project');assert.equal(stored[0].snapshot.verified,undefined);assert.equal((await run(bookmarks,'/api/collection')).data.items[0].repo.full,'new/project');assert.equal(bookmarkSnapshot('new/project',{demo:'javascript:alert(1)'}).demo,null);assert.equal((await run(bookmarks,'/api/collection',{method:'PUT',body:{id:'../../etc'}})).status,400);
console.log('PASS: active legal acceptance blocks protected actions, versions/explicit agreement/origin checked, operator setup is transparent, unindexed bookmarks and safe snapshots persist.');
