import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {writeFile} from 'node:fs/promises';
import {popularityGrowth} from '../lib/popularity-growth.mjs';
import {repositoryCheckPlan,dueEntries,CHECK_INTERVAL_MS} from '../scripts/catalog-health.mjs';
import {createCatalogService} from '../lib/catalog-service.mjs';
import {fixture} from './api-fixture.mjs';
const require=createRequire(import.meta.url),S=require('../dist/storefront.js'),UI=require('../dist/admin-growth.js');
const now=Date.parse('2026-10-04T12:00:00Z'),day=86400000,at=n=>new Date(now-n*day).toISOString();
const base={full:'team/stars',name:'Stars',demo:'https://demo.example.org',availability:'available',lastCheckedAt:at(0),stars:170,forks:27,metrics:[{at:at(7),stars:100,forks:20},{at:at(0),stars:170,forks:27}]};
const forks={...base,full:'team/forks',name:'Forks',stars:107,forks:90,metrics:[{at:at(7),stars:100,forks:20}]};
const rows=[base,forks,{...base,full:'team/stale',lastCheckedAt:at(3)},{...base,full:'team/warming',metrics:[]},{...base,full:'team/no-date',lastCheckedAt:null},{...base,full:'team/flat',stars:100,forks:20},{...base,full:'team/decreased',stars:90,forks:10},{...base,full:'team/gone',availability:'unavailable'},{...base,full:'hf:team/space',source:'huggingface',likes:100000},{...base,full:'team/no-demo',demo:null}];
let data=popularityGrowth(rows,{now});assert.equal(data.total,2);assert.equal(data.items[0].id,base.full);assert.equal(data.items[0].score,S.trend(base,now).score);assert.equal(data.items[0].starGain,70);assert.equal(data.items[0].starsPerDay,10);assert.equal(data.coverage.eligible,7);assert.equal(data.coverage.measured,4);assert.equal(data.coverage.baselineMissing,1);assert.equal(data.coverage.stale,1);assert.equal(data.coverage.missingObservation,1);assert.equal(data.coverage.observed24h,5);
assert.equal(popularityGrowth(rows,{now,sort:'forks'}).items[0].id,forks.full);assert.equal(popularityGrowth(rows,{now,sort:'stars',limit:1}).items.length,1);
assert.equal(popularityGrowth([{...base,lastCheckedAt:at(1),metrics:[{at:at(8),stars:100,forks:20}]}],{now}).items[0].days,7,'Window ends at the observation, not the page visit');
assert.equal(popularityGrowth([{...base,lastCheckedAt:at(-1)}],{now}).total,0,'Future observations cannot qualify');
assert.equal(popularityGrowth([{...base,metrics:[{at:at(10),stars:0,forks:0}]}],{now}).total,0,'Old baselines excluded');
assert.equal(popularityGrowth([{...base,metrics:[{at:at(.5),stars:0,forks:0}]}],{now}).total,0,'Same-day growth excluded');
assert.equal(popularityGrowth([{...base,checkError:{kind:'rate_limit'},trendSummary:{score:999}}],{now}).items[0].score,S.trend(base,now).score,'Transient failures preserve last successful evidence');
assert.equal(popularityGrowth([{...base,metrics:[...base.metrics,{at:at(5),stars:null,forks:0}]}],{now}).items[0].history.length,2,'Invalid points are not plotted');
assert.throws(()=>popularityGrowth(rows,{sort:'watchers'}));
const html=UI.render(data);assert(html.includes('Stars over time'));assert(html.includes('Forks over time'));assert(html.includes('Daily observation coverage'));assert(!UI.render(popularityGrowth([{...base,name:'<script>alert(1)</script>'}],{now})).includes('<script>'));assert(UI.render(popularityGrowth([],{now})).includes('No measured positive growth'));assert(UI.chart(base.metrics,'stars','Stars').includes('aria-label="Stars: 100 to 170"'));
assert.equal(CHECK_INTERVAL_MS,48*3600000);assert.equal(dueEntries([{...base,lastCheckedAt:at(47/24)}],now).length,0);assert.equal(dueEntries([{...base,lastCheckedAt:at(2)}],now).length,1);
assert.equal(repositoryCheckPlan(Array(4200),{remaining:950,authenticated:true}).limit,500);
assert.equal(repositoryCheckPlan(Array(6500),{remaining:1000,authenticated:true}).limit,650);
assert.equal(repositoryCheckPlan(Array(10000),{remaining:5000,authenticated:true}).limit,750);
assert.equal(repositoryCheckPlan(Array(10000),{remaining:5000,authenticated:true}).dailyCapacitySufficient,false,'A growing catalogue exposes capacity shortfall without capping catalogue size');
assert.equal(repositoryCheckPlan(Array(4200),{remaining:200,authenticated:true}).limit,0,'Reserve API budget');
assert.equal(repositoryCheckPlan(Array(4200),{remaining:60}).limit,50);
assert.equal(repositoryCheckPlan(Array(4200),{authenticated:true}).limit,500,'Unknown allowance uses conservative prior batch');
const f=await fixture();try{
 const shift=timestamp=>new Date(Date.now()-(now-Date.parse(timestamp))).toISOString();
 const currentRows=rows.map(r=>({...r,lastCheckedAt:r.lastCheckedAt?shift(r.lastCheckedAt):null,metrics:r.metrics.map(p=>({...p,at:shift(p.at)}))}));
 await writeFile(new URL('dist/catalog.json',f.root),JSON.stringify({repositories:currentRows}));
 const service=createCatalogService({root:f.root,controls:async()=>[{project_id:base.full,visibility:'hidden'}]});const ranked=await service.popularity();
 assert(ranked.items.some(r=>r.id===forks.full),'Visible qualified projects still rank');assert.equal(ranked.items.some(r=>r.id===base.full),false,'Moderated entries are absent');
 await assert.rejects(()=>service.popularity({sort:'watchers'}),e=>e.status===400);await assert.rejects(()=>service.popularity({limit:51}),e=>e.status===400);
}finally{await f.cleanup()}
console.log('PASS: measured growth matches Trending, daily-rate sorting, stale/missing/decreasing observations, retry preservation, bounded safe history charts, moderation, and daily API-budget planning.');
