import assert from 'node:assert/strict';import {Readable} from 'node:stream';import {createHmac} from 'node:crypto';import {createPromotionHandler} from '../api/promotions.mjs';import {OFFER,verifyEvent,requireTest,createPayments} from '../lib/promotion-payments.mjs';import {demoAvailable} from '../lib/promotion-health.mjs';
const id='10000000-0000-0000-0000-000000000001',attempt='20000000-0000-0000-0000-000000000001',person={id:'00000000-0000-0000-0000-000000000001',token:'owner',githubId:'1',githubToken:'private-token'};let admin=true,githubOwner='1',type='User',health='available',demoUrl='https://demo.example.org',record={id,user_id:person.id,repo_name:'owner/project',repo_id:'42',owner_id:'1',snapshot:{full:'owner/project',name:'Project',demo:'https://demo.example.org'},status:'approved',checkout_attempt:attempt,updated_at:new Date().toISOString()},writes=[];
const accounts={ready:true,legal:{active:false},config:{origin:'https://reposhelf.test',serviceKey:'private'},origin(req){if(req.headers.origin!==this.config.origin)throw Object.assign(Error('Origin'),{status:403})},user:async()=>person,admin:async()=>{if(!admin)throw Object.assign(Error('Forbidden'),{status:403});return person},isAdmin:async()=>admin,request:async(path,opts)=>{if(path.includes('rpc/reposhelf_promotion_write')){const {operation,payload}=opts.body;writes.push({operation,payload});if(operation==='reserve'){record.status='checkout'}if(operation==='session')record.checkout_session=payload.session;if(operation==='paid'){record.status='paid_waiting';record.payment_intent=payload.payment}if(operation==='health')record.status=payload.health==='available'?'active':'paused';if(operation==='request')record.status='pending';return {...record}}return [{...record}]}};
const settings={key:'sk_test_fixture',webhook:'whsec_fixture',syncKey:'s'.repeat(32)},session={id:'cs_test_fixture',livemode:false,mode:'payment',metadata:{promotion_id:id,attempt},client_reference_id:id,amount_total:1500,currency:'gbp',payment_status:'unpaid',status:'open',url:'https://checkout.stripe.com/c/pay/test'},payments={create:async()=>session,session:async()=>session,refund:async()=>({status:'succeeded'})},catalog={project:async()=>({project:{name:'Project',description:'Demo',demo:{url:demoUrl},repositoryAvailability:{status:'available'}}})},fetcher=async()=>new Response(JSON.stringify({id:42,full_name:'owner/project',private:false,owner:{type,id:githubOwner}}),{status:200});
const handler=createPromotionHandler({accounts,catalog,settings,payments,fetcher,demoCheck:async()=>health});
async function run(action,{method='GET',body,origin=accounts.config.origin,headers={}}={}){const raw=body===undefined?'':typeof body==='string'?body:JSON.stringify(body),req=Readable.from([Buffer.from(raw)]);Object.assign(req,{url:'/api/promotions?action='+action,method,headers:{origin,...headers}});const res={writeHead(s){this.status=s},end(v){this.data=JSON.parse(v)}};await handler(req,res);return res}
assert.throws(()=>requireTest({key:'sk_live_disallowed',webhook:'whsec_fixture'}),e=>e.status===503);
assert.equal((await run('eligibility&repo=owner/project')).data.eligible,true);githubOwner='2';assert.equal((await run('eligibility&repo=owner/project')).data.eligible,false);githubOwner='1';type='Organization';assert.equal((await run('request',{method:'POST',body:{repo:'owner/project'}})).status,403);type='User';admin=false;assert.equal((await run('review',{method:'POST',body:{id,decision:'approved',note:''}})).status,403);assert.equal((await run('mine')).status,403);assert.equal((await run('eligibility&repo=owner/project')).status,403);assert.equal((await run('request',{method:'POST',body:{repo:'owner/project'}})).status,403);admin=true;
assert.equal((await run('request',{method:'POST',body:{repo:'owner/project'},origin:'https://evil.test'})).status,403);
record.status='approved';demoUrl='https://changed.example.org';assert.equal((await run('checkout',{method:'POST',body:{id}})).status,409,'Changed demo must be reviewed before any payment');assert(!writes.some(w=>w.operation==='reserve'));demoUrl='https://demo.example.org';const checked=await run('checkout',{method:'POST',body:{id,amount:1,currency:'usd'}});assert.equal(checked.data.url,session.url);assert.equal(writes.at(-1).operation,'session');assert(!writes.some(w=>w.operation==='paid'),'Redirect does not mark paid');
const signature=raw=>{const t=Math.floor(Date.now()/1000);return 't='+t+',v1='+createHmac('sha256',settings.webhook).update(t+'.'+raw).digest('hex')};
session.payment_status='paid';session.status='complete';session.payment_intent='pi_fixture';const event={livemode:false,type:'checkout.session.completed',data:{object:session}},raw=JSON.stringify(event);assert.equal((await run('webhook',{method:'POST',body:raw,headers:{'stripe-signature':'invalid'}})).status,400);assert.equal((await run('webhook',{method:'POST',body:raw,headers:{'stripe-signature':signature(raw)}})).status,200);assert.equal(record.status,'active');assert.equal(writes.find(w=>w.operation==='paid').payload.amount,1500);session.amount_total=1;const wrong=JSON.stringify(event);assert.equal((await run('webhook',{method:'POST',body:wrong,headers:{'stripe-signature':signature(wrong)}})).status,400);session.amount_total=1500;
const live=JSON.stringify({...event,livemode:true});assert.equal((await run('webhook',{method:'POST',body:live,headers:{'stripe-signature':signature(live)}})).status,400);
admin=false;assert.equal((await run('feed')).data.items.length,0,'Test promotions hidden from public visitors');admin=true;record.remaining_seconds=2592000;assert.equal((await run('feed')).data.items.length,1);health='unavailable';await run('refresh',{method:'POST',body:{id}});assert.equal(record.status,'paused');health='available';await run('refresh',{method:'POST',body:{id}});assert.equal(record.status,'active');assert.equal((await run('sync',{method:'POST',headers:{authorization:'Bearer wrong'}})).status,401);
const oldRaw=JSON.stringify(event);assert.throws(()=>verifyEvent(oldRaw,'t=1,v1='+'0'.repeat(64),settings.webhook),e=>e.status===400);
let sent;const gateway=createPayments(settings,{fetcher:async(url,options)=>{sent={url,options};return new Response(JSON.stringify(session))}});await gateway.create(record,accounts.config.origin);const params=sent.options.body;assert.equal(params.get('mode'),'payment');assert.equal(params.get('line_items[0][price_data][unit_amount]'),'1500');assert.equal(params.get('line_items[0][price_data][currency]'),'gbp');assert(sent.options.headers['Idempotency-Key'].includes(attempt));assert(!params.has('subscription_data'));
let networkCalls=0;assert.equal(await demoAvailable('https://private.example',{resolver:async()=>[{address:'127.0.0.1',family:4}],send:async()=>{networkCalls++}}),'temporary');assert.equal(networkCalls,0);assert.equal(await demoAvailable('https://public.example',{resolver:async()=>[{address:'8.8.8.8',family:4}],send:async()=>({status:404})}),'unavailable');assert.equal(await demoAvailable('https://public.example',{resolver:async()=>[{address:'8.8.8.8',family:4}],send:async()=>({status:429})}),'temporary');
console.log('PASS: immutable personal ownership, admin approval, origin/price enforcement, test-only checkout, signed webhooks, paid activation, private test previews, pause/recovery and public-IP-pinned demo checks.');
