import assert from 'node:assert/strict';import {Readable} from 'node:stream';import {createRequire} from 'node:module';
import {createAuthHandler} from '../api/auth.mjs';import {createOpenHandler} from '../api/open.mjs';import {syncAlerts,storefrontAlerts,enrichmentAlerts,monitor} from '../scripts/monitor-health.mjs';import {requiresAccount} from '../lib/outgoing-policy.mjs';
const B=createRequire(import.meta.url)('../dist/browse.js'),now=Date.now(),at=new Date(now).toISOString();
const repos=[{full:'team/react',name:'React canvas',description:'Design with React',category:'Design',technologies:['React'],availability:'available',demo:'https://demo.org'},{full:'team/planner',name:'Planner',description:'Plan your work',category:'Productivity',availability:'available',demo:'https://planner.org'}];
let data=B.select(repos,{q:'recat',demos:true,limit:48});assert.equal(data.total,0);assert(data.suggestions.some(s=>s.options.q==='react'));for(const s of data.suggestions)assert(B.select(repos,{...s.options,demos:true}).total>0);
data=B.select(repos,{q:'react',category:'Finance',technology:'Python',demos:true});assert(data.suggestions.some(s=>!s.options.category&&!s.options.technology));assert(!B.select(repos,{q:'recat',exclude:['team/react'],demos:true}).suggestions.some(s=>s.options.q==='react'),'Suggestions respect hidden history');assert.equal(B.select(repos,{q:'react',demos:true}).suggestions,undefined);assert.deepEqual(B.order([{...repos[0],latestRelease:{publishedAt:new Date(now-86400000).toISOString()}},{...repos[1],latestRelease:{publishedAt:at}}],'releases').map(r=>r.full),['team/planner','team/react']);
for(const url of ['https://github.com/team/app','https://github.com/team/app/blob/main/README.md','https://spdx.org/licenses/MIT.html','https://demo.org'])assert(!requiresAccount(new URL(url)));
for(const url of ['https://github.com/team/app/fork','https://github.com/Team/App/FORK/','https://www.github.com/team/app/%66ork','https://huggingface.co/spaces/team/app?duplicate=true'])assert(requiresAccount(new URL(url)));
const origin='https://reposhelf.test',calls=[];let signedIn=true,fresh=true,allowed=true,missing=false,cleared=false;
const accounts={config:{origin,serviceKey:'private-secret'},ready:true,legal:{active:false},origin(req){if(req.headers.origin!==origin)throw Object.assign(Error('Origin'),{status:403})},async user(){if(!signedIn)throw Object.assign(Error('Sign in'),{status:401});return {id:'member-id',token:'member',githubId:'42',signedInAt:new Date(now-(fresh?0:3600000)).toISOString()}},clear(){cleared=true},async request(path,options){calls.push({path,options});if(missing)throw Object.assign(Error('Migration needed'),{code:'migration_required',status:503});if(path.endsWith('reposhelf_account_data_ready'))return true;if(path.endsWith('reposhelf_account_deletion_status'))return {allowed,reason:'Assign another administrator'};if(path.endsWith('reposhelf_export_account'))return {account:{id:'member-id'},likes:[],viewingHistory:[]};return null}};
async function call(handler,url,{method='GET',body,requestOrigin=origin}={}){const req=Readable.from([]);Object.assign(req,{url,method,body,headers:{origin:requestOrigin}});const res={headers:{},setHeader(k,v){this.headers[k]=v},writeHead(status,h={}){this.status=status;Object.assign(this.headers,h)},end(body){this.data=body?JSON.parse(body):null}};await handler(req,res);return res}
const auth=createAuthHandler(accounts),open=createOpenHandler({accounts});
let r=await call(auth,'/api/auth?action=data-state');assert(r.data.ready);missing=true;assert.equal((await call(auth,'/api/auth?action=data-state')).data.ready,false);missing=false;
r=await call(auth,'/api/auth?action=export-account');assert.equal(r.data.account.id,'member-id');assert.equal(calls.at(-1).options.token,'member');assert.equal(r.headers['Cache-Control'],'private, no-store');assert(!JSON.stringify(r).includes('private-secret'));signedIn=false;assert.equal((await call(auth,'/api/auth?action=export-account')).status,401);
assert.equal((await call(open,'/api/open?url='+encodeURIComponent('https://github.com/team/app'))).headers.Location,'https://github.com/team/app');assert.match((await call(open,'/api/open?url='+encodeURIComponent('https://github.com/team/app/fork'))).headers.Location,/action=start/);assert.equal((await call(open,'/api/open?url=javascript:alert(1)')).status,400);
signedIn=true;assert.equal((await call(auth,'/api/auth?action=delete-account',{method:'DELETE',body:{confirm:'DELETE'},requestOrigin:'https://evil.test'})).status,403);assert.equal((await call(auth,'/api/auth?action=delete-account',{method:'DELETE',body:{confirm:'yes'}})).status,400);fresh=false;assert.equal((await call(auth,'/api/auth?action=delete-account',{method:'DELETE',body:{confirm:'DELETE'}})).data.error.code,'recent_sign_in_required');fresh=true;allowed=false;assert.equal((await call(auth,'/api/auth?action=delete-account',{method:'DELETE',body:{confirm:'DELETE'}})).status,409);assert(!calls.some(c=>c.options.method==='DELETE'));allowed=true;r=await call(auth,'/api/auth?action=delete-account',{method:'DELETE',body:{confirm:'DELETE',userId:'other'}});assert(r.data.deleted&&cleared);assert.equal(calls.at(-1).path,'/auth/v1/admin/users/member-id');assert(calls.at(-1).options.service);assert.equal(calls.at(-1).options.body.should_soft_delete,false);
const success={status:'completed',conclusion:'success',updated_at:at};assert.equal(syncAlerts([success],now).length,0);assert(syncAlerts([{...success,updated_at:new Date(now-7*3600000).toISOString()}],now).some(a=>a.id==='sync-overdue'));assert(syncAlerts([{...success,conclusion:'failure'},{...success,conclusion:'failure'},success],now).some(a=>a.id==='repeated-sync-failure'));assert(!syncAlerts([{...success,conclusion:'cancelled'},success],now).some(a=>a.id==='repeated-sync-failure'));
assert.equal(enrichmentAlerts([{phase:'complete',recordedAt:at,stages:[{id:'previews',name:'Preview screenshots',status:'failure'}]},{phase:'complete',recordedAt:new Date(now-3600000).toISOString(),stages:[{id:'previews',status:'failure'}]}],now)[0].id,'stage-previews');
const session={enabled:true,launchAnalyticsEnabled:true,user:null},browse={catalogVersion:'v1',indexed:2,items:[],snapshots:{catalog:at}};assert.deepEqual(storefrontAlerts(session,browse,now),[]);assert(storefrontAlerts(session,{...browse,snapshots:{catalog:'invalid'}},now).some(a=>a.id==='catalogue-stale'));
// Monitor alerts are deduplicated; recovery closes the bot issue, without comments.
let issues=[],history=[{...success,conclusion:'failure'},{...success,conclusion:'failure'},success],writes=0;
const fetcher=async(url,opts={})=>{if(url.includes('/actions/workflows/'))return Response.json({workflow_runs:history});if(url.includes('api.github.com')&&url.includes('/issues')){if(!opts.method)return Response.json(issues.filter(i=>i.state!=='closed'));writes++;const body=JSON.parse(opts.body);if(opts.method==='POST')issues=[{number:1,user:{login:'github-actions[bot]'},...body}];else issues[0]={...issues[0],...body};return Response.json(issues[0])}if(url.endsWith('/api/auth'))return Response.json(session);if(url.includes('action=browse'))return Response.json(browse);throw Error('Unexpected path')};
await monitor({fetcher,now,token:'fixture'});assert.equal(writes,1);await monitor({fetcher,now,token:'fixture'});assert.equal(writes,1);history=[success];await monitor({fetcher,now,token:'fixture'});assert.equal(writes,2);assert.equal(issues[0].state,'closed');
console.log('PASS: useful catalogue suggestions, release sorting, guest source access, protected fork actions, private exports, deletion origin/confirmation/reauth safeguards and operational alert deduplication/recovery.');
