import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {recordDemoResult,demoCandidates,applyDemoReports,publicIP,publicUrlGuard,inspectDemo,DEMO_RETRY_INTERVAL,DEMO_CONFIRM_INTERVAL} from '../scripts/demo-health.mjs';
import {extractProjectInsights} from '../scripts/project-insights.mjs';
import {generateAIOverview,validateAIOverview,aiFingerprint} from '../scripts/ai-overviews.mjs';
const Q=createRequire(import.meta.url)('../dist/quality.js');
const now=Date.parse('2026-10-03T12:00:00Z'),base={full:'owner/app',name:'App',demo:'https://demo.example.org',availability:'available'};
let r=recordDemoResult(base,{kind:'working'},now);
assert(Q.hasLiveDemo(r));assert.equal(Q.demoLabel(r),'Demo checked');
const good=r.demoHealth.checkedAt;
r=recordDemoResult(r,{kind:'temporary',reason:'rate_limit'},now+1000);
assert.equal(r.demoHealth.checkedAt,good);assert.equal(r.demoHealth.status,'working');assert(Q.hasLiveDemo(r));
r=recordDemoResult(r,{kind:'unavailable',reason:'http_404'},now+DEMO_RETRY_INTERVAL);
assert.equal(r.demoHealth.status,'review');assert(Q.hasLiveDemo(r));
r=recordDemoResult(r,{kind:'unavailable',reason:'http_404'},now+DEMO_RETRY_INTERVAL+1000);
assert.equal(r.demoHealth.failureCount,1,'Same-run screenshot failures cannot count twice');
r=recordDemoResult(r,{kind:'unavailable',reason:'http_410'},now+DEMO_RETRY_INTERVAL+DEMO_CONFIRM_INTERVAL+1000);
assert.equal(r.demoHealth.status,'unavailable');assert(!Q.hasLiveDemo(r));
const unavailable=r.demoHealth.checkedAt;
r=recordDemoResult(r,{kind:'temporary'},now+DEMO_CONFIRM_INTERVAL+3*DEMO_RETRY_INTERVAL);
assert.equal(r.demoHealth.checkedAt,unavailable);assert(!Q.hasLiveDemo(r));
assert(Q.hasLiveDemo({...r,demo:'https://new.example.org'}),'Changed demo URL ignores old health');
r=recordDemoResult(r,{kind:'working'},now+4*DEMO_RETRY_INTERVAL);
assert.equal(r.demoHealth.failureCount,0);assert(!r.demoHealth.error);assert(Q.hasLiveDemo(r));
assert.equal(demoCandidates([r],now+4*DEMO_RETRY_INTERVAL+1000).length,0);
applyDemoReports([r],[{number:3,title:'[Broken demo] App',body:`Project: \`${r.full}\`\nDemo: ${r.demo}`,created_at:new Date(now+5*DEMO_RETRY_INTERVAL).toISOString()}]);
assert(Q.hasLiveDemo(r),'Reports alone cannot hide demos');
assert.equal(demoCandidates([r],now+5*DEMO_RETRY_INTERVAL)[0],r);
assert.equal(demoCandidates([{...base,availability:'unavailable'}],now).length,0);
const unknown={...base,full:'unrelated/app'};applyDemoReports([unknown],[{number:4,title:'[Broken demo]',body:'Project: `unrelated/app`\nDemo: https://wrong.example.org',created_at:new Date(now).toISOString()}]);assert(!unknown.demoReport);
for(const ip of ['127.0.0.1','10.0.0.1','169.254.169.254','192.168.1.1','100.64.0.1','::1','fe80::1','::ffff:7f00:1'])assert(!publicIP(ip),ip);
assert(publicIP('8.8.8.8'));assert(publicIP('2606:4700:4700::1111'));
const guard=publicUrlGuard({resolver:async host=>host==='mixed.example'?[{address:'8.8.8.8'},{address:'10.0.0.1'}]:[{address:'8.8.8.8'}]});
assert(!await guard('http://mixed.example'));assert(!await guard('http://localhost'));assert(!await guard('file:///tmp/file'));assert(!await guard('https://user:pass@public.example'));assert(await guard('https://public.example'));
function page({status=200,title='Project',body='A working project with useful interactive content for visitors.',url='https://demo.example.org',canvas=0,throws=false}={}){return {goto:async()=>{if(throws)throw Error('timeout');return {status:()=>status}},waitForTimeout:async()=>{},title:async()=>title,url:()=>url,locator:selector=>({innerText:async()=>body,count:async()=>selector==='canvas'?canvas:1})}}
assert.equal((await inspectDemo(page({status:404}),base.demo)).kind,'unavailable');assert.equal((await inspectDemo(page({status:503}),base.demo)).kind,'temporary');assert.equal((await inspectDemo(page({status:429}),base.demo)).reason,'rate_limit');assert.equal((await inspectDemo(page({title:'Just a moment'}),base.demo)).kind,'temporary');assert.equal((await inspectDemo(page({body:''}),base.demo)).reason,'empty_page');assert.equal((await inspectDemo(page({body:'',canvas:1}),base.demo)).kind,'working');assert.equal((await inspectDemo(page({url:'https://huggingface.co/spaces/o/app'}),base.demo,{space:true})).kind,'temporary');assert.equal((await inspectDemo(page({url:'https://o-app.hf.space'}),base.demo,{space:true})).kind,'working');assert.equal((await inspectDemo(page({throws:true}),base.demo)).kind,'temporary');
const md='# Sketch\n\nSketch is designed for teams to share and organise their visual ideas.\n\n## Setup\n\nYou must provide an API key and enable paid billing for the AI service.\n\nAn optional API key enables AI suggestions.\n\nNo account is required to use the local editor.\n\nYou can self-host the application on your own server.\n\n```sh\nYou must configure an unrelated API key.\n```\n\n## Credits\n\nYou must create an account for the sponsor.\n';
const insight=extractProjectInsights(md,'https://github.com/o/r/blob/main/README.md');
assert.equal(insight.audience.length,1);assert(insight.whatItDoes.text.includes('Sketch'));assert(insight.requirements.some(x=>x.kind==='paid_service'&&x.status==='required'));assert(insight.requirements.some(x=>x.kind==='api_key'&&x.status==='optional'));assert(insight.requirements.some(x=>x.kind==='account'&&x.status==='not_required'));assert(insight.requirements.some(x=>x.kind==='hosting'));assert(!insight.requirements.some(x=>/unrelated|sponsor/.test(x.text)));assert.equal(extractProjectInsights('# Payments\n\nA dashboard managing paid subscriptions and user accounts.','source').requirements.length,0);
assert.equal(Q.licenseInfo({license:'mit'}).id,'MIT');assert.equal(Q.licenseInfo({license:'agpl-3.0'}).title,'Network copyleft licence');assert.equal(Q.licenseInfo({license:null}).title,'No licence detected');assert.equal(Q.licenseInfo({license:'Custom'}).url,null);assert.equal(Q.licenseInfo({license:'CC-BY-NC-4.0'}).title,'Non-commercial terms');
const project={name:'Sketch',description:'Sketch helps teams share and organise their visual ideas.',overview:{sourceUrl:'https://github.com/o/r/blob/main/README.md',paragraphs:['An interactive canvas for planning projects with colleagues.']}};
const summary={paragraphs:[{text:'Sketch offers an interactive canvas to help teams organise ideas and plan their projects together.',evidenceQuotes:['Sketch helps teams share and organise their visual ideas.']}]};
assert.throws(()=>validateAIOverview({paragraphs:[{text:summary.paragraphs[0].text,evidenceQuotes:['Invented unsupported source claim.']}]},project.description));
let requests=0;const generated=await generateAIOverview(project,{key:'test-secret',model:'test-model',now,fetcher:async(url,opts)=>{requests++;assert.equal(url,'https://generativelanguage.googleapis.com/v1beta/models/test-model:generateContent');assert.equal(opts.headers['x-goog-api-key'],'test-secret');assert(!url.includes('test-secret'));return {ok:true,json:async()=>({candidates:[{content:{parts:[{text:JSON.stringify(summary)}]}}]})}}});
assert.equal(requests,1);assert.equal(generated.provider,'Gemini');assert.equal(generated.fingerprint,aiFingerprint(project,'test-model'));assert.notEqual(aiFingerprint({...project,description:'Changed author text'},'test-model'),generated.fingerprint);await assert.rejects(()=>generateAIOverview(project,{key:'test-secret',model:'../invalid'}));
console.log('PASS: demo recovery, delayed confirmation, temporary retention, report safety, public-network guards, page classification, author-evidence requirements, licence guidance and grounded optional AI summaries.');

let readyWaits=0;const delayed={...page({body:''}),waitForFunction:async(fn,arg,options)=>{readyWaits++;assert.equal(options.timeout,8000)}};assert.equal((await inspectDemo(delayed,base.demo)).kind,'working');assert.equal(readyWaits,1);assert.equal((await inspectDemo({...delayed,waitForFunction:async()=>{throw Error('Still blank')}},base.demo)).reason,'empty_page');
