import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {verifySpaceSource,checkSpace,explicitGithub,listCandidates,importListCandidate} from '../scripts/source-imports.mjs';const require=createRequire(import.meta.url),P=require('../dist/providers.js');
const data={id:'org/space',private:false,likes:42,runtime:{stage:'RUNNING'},cardData:{title:'My Space',sdk:'gradio'}};const space=P.normalizeSpace(data);assert.equal(space.full,'hf:org/space');assert.equal(space.demo,'https://huggingface.co/spaces/org/space');assert.equal(P.action(space).url,'https://huggingface.co/spaces/org/space?duplicate=true');assert.equal(P.githubFull(space),null);assert.equal(P.normalizeSpace({...data,runtime:{stage:'BUILD_ERROR'}},space).demo,null);assert.equal(P.normalizeSpace({...data,private:true},space).availability,'unavailable');assert.equal(P.normalizeSpace({...data,gated:true},space).demo,null);assert.throws(()=>P.normalizeSpace({...data,id:'org/space/evil'}));
for(const code of [503,429,403]){const result=await checkSpace(space,{fetcher:async()=>new Response('{}',{status:code})});assert.equal(result.entry.demo,space.demo);assert.equal(result.entry.lastCheckedAt,space.lastCheckedAt);assert.equal(result.entry.availability,'available');assert(result.entry.nextCheckAt);assert.equal(result.stop,code!==503)}
const gone=await checkSpace(space,{fetcher:async()=>new Response('{}',{status:404})});assert.equal(gone.entry.availability,'unavailable');const restored=await checkSpace(gone.entry,{fetcher:async()=>Response.json(data)});assert.equal(restored.entry.availability,'available');assert.equal(restored.entry.unavailableSince,undefined);
assert.equal(explicitGithub('[React](https://github.com/facebook/react)'),null);assert.equal(explicitGithub('[Source code](https://github.com/org/app)'),'org/app');assert.equal(explicitGithub('',{source_repo:'https://github.com/org/app/tree/main'}),null);
assert.deepEqual(listCandidates('[App](https://github.com/org/app) [Docs](https://github.com/org/app/issues) [List](https://github.com/org/awesome-apps)','org/list'),['org/app']);
const merged=P.mergeCatalog([{full:'org/app',name:'App',demo:null}], [{...space,githubFull:'org/app'}]);assert.equal(merged.length,1);assert.equal(merged[0].demo,space.demo);assert.equal(merged[0].spaces.length,1);assert(P.matchesSource(merged[0],'huggingface'));assert(P.action(merged[0]).url.endsWith('/org/app/fork'));assert.equal(P.mergeCatalog([{full:'org/space'}],[space]).length,2,'Namespaced identities must not collide');
assert.equal(P.popular([{...space,likes:1},{...space,full:'hf:org/b',likes:5}])[0].likes,5);assert.equal(P.popular([{full:'org/a',stars:100,forks:10},{full:'org/b',stars:10,forks:1}])[0].full,'org/a');
const provenance={name:'Awesome list',url:'https://github.com/org/list'};const metadata={full_name:'org/app',name:'App',private:false,default_branch:'main',stargazers_count:3,forks_count:1};let markdown='[Demo](https://app.pages.dev)';const fetcher=async url=>url.startsWith('https://api.github.com')?Response.json(metadata):new Response(markdown);const imported=await importListCandidate('org/app',provenance,null,{fetcher});assert.equal(imported.demo,'https://app.pages.dev/');assert.equal(imported.discoveredVia[0].name,'Awesome list');markdown='[Dependency](https://react.dev)';assert.equal(await importListCandidate('org/app',provenance,null,{fetcher}),null,'Curated links alone cannot confirm demos');
console.log('PASS: source identities, Space actions and availability, private/gated/runtime handling, deduplication, provenance, and independently checked curated demos.');

const linked={...space,githubFull:'org/app'};let seen=[];const sourceFetcher=async(url,opts)=>{seen.push({url,headers:opts?.headers});return url.includes('huggingface.co')?new Response('[Source code](https://github.com/org/app)'):new Response('{}',{status:404})};const checkedLink=await verifySpaceSource(linked,data,{fetcher:sourceFetcher,headers:{Authorization:'Bearer test-secret'}});assert.equal(checkedLink.githubFull,undefined);assert.equal(seen[0].headers,undefined,'GitHub tokens must never be sent to Hugging Face');assert.equal(seen[1].headers.Authorization,'Bearer test-secret');const temporaryLink=await verifySpaceSource(linked,data,{fetcher:async()=>new Response('{}',{status:503})});assert.equal(temporaryLink.githubFull,'org/app');assert.equal(P.action(linked).label,'Duplicate on Hugging Face','Standalone Spaces keep a native duplicate action even with a GitHub source');
