const assert=require('node:assert/strict'),S=require('../dist/storefront.js');
const now=Date.parse('2026-10-03T12:00:00Z');
assert.deepEqual(S.technologies({topics:['react','threejs'],language:'TypeScript'}),['React','Three.js']);assert.deepEqual(S.technologies({topics:[]},{dependencies:{next:'1',react:'1'},devDependencies:{three:'1'}}),['React','Next.js','Three.js']);assert(!S.technologies({},{engines:{node:'22'}}).includes('Node.js'),'Node build tooling must not be called a Node app');
assert(S.popularity({stars:100,forks:10})>S.popularity({stars:10,forks:1}));assert.equal(S.popularity({stars:100,forks:10,watchers:100000}),S.popularity({stars:100,forks:10}));
assert.equal(S.trend({stars:100,forks:20},now),null);assert.equal(S.trend({stars:100,forks:20,metrics:[{at:new Date(now).toISOString(),stars:90,forks:10}]},now),null);const growing={stars:150,forks:25,metrics:[{at:new Date(now-7*86400000).toISOString(),stars:100,forks:20}]};assert.equal(S.trend(growing,now).stars,50);assert.equal(S.trend(growing,now).forks,5);assert.equal(S.trend(growing,now).days,7);assert.equal(S.sorted([growing,{stars:90000,forks:9000}],'trending',now).length,1);
let sampled=S.recordMetrics({stars:10,forks:1},now);sampled=S.recordMetrics({...sampled,stars:11},now+1000);assert.equal(sampled.metrics.length,1);assert.equal(sampled.metrics[0].stars,11);sampled=S.recordMetrics(sampled,now+86400000);assert.equal(sampled.metrics.length,2);
assert(S.recentRelease({latestRelease:{publishedAt:new Date(now-2*86400000).toISOString()}},now));assert(!S.recentRelease({created:new Date(now).toISOString(),updated:new Date(now).toISOString()},now));assert(!S.recentRelease({latestRelease:{publishedAt:new Date(now-60*86400000).toISOString()}},now));
assert.equal(S.images({screenshots:[{src:'javascript:alert(1)'},{src:'previews/../../secret.jpg'},{src:'previews/aaaaaaaaaaaaaaaaaaaaaaaa.jpg',kind:'demo'}]}).length,1);assert.equal(S.readmeImages('![Screenshot](images/app.png)',{full:'a/b',branch:'main'})[0].src,'https://raw.githubusercontent.com/a/b/main/images/app.png');assert.equal(S.readmeImages('![Logo](https://site.com/logo.png)',{full:'a/b'}).length,0);
console.log('PASS: technology evidence, popularity without watchers, genuine historical trends, daily samples, actual release dates, and safe screenshot sources.');
