import assert from 'node:assert/strict';import {Readable} from 'node:stream';
import {repositoryName,publicRepository} from '../lib/submissions.mjs';import {createSubmissionsHandler} from '../api/submissions.mjs';import {scanSubmissions} from '../scripts/submission-imports.mjs';
assert.equal(repositoryName(' https://github.com/Owner/project.git/ '),'Owner/project');for(const input of ['https://evil.test/a/b','https://github.com/a/b/blob/main','https://github.com/a/b?q=x','https://user:secret@github.com/a/b','http://github.com/a/b','a/..','a','//github.com/a/b'])assert.throws(()=>repositoryName(input));
assert.deepEqual(await publicRepository('owner/project',{fetcher:async()=>Response.json({private:false,id:42,full_name:'Owner/project'})}),{name:'Owner/project',id:'42'});await assert.rejects(()=>publicRepository('a/b',{fetcher:async()=>Response.json({private:true,id:42,full_name:'a/b'})}),e=>e.code==='public_repository_required');await assert.rejects(()=>publicRepository('a/b',{fetcher:async()=>new Response(null,{status:429})}),e=>e.status===429);await assert.rejects(()=>publicRepository('a/b',{fetcher:async()=>new Response(null,{status:301,headers:{location:'https://evil.test/repos/a/b'}})}),e=>e.status===503);
let signedIn=true,githubId='42',calls=[],queued=true,dispatch=0,waiting=[],queueError=null;const key='a'.repeat(32),person={id:'00000000-0000-0000-0000-000000000001',token:'private-token',githubId:'42'},accounts={config:{origin:'https://reposhelf.test'},legal:{active:false},origin(req){if(req.headers.origin!==this.config.origin)throw Object.assign(Error('Origin'),{status:403})},async user(){if(!signedIn)throw Object.assign(Error('Sign in'),{status:401});return {...person,githubId}},async request(path,options){calls.push({path,options});if(path.includes('submit_repository'))return {item:{id:'00000000-0000-0000-0000-000000000099',repo_name:'Owner/project',status:'queued'},queued};if(path.includes('submission_capabilities'))return {version:2,cancel:true};if(path.includes('cancel_submission'))return {id:options.body.submission,status:'cancelled',lease:'secret'};if(path.includes('claim_submissions'))return [];if(path.includes('repository_submissions?select=id&limit=1&or=')){if(queueError)throw queueError;return waiting}if(path.includes('finish_submission'))return true;return [{id:'mine',status:'queued',lease:'private-claim',lease_until:'private-time'}]}};
const fetcher=async(url,options)=>{if(url.includes('/dispatches')){dispatch++;assert.equal(options.headers.Authorization,'Bearer server-only');assert.equal(JSON.parse(options.body).inputs.submission_id,'00000000-0000-0000-0000-000000000099');return new Response(null,{status:204})}return Response.json({private:false,id:42,full_name:'Owner/project'})};const handler=createSubmissionsHandler({accounts,key,workflowToken:'server-only',fetcher,checkpoint:{json:async()=>null},now:()=>Date.parse('2026-10-08T10:00:00Z')});
async function call(url='/api/submissions',{method='GET',body,origin=accounts.config.origin,authorization}={}){const req=Readable.from(body?[JSON.stringify(body)]:[]);req.method=method;req.url=url;req.headers={origin,...authorization?{authorization}:{}};let result;const res={writeHead(status,headers){result={status,headers}},end(body){if(body)result.data=JSON.parse(body)}};await handler(req,res);return result}
signedIn=false;assert.equal((await call()).status,401);signedIn=true;githubId=null;assert.equal((await call()).status,403);githubId='42';assert.equal((await call(undefined,{method:'POST',body:{repository:'a/b'},origin:'https://evil.test'})).status,403);
let r=await call(undefined,{method:'POST',body:{repository:'owner/project',submitter:'spoofed'}});assert.equal(r.status,202);assert.equal(r.data.scanRequested,true);assert.equal(calls.at(-1).options.body.submitter,person.id);assert.equal(calls.at(-1).options.service,true);queued=false;await call(undefined,{method:'POST',body:{repository:'owner/project'}});assert.equal(dispatch,1,'Duplicates must not dispatch another run');r=await call();assert.equal(r.data.workerConfigured,true);const listCall=calls.findLast(c=>c.path.includes('repository_submissions?select=*'));assert(listCall.path.includes(person.id));assert.equal(listCall.options.token,person.token);assert.equal(r.data.items[0].lease,undefined);assert.equal(r.data.items[0].lease_until,undefined);assert.equal(r.data.canCancel,true);assert.equal(r.data.publication.nextScheduledAt,'2026-10-09T06:35:00.000Z');
assert.equal((await call('/api/submissions?action=pending',{method:'POST',body:{}})).status,401);assert.equal((await call('/api/submissions?action=pending',{method:'POST',body:{},authorization:'Bearer wrong'+key})).status,401);
r=await call('/api/submissions?action=pending',{method:'POST',body:{},authorization:'Bearer '+key});assert.deepEqual(r.data,{pending:false},'An empty queue must report nothing waiting');assert.equal(calls.at(-1).options.service,true);{const q=decodeURIComponent(calls.at(-1).path);assert(q.includes('status.in.(queued,retry)')&&q.includes('next_attempt_at.lte.')&&q.includes('status.eq.processing')&&q.includes('lease_until.lt.'),'The check must cover due, retry and expired-lease submissions');assert(!calls.some(c=>c.path.includes('claim_submissions')),'Checking must never claim a submission')}
waiting=[{id:'due'}];r=await call('/api/submissions?action=pending',{method:'POST',body:{},authorization:'Bearer '+key});assert.deepEqual(r.data,{pending:true});
queueError=Object.assign(new Error('A database update is required.'),{status:503,code:'migration_required'});r=await call('/api/submissions?action=pending',{method:'POST',body:{},authorization:'Bearer '+key});assert.equal(r.status,503,'A missing database update must be reported, not hidden');queueError=null;waiting=[];
assert.equal((await call('/api/submissions?action=claim',{method:'POST',body:{}})).status,401);r=await call('/api/submissions?action=claim',{method:'POST',body:{},authorization:'Bearer '+key});assert.equal(r.status,200);assert.equal(calls.at(-1).options.service,true);r=await call('/api/submissions?action=complete',{method:'POST',body:{id:'00000000-0000-0000-0000-000000000099',lease:'y',status:'imported',canonical:'Owner/project',withDemo:true,commit:'b'.repeat(40)},authorization:'Bearer '+key});assert.equal(r.status,200);assert.equal(calls.at(-1).options.body.published_commit,'b'.repeat(40));
const noDispatch=createSubmissionsHandler({accounts,key,workflowToken:'server-only',fetcher:async(url,opts)=>{if(opts.method==='POST')throw Error('Dispatch failed');return fetcher(url,opts)}});queued=true;const req=Readable.from([JSON.stringify({repository:'owner/project'})]);req.url='/api/submissions';req.method='POST';req.headers={origin:accounts.config.origin};let status,body;await noDispatch(req,{writeHead(s){status=s},end(b){body=JSON.parse(b)}});assert.equal(status,202);assert.equal(body.scanRequested,false,'Dispatch failure must preserve the queue');
const original={repositories:[{full:'a/old',demo:'https://old.test',name:'Old'},{full:'x/fail',demo:'https://kept.test'}]},items=['a/old','a/plain','x/fail','x/gone'].map((name,i)=>({id:String(i),lease:'claim',repo_name:name,user_id:'never-publish-this'}));const scan=await scanSubmissions(items,original,{importer:async(name,provenance,prior,opts)=>{assert.equal(opts.requireDemo,true);assert.equal(provenance.kind,'submission');if(name==='x/fail')throw Object.assign(Error('rate limit'),{status:429});if(name==='x/gone')throw Object.assign(Error('not found'),{status:404});return {full:name==='a/old'?'a/renamed':name,demo:name==='a/old'?'https://demo.test':null}}});assert.deepEqual(scan.results.map(r=>r.status),['imported','unavailable','retry','unavailable']);assert.equal(scan.catalog.repositories.find(r=>r.full==='x/fail').demo,'https://kept.test');assert(!scan.catalog.repositories.some(r=>r.full==='a/old'));assert(!JSON.stringify(scan.catalog).includes('never-publish-this'));assert(!scan.catalog.repositories.some(r=>r.full==='a/plain')); assert.equal(original.repositories.length,2);
console.log('PASS: public GitHub validation, verified sign-in/origin/private history, server-owned enqueue, duplicate and failed dispatch handling, worker authorization, retained transient entries and public-only import receipts.');

assert.equal((await call('/api/submissions?action=cancel',{method:'POST',origin:'https://evil.test',body:{id:'00000000-0000-0000-0000-000000000099'}})).status,403);assert.equal((await call('/api/submissions?action=cancel',{method:'POST',body:{id:'bad'}})).status,400);r=await call('/api/submissions?action=cancel',{method:'POST',body:{id:'00000000-0000-0000-0000-000000000099',user_id:'spoofed'}});assert.equal(r.status,200);assert.equal(r.data.item.lease,undefined);assert.equal(calls.at(-1).options.token,person.token);assert.deepEqual(calls.at(-1).options.body,{submission:'00000000-0000-0000-0000-000000000099'});r=await call('/api/submissions?action=claim',{method:'POST',authorization:'Bearer '+key,body:{id:'00000000-0000-0000-0000-000000000099',requireVersion:2}});assert.equal(r.status,200);assert(calls.at(-1).path.endsWith('claim_submissions_v2'));assert.equal(calls.at(-1).options.body.submission,'00000000-0000-0000-0000-000000000099');
console.log('PASS: selected-repository dispatch, owner-authenticated cancellation, origin/input checks, private lease redaction, targeted claims and next publication date.');
