import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {pathToFileURL} from 'node:url';import {createSyncLogHandler} from '../api/sync-log.mjs';import {createOpenHandler} from '../api/open.mjs';import {run,measure,summarizeStages} from '../scripts/sync-history.mjs';
assert.deepEqual(measure({a:'old',b:'same',d:'gone'},{a:'new',b:'same',c:'new'}),{before:3,after:3,added:1,updated:1,removed:1});assert.equal(summarizeStages({catalog:{outcome:'success'}},{catalog:'Revalidation: 3 checked, 2 unavailable, 1 temporary failures.\nCatalog: 10 saved records; 8 checked, 3 found/refreshed, 2 temporary failures.'})[0].temporaryFailures,3);
const directory=await mkdtemp(tmpdir()+'/reposhelf-sync-'),root=pathToFileURL(directory+'/');try{await mkdir(new URL('dist/',root));await writeFile(new URL('dist/catalog.json',root),JSON.stringify({repositories:[{full:'team/old',name:'Old'}]}));await writeFile(new URL('dist/spaces.json',root),'{"repositories":[]}');await run('start',root);await writeFile(new URL('dist/catalog.json',root),JSON.stringify({repositories:[{full:'team/old',name:'Old',stars:2},{full:'team/new',name:'New'}]}));await run('finish',root,{GITHUB_RUN_ID:'123',GITHUB_RUN_ATTEMPT:'1',GITHUB_EVENT_NAME:'schedule',SYNC_STEP_RESULTS:JSON.stringify({catalog:{outcome:'failure'},health:{outcome:'skipped'}})});const report=JSON.parse(await readFile(new URL('data/sync-runs/123.json',root),'utf8'));assert.equal(report.status,'failure');assert.equal(report.counts.added,1);assert.equal(report.counts.updated,1);assert.equal(report.stages[1].status,'skipped')}finally{await rm(directory,{recursive:true,force:true})}
let admin=true,authenticated=true,githubOk=true;const accounts={config:{origin:'https://reposhelf.test'},async admin(){if(!admin)throw Object.assign(Error('Forbidden'),{status:403});return {}},async user(){if(!authenticated)throw Object.assign(Error('Sign in'),{status:401});return {githubId:'42'}}};
const saved=[{id:'123',attempt:1,startedAt:'2026-10-03T00:00:00Z',status:'success',counts:{added:5},stages:[],temporaryFailures:0}];const log=createSyncLogHandler({accounts,saved:async()=>saved,fetcher:async()=>{if(!githubOk)throw Error('timeout');return Response.json({total_count:21,workflow_runs:[{id:123,run_attempt:1,status:'completed',conclusion:'failure',created_at:saved[0].startedAt,updated_at:'2026-10-03T00:10:00Z',event:'schedule'}]})}});
async function call(handler,url){const req={method:'GET',url};const res={writeHead(status,headers){this.status=status;this.headers=headers},end(body){this.body=body}};await handler(req,res);if(res.body)res.data=JSON.parse(res.body);return res}
let response=await call(log,'/api/sync-log');assert.equal(response.data.runs[0].counts.added,5);assert.equal(response.data.runs[0].status,'failure','Live terminal failure overrides pre-publish report');assert(response.data.hasMore);githubOk=false;response=await call(log,'/api/sync-log');assert.equal(response.data.runs.length,1);assert(response.data.notice);admin=false;assert.equal((await call(log,'/api/sync-log')).status,403);admin=true;assert.equal((await call(log,'/api/sync-log?page=-1')).status,400);
const open=createOpenHandler({accounts});authenticated=false;response=await call(open,'/api/open?url=https%3A%2F%2Fdemo.example');assert.equal(response.status,302);assert.equal(response.headers.Location,'/api/auth?action=start');authenticated=true;response=await call(open,'/api/open?url=https%3A%2F%2Fdemo.example');assert.equal(response.headers.Location,'https://demo.example/');assert.equal((await call(open,'/api/open?url=javascript%3Aalert(1)')).status,400);assert.equal((await call(open,'/api/open?url=https%3A%2F%2Fuser%3Apass%40example.com')).status,400);
console.log('PASS: exact record additions/updates, durable failed-stage reports, admin-only logs, live final status, retained reports during GitHub errors, and authenticated safe demo/repository redirects.');
