import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {pathToFileURL} from 'node:url';import {createSyncLogHandler} from '../api/sync-log.mjs';import {createOpenHandler} from '../api/open.mjs';import {run,measure,summarizeStages,demoCount} from '../scripts/sync-history.mjs';
assert.equal(demoCount([{demo:'https://demo.org'},{demo:'https://demo.org',availability:'unavailable'},{demo:'https://demo.org',demoHealth:{url:'https://demo.org',status:'unavailable'}},{full:'team/none'},{demo:null},{source:'huggingface',demo:'https://demo.hf.space'}]),2);
assert.deepEqual(measure({a:'old',b:'same',d:'gone'},{a:'new',b:'same',c:'new'}),{before:3,after:3,added:1,updated:1,removed:1});assert.equal(summarizeStages({catalog:{outcome:'success'}},{catalog:'Revalidation: 3 checked, 2 unavailable, 1 temporary failures.\nCatalog: 10 saved records; 8 checked, 3 found/refreshed, 2 temporary failures.'})[0].temporaryFailures,3);
const [health,previews]=summarizeStages({health:{outcome:'success'},previews:{outcome:'success'}},{health:'Demo progress: 10/100 checked; 3 inconclusive.\nDemo progress: 20/100 checked; 8 inconclusive.\nDemo checks: 100 checked, 55 pages loaded, 3 unavailable responses, 42 inconclusive. 0 deferred.',previews:'Preview progress: 1/20 checked, 0 captured.\nPreview progress: 20/20 checked, 13 captured.\nSaved 13 demo screenshots; 0 deferred.'});assert.equal(health.checked,100);assert.equal(health.inconclusiveChecks,42);assert.equal(health.unavailableResponses,3);assert.equal(previews.checked,20,'Cumulative progress messages must not inflate scan totals');
const directory=await mkdtemp(tmpdir()+'/reposhelf-sync-'),root=pathToFileURL(directory+'/');try{await mkdir(new URL('dist/',root));await writeFile(new URL('dist/catalog.json',root),JSON.stringify({repositories:[{full:'team/old',name:'Old'}]}));await writeFile(new URL('dist/spaces.json',root),'{"repositories":[]}');await run('start',root);await writeFile(new URL('dist/catalog.json',root),JSON.stringify({repositories:[{full:'team/old',name:'Old',stars:2,demo:'https://demo.org'},{full:'team/new',name:'New'}]}));await writeFile(new URL('dist/spaces.json',root),JSON.stringify({repositories:[{source:'huggingface',full:'hf:team/linked',spaceId:'team/linked',githubFull:'team/old',demo:'https://linked.hf.space'},{source:'huggingface',full:'hf:team/standalone',spaceId:'team/standalone',demo:'https://standalone.hf.space'},{source:'huggingface',full:'hf:team/unavailable',spaceId:'team/unavailable',demo:'https://unavailable.hf.space',availability:'unavailable'}]}));await run('finish',root,{GITHUB_RUN_ID:'123',GITHUB_RUN_ATTEMPT:'1',GITHUB_EVENT_NAME:'schedule',SYNC_STEP_RESULTS:JSON.stringify({catalog:{outcome:'failure'},health:{outcome:'skipped'}})});const report=JSON.parse(await readFile(new URL('data/sync-runs/123.json',root),'utf8'));assert.equal(report.status,'failure');assert.equal(report.counts.added,3);assert.equal(report.counts.updated,1);assert.equal(report.counts.withDemo,2);assert.equal(report.schema,4);assert.equal(report.stages[1].status,'skipped')}finally{await rm(directory,{recursive:true,force:true})}
let admin=true,authenticated=true,githubOk=true,githubId='42';const accounts={legal:{active:false},config:{origin:'https://reposhelf.test'},async admin(){if(!admin)throw Object.assign(Error('Forbidden'),{status:403});return {}},async user(){if(!authenticated)throw Object.assign(Error('Sign in'),{status:401});return {githubId}}};
const saved=[{id:'123',attempt:1,startedAt:'2026-10-03T00:00:00Z',status:'success',counts:{added:5,withDemo:12},stages:[],temporaryFailures:0}];const log=createSyncLogHandler({accounts,saved:async()=>saved,fetcher:async()=>{if(!githubOk)throw Error('timeout');return Response.json({total_count:21,workflow_runs:[{id:123,run_attempt:1,status:'completed',conclusion:'failure',created_at:saved[0].startedAt,updated_at:'2026-10-03T00:10:00Z',event:'schedule'}]})}});
async function call(handler,url){const req={method:'GET',url};const res={writeHead(status,headers){this.status=status;this.headers=headers},end(body){this.body=body}};await handler(req,res);if(res.body)res.data=JSON.parse(res.body);return res}
let response=await call(log,'/api/sync-log');assert.equal(response.data.runs[0].counts.added,5);assert.equal(response.data.runs[0].counts.withDemo,12);assert.equal(response.data.runs[0].status,'failure','Live terminal failure overrides pre-publish report');assert(response.data.hasMore);githubOk=false;response=await call(log,'/api/sync-log');assert.equal(response.data.runs.length,1);assert(response.data.notice);assert.equal(response.data.runs[0].counts.withDemo,12);delete saved[0].counts.withDemo;response=await call(log,'/api/sync-log');assert.equal(response.data.runs[0].counts.withDemo,undefined,'Legacy reports must not invent demo counts');admin=false;assert.equal((await call(log,'/api/sync-log')).status,403);admin=true;assert.equal((await call(log,'/api/sync-log?page=-1')).status,400);
const authRequests=[];const fallbackLog=createSyncLogHandler({checkpoint:{reports:async()=>[],json:async()=>null},accounts:{...accounts,admin:async()=>({githubToken:'expired-fixture-token'})},saved:async()=>saved,fetcher:async(url,options)=>{authRequests.push(options.headers);return options.headers.Authorization?new Response('',{status:401}):Response.json({workflow_runs:[],total_count:0})}});const fallback=await call(fallbackLog,'/api/sync-log');assert.equal(fallback.data.notice,null);assert.equal(authRequests.length,6);assert.equal(authRequests[1].Authorization,undefined,'Expired account tokens must not block public workflow status');
{const seen=[],fetcher=async(url,options)=>{if(/\/actions\//.test(url))seen.push(options.headers.Authorization||null);return Response.json({workflow_runs:[{id:777,run_attempt:1,status:'in_progress',conclusion:null,event:'workflow_dispatch',display_title:'Refresh demo catalog',run_started_at:'2026-10-06T20:53:56Z',created_at:'2026-10-06T20:53:56Z',updated_at:'2026-10-06T20:54:02Z'}],total_count:1})},googleAdmin=async()=>({githubToken:null}),build=serverToken=>createSyncLogHandler({checkpoint:{reports:async()=>[],json:async()=>null},accounts:{...accounts,admin:googleAdmin},saved:async()=>[],fetcher,progress:async()=>null,serverToken});const withServer=await call(build('server-fixture-token'),'/api/sync-log');assert.equal(withServer.data.runs[0].status,'in_progress','A running sync is listed for an administrator who signed in without GitHub');assert(seen.length>0&&seen.every(v=>v==='Bearer server-fixture-token'),'GitHub requests use the server token when the account has none');seen.length=0;await call(build(undefined),'/api/sync-log');assert(seen.length>0&&seen.every(v=>v===null),'No token is invented when none is configured')}
const open=createOpenHandler({accounts});authenticated=false;response=await call(open,'/api/open?url=https%3A%2F%2Fdemo.example');assert.equal(response.status,302);assert.equal(response.headers.Location,'https://demo.example/');response=await call(open,'/api/open?url='+encodeURIComponent('https://github.com/team/app/fork'));const login=new URL(response.headers.Location,accounts.config.origin);assert.equal(login.pathname,'/api/auth');assert.equal(login.searchParams.get('action'),'start');assert.equal(login.searchParams.get('return'),'/api/open?url='+encodeURIComponent('https://github.com/team/app/fork'));authenticated=true;response=await call(open,'/api/open?url=https%3A%2F%2Fdemo.example');assert.equal(response.headers.Location,'https://demo.example/');assert.equal(response.headers['Cache-Control'],'private, no-store');githubId=null;response=await call(open,'/api/open?url='+encodeURIComponent('https://github.com/team/app/fork'));assert.equal(response.status,302);assert.equal(response.headers.Location,'/api/auth?action=link-github&return='+encodeURIComponent('/api/open?url='+encodeURIComponent('https://github.com/team/app/fork')),'A signed-in user without GitHub is sent to connect it');githubId='42';assert.equal((await call(open,'/api/open?url=javascript%3Aalert(1)')).status,400);assert.equal((await call(open,'/api/open?url=https%3A%2F%2Fuser%3Apass%40example.com')).status,400);
const finished=[{id:'900',attempt:1,startedAt:'2026-10-05T16:47:43.077Z',recordedAt:'2026-10-05T16:52:35.037Z',phase:'complete',status:'success',counts:{added:1,withDemo:1},stages:[],temporaryFailures:0},{id:'901',attempt:1,startedAt:'2026-10-05T18:00:00.000Z',recordedAt:'2026-10-05T18:03:00.000Z',phase:'discovering',status:'success',counts:{added:1,withDemo:1},stages:[],temporaryFailures:0}];
const offline=createSyncLogHandler({accounts,saved:async()=>finished,fetcher:async()=>{throw Error('GitHub unreachable')}});const offlineRuns=(await call(offline,'/api/sync-log')).data.runs;assert.equal(offlineRuns.find(r=>r.id==='900').finishedAt,'2026-10-05T16:52:35.037Z','A complete saved report supplies the finish time when GitHub run history is unavailable');assert.equal(offlineRuns.find(r=>r.id==='901').finishedAt,null,'An unfinished saved report has no finish time');
console.log('PASS: exact record additions/updates, durable failed-stage reports, admin-only logs, live final status, retained reports during GitHub errors, and authenticated safe demo/repository redirects.');

const branchReport={...saved[0],id:'999',attempt:1,recordedAt:'2026-10-04T00:00:00Z',publication:'unchanged',counts:{added:0,updated:0,withDemo:12},stages:[]};
const branchLog=createSyncLogHandler({accounts,saved:async()=>[],checkpoint:{reports:async()=>[branchReport]},fetcher:async()=>Response.json({workflow_runs:[{id:999,run_attempt:1,status:'completed',conclusion:'success',created_at:'2026-10-04T00:00:00Z'}],total_count:1})});
const branchResult=await call(branchLog,'/api/sync-log');assert.equal(branchResult.data.runs[0].counts.withDemo,12);assert.equal(branchResult.data.runs[0].diagnostics.publication,'unchanged');
console.log('PASS: checkpoint reports appear in admin logs without deployment and distinguish unchanged publication.');

const configuredLog=createSyncLogHandler({accounts,saved:async()=>[],checkpoint:{reports:async()=>[],json:async()=>null},control:{configured:false},fetcher:async()=>Response.json({workflow_runs:[],total_count:0})});
assert.equal((await call(configuredLog,'/api/sync-log')).data.publication.controlConfigured,false);
console.log('PASS: admin sync logs expose configuration readiness without credentials.');

{const byFile={'catalog.yml':[{id:1,name:'Refresh demo catalog',run_attempt:1,status:'completed',conclusion:'success',event:'workflow_dispatch',display_title:'Refresh demo catalog',created_at:'2026-10-07T01:00:00Z',updated_at:'2026-10-07T01:30:00Z'}],'publication.yml':[{id:2,name:'Publish saved catalogue',run_attempt:1,status:'completed',conclusion:'success',event:'workflow_dispatch',display_title:'Publish saved catalogue',created_at:'2026-10-07T02:00:00Z',updated_at:'2026-10-07T02:05:00Z'}],'submissions.yml':[{id:3,name:'Scan submitted repositories',run_attempt:1,status:'completed',conclusion:'failure',event:'schedule',display_title:'Scan submitted repositories',created_at:'2026-10-07T03:00:00Z',updated_at:'2026-10-07T03:10:00Z'}]};
const all=createSyncLogHandler({checkpoint:{reports:async()=>[],json:async()=>null},accounts:{...accounts,admin:async()=>({githubToken:'fixture'})},saved:async()=>[],progress:async()=>null,fetcher:async url=>{const file=/workflows\/([^/]+)\/runs/.exec(url)?.[1];return file?Response.json({workflow_runs:byFile[file]||[],total_count:(byFile[file]||[]).length}):Response.json({})}});
const result=await call(all,'/api/sync-log');assert.deepEqual(result.data.runs.map(r=>r.id),['3','2','1'],'Publication and submission runs are listed with catalogue syncs');assert.equal(result.data.runs[1].workflow,'Publish saved catalogue');assert.equal(result.data.health.latestRunId,'1','A failed submission scan does not make the catalogue sync look failed');assert.equal(result.data.health.alerts.some(a=>a.id==='latest-failure'),false)}
{const seen=[],run={id:888,name:'Refresh demo catalog',run_attempt:1,status:'in_progress',conclusion:null,event:'push',display_title:'Refresh demo catalog',created_at:'2026-10-07T04:45:17Z',run_started_at:'2026-10-07T04:45:17Z',updated_at:'2026-10-07T05:00:00Z'};
const fetcher=async(url,options)=>{if(!/\/actions\//.test(url))return Response.json({});const auth=options.headers.Authorization||null;seen.push(auth);if(auth==='Bearer expired-user-token'||!auth)return new Response('',{status:auth?401:403});return Response.json({workflow_runs:/catalog\.yml/.test(url)?[run]:[],total_count:1})};
const build=serverToken=>createSyncLogHandler({checkpoint:{reports:async()=>[],json:async()=>null},accounts:{...accounts,admin:async()=>({githubToken:'expired-user-token'})},saved:async()=>[],fetcher,progress:async()=>null,serverToken});
const withServer=await call(build('server-fixture-token'),'/api/sync-log');assert.equal(withServer.data.runs[0].status,'in_progress','An expired account token falls back to the server token, so a running sync is listed');assert.equal(withServer.data.notice,null);
seen.length=0;const without=await call(build(undefined),'/api/sync-log');assert.match(without.data.notice,/HTTP 403/,'The notice names the GitHub status when run history cannot be read')}
{const run={id:889,name:'Refresh demo catalog',run_attempt:1,status:'completed',conclusion:'success',event:'schedule',display_title:'Refresh demo catalog',created_at:'2026-10-07T04:45:17Z',run_started_at:'2026-10-07T04:45:17Z',updated_at:'2026-10-07T05:25:00Z'};
// A private repository answers 404, not 401/403, to a token that cannot see it.
const fetcher=async(url,options)=>{if(!/\/actions\//.test(url))return Response.json({});const auth=options.headers.Authorization||null;if(auth!=='Bearer server-fixture-token')return new Response('',{status:404});return Response.json({workflow_runs:/catalog\.yml/.test(url)?[run]:[],total_count:1})};
const build=serverToken=>createSyncLogHandler({checkpoint:{reports:async()=>[],json:async()=>null},accounts:{...accounts,admin:async()=>({githubToken:'user-token-without-repo-access'})},saved:async()=>[],fetcher,progress:async()=>null,serverToken});
const withServer=await call(build('server-fixture-token'),'/api/sync-log');assert.equal(withServer.data.runs[0].status,'success','A 404 for the account token falls back to the server token, so run history still loads');assert.equal(withServer.data.notice,null);
const without=await call(build(undefined),'/api/sync-log');assert.match(without.data.notice,/HTTP 404.*REPOSHELF_ACTIONS_TOKEN/,'A 404 explains that the private repository needs the Actions token')}
console.log('PASS: a private repository 404 falls back to the server token and names the token to check.');
{// Record counts: a 404 for the first token must not stop the second, and a refusal of every token is explained.
const {createCheckpointStore}=await import('../lib/checkpoint-store.mjs');
const report={id:'900',attempt:1,phase:'complete',recordedAt:'2026-10-07T10:00:00Z',stages:[],counts:{added:1,updated:2,total:3}};
const seen=[];const fetcher=async(url,options)=>{const auth=options?.headers?.Authorization||null;seen.push(auth);if(/api\.github\.com/.test(url)&&auth==='Bearer server-token')return Response.json(/sync-checkpoint/.test(url)?{schema:1,reportIds:['900']}:report);return new Response('',{status:404})};
process.env.REPOSHELF_ACTIONS_TOKEN='server-token';
const store=createCheckpointStore({fetcher});
assert.deepEqual((await store.reports(['900'],'account-token')).map(r=>r.id),['900'],'the server token is tried after the account token gets a 404');
const meta=await store.json('.sync-checkpoint.json',1500,'account-token');assert.equal(meta.schema,1);assert.equal(store.access,'ok');
process.env.REPOSHELF_ACTIONS_TOKEN='token-without-contents-access';
const refused=createCheckpointStore({fetcher});assert.equal(await refused.json('.sync-checkpoint.json',1500,null),null);assert.equal(refused.access,'denied','every token refused is reported as denied, not as missing data');
const run={id:900,name:'Refresh demo catalog',run_attempt:1,status:'completed',conclusion:'success',event:'schedule',display_title:'Refresh demo catalog',created_at:'2026-10-07T04:45:17Z',run_started_at:'2026-10-07T04:45:17Z',updated_at:'2026-10-07T05:25:00Z'};
const live=async(url,options)=>{if(/\/actions\//.test(url))return Response.json({workflow_runs:/catalog\.yml/.test(url)?[run]:[],total_count:1});return fetcher(url,options)};
const handler=createSyncLogHandler({checkpoint:refused,accounts:{...accounts,admin:async()=>({githubToken:null})},saved:async()=>[],fetcher:live,progress:async()=>null,serverToken:'token-without-contents-access'});
const denied=await call(handler,'/api/sync-log');assert.match(denied.data.notice,/Record counts are unavailable.*Contents: Read-only/,'the log says why record counts are missing');
delete process.env.REPOSHELF_ACTIONS_TOKEN;
// The deployment card: compares the running site's commit with the newest commit on main when Vercel's status cannot be read.
const sha=c=>c.repeat(40),mk=(liveSha,headSha,minutes)=>createSyncLogHandler({checkpoint:{reports:async()=>[],json:async()=>null},accounts:{...accounts,admin:async()=>({githubToken:'t'})},saved:async()=>[],progress:async()=>null,liveSha,fetcher:async url=>{if(/\/actions\//.test(url))return Response.json({workflow_runs:/catalog\.yml/.test(url)?[run]:[],total_count:1});if(/commits\/main\/status/.test(url))return new Response('',{status:404});if(/commits\/main$/.test(url))return Response.json({sha:headSha,commit:{committer:{date:new Date(Date.now()-minutes*60000).toISOString()}}});return Response.json({})}});
assert.equal((await call(mk(sha('a'),sha('a'),3),'/api/sync-log')).data.deployment.state,'ready');
assert.equal((await call(mk(sha('a'),sha('b'),3),'/api/sync-log')).data.deployment.state,'pending');
assert.equal((await call(mk(sha('a'),sha('b'),90),'/api/sync-log')).data.deployment.state,'delayed');
assert.equal((await call(mk(undefined,sha('b'),3),'/api/sync-log')).data.deployment.state,'unknown');
}
console.log('PASS: record counts survive a token that cannot see the repository, a refusal is explained, and the website-update card works without Vercel\'s status API.');
