import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {pathToFileURL} from 'node:url';
import {probeMetrics,recordStageMetrics,readStageMetrics} from '../scripts/sync-metrics.mjs';
import {qualityPlan} from '../scripts/catalog-priority.mjs';
import {run} from '../scripts/sync-history.mjs';
import {shouldBuild} from '../scripts/deployment-policy.mjs';
import {diagnoseSync,deploymentStatus} from '../lib/sync-diagnostics.mjs';

assert.equal(shouldBuild('Save catalogue recovery checkpoint',['data/sync-runs/1.json','dist/catalog.json']),false);
assert.equal(shouldBuild('Sync progress [skip ci]',['data/sync-progress.json'],'reposhelf-progress'),false);
assert.equal(shouldBuild('Refresh public demo catalog',['dist/catalog.json']),true);
assert.equal(shouldBuild('Save catalogue recovery checkpoint',['data/browse/index.json','dist/admin.js']),true);
assert.equal(shouldBuild('Save catalogue recovery checkpoint',[]),true);
assert.equal(shouldBuild('Add feature',['dist/app.js'],'claude/some-feature','preview'),false,'preview deployments are skipped');
assert.equal(shouldBuild('Add feature',['dist/app.js'],'claude/some-feature'),false,'non-main branches are skipped even without VERCEL_ENV');
assert.equal(shouldBuild('Add feature',['dist/app.js'],'main','preview'),false,'a preview environment never builds');
assert.equal(shouldBuild('Add feature',['dist/app.js'],'main','production'),true,'production builds from main');
assert.equal(shouldBuild('Add feature',['dist/app.js'],null,null),true,'unknown metadata still builds rather than dropping an update');
const blocked=deploymentStatus({statuses:[{context:'Vercel',state:'failure',description:'Deployment rate limited — retry in 24 hours.',target_url:'https://vercel.com/sparx1981?upgradeToPro=build-rate-limit'}]});
assert.equal(blocked.state,'blocked');assert(blocked.description.includes('rate limited'));
assert.equal(deploymentStatus({statuses:[{context:'Vercel',state:'success',target_url:'javascript:alert(1)'}]}).url,'https://vercel.com/sparx1981/reposhelf');
assert.equal(deploymentStatus({statuses:[]}).state,'unknown');
const telemetry=probeMetrics({due:10,selected:4,limit:4});
telemetry.record('team/one',{kind:'working'},true);
telemetry.record('team/two',{kind:'temporary',reason:'probe_timeout'},false);
telemetry.record('team/three',{kind:'unavailable',reason:'http_404'},false);
telemetry.record('team/four',{kind:'working'},false);
const summary=telemetry.summary(1000,13000);
assert.equal(summary.attempted,4);assert.equal(summary.captured,1);
assert.equal(summary.temporaryFailures,1);assert.equal(summary.unavailable,1);
assert.equal(summary.remainingDue,6);assert.equal(summary.durationMs,12000);
assert.deepEqual(summary.reasons,{probe_timeout:1,http_404:1,no_screenshot:1});
const health=probeMetrics();health.record('team/good',{kind:'working'});assert.deepEqual(health.metrics.reasons,{});
for(let i=0;i<20;i++)health.record('team/'+i,{kind:'temporary',reason:'https://unsafe.example/?secret=x'});
assert.equal(health.metrics.examples.length,12);assert(!JSON.stringify(health.metrics).includes('secret'));
const project={full:'team/app',demo:'https://demo.org',availability:'available'};
const plan=qualityPlan([project]);assert.equal(plan.ready,true);assert.equal(plan.pending.screenshots,1);assert.equal(plan.targets.demoChecks,1);assert(plan.reasons.includes('Demo validation is below 95%.'));
const dir=await mkdtemp(tmpdir()+'/reposhelf-debug-'),root=pathToFileURL(dir+'/');
try{
 await mkdir(new URL('dist/',root));await writeFile(new URL('dist/catalog.json',root),JSON.stringify({repositories:[project]}));await writeFile(new URL('dist/spaces.json',root),'{"repositories":[]}');
 await run('start',root);await recordStageMetrics('priority',plan,root);await recordStageMetrics('browser_cycle',{due:false,reason:'Window already completed',nextDueAt:'2026-10-05T00:00:00Z'},root);
 await recordStageMetrics('previews',{...summary,complete:false},root);
 assert.equal((await readStageMetrics('previews',root)).captured,1);
 await run('finish',root,{GITHUB_RUN_ID:'456',SYNC_STEP_RESULTS:JSON.stringify({priority:{outcome:'success'},previews:{outcome:'failure'}})});
 const report=JSON.parse(await readFile(new URL('data/sync-runs/456.json',root),'utf8'));
 assert.equal(report.schema,4);assert.equal(report.work.discovery.ready,true);assert.equal(report.work.coverageAfter.pending.screenshots,1);
 const preview=report.stages.find(s=>s.id==='previews');assert.equal(preview.checked,4);assert.equal(preview.details.captured,1);assert.equal(preview.temporaryFailures,1);assert.equal(preview.details.complete,false);
 const success={status:'completed',conclusion:'success'};
 let diagnosis=diagnoseSync(success,undefined,{...report,stages:[]});
 assert.equal(diagnosis.kind,'no_changes');assert(!diagnosis.message.includes('New discovery was paused'));assert(diagnosis.message.includes('browser window already completed'));
 diagnosis=diagnoseSync(success,undefined,{...report,phase:'cleanup',stages:[]});assert.equal(diagnosis.kind,'checkpoint');
 diagnosis=diagnoseSync({status:'in_progress'},undefined,{...report,phase:'cleanup'});assert(diagnosis.message.includes('not the finished run'));
 assert.equal(await readStageMetrics('health',root),null);
}finally{await rm(dir,{recursive:true,force:true})}
console.log('PASS: durable sync work metrics, coverage gates, partial screenshot outcomes, bounded failure samples and honest zero-change/checkpoint explanations.');
