import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {pathToFileURL} from 'node:url';
import {reclassifyCatalog} from '../scripts/reclassify-catalog.mjs';
import {applyListingControls} from '../lib/listing-policy.mjs';
const require=createRequire(import.meta.url),T=require('../dist/taxonomy.js'),B=require('../dist/browse.js'),E=require('../dist/editorial.js');
const project={full:'team/sunlight',name:'Building sunlight simulator',description:'Building design and floor plans with a physics engine.',category:'Other',demo:'https://demo.example',lastCheckedAt:'2026-10-05T00:00:00Z'};
const classified=T.annotate(project);
assert(classified.subjects.includes('Architecture & building design'));
assert(classified.subjects.includes('Simulation & physics'));
assert.equal(classified.lastCheckedAt,project.lastCheckedAt);
assert.equal(T.annotate(classified),classified,'Current-version assignments need no repeated runtime classification');
assert(T.annotate({...classified,classification:{version:0},subjects:[]}).subjects.length>0,'Stale versions are backfilled');
assert(T.annotate({...project,full:'hf:team/sunlight',source:'huggingface'}).subjects.includes('Architecture & building design'));
assert.equal(T.annotate({...project,full:'hf:team/sunlight',source:'huggingface'}).category,'AI & machine learning');
const unrelated=T.annotate({name:'API recipes',description:'Software architecture and cryptography cookbook with a model simulator dependency.',readmeSnapshot:{searchTerms:['restaurant','blender']}});
assert(!unrelated.subjects.includes('Food & cooking'),'Code recipes are not food');
assert(!unrelated.subjects.includes('Architecture & building design'),'Software architecture is not building design');
assert(!unrelated.subjects.includes('Crypto & blockchain'),'Cryptography is not cryptocurrency');
assert(!unrelated.subjects.includes('Animation & motion'),'README-only dependencies are suggestions, not allocations');
assert(unrelated.classification.suggestedSubjects.includes('Food & cooking'));
const override=applyListingControls([classified],[{project_id:project.full,category:'Education',visibility:'visible'}])[0];
assert.equal(override.category,'Education');assert(override.subjects.includes('Simulation & physics'));
assert(T.matches(override,'Education'));assert(T.matches(override,'Simulation & physics'));
const result=B.select([classified],{category:'Simulation & physics',demos:false,limit:48});assert.equal(result.total,1);assert.equal(result.facets.categories['Architecture & building design'],1);
const duplicate=B.select([{...classified,category:'Simulation & physics'}],{demos:false});assert.equal(duplicate.facets.categories['Simulation & physics'],1,'Facet counts do not double-count the same category');
const existing=E.defaults().find(r=>r.builtin_key==='reposhelf');assert.equal(existing.id,'e0000000-0000-4000-8000-000000000014','Existing editorial IDs stay stable');
assert.equal(E.defaults().filter(r=>T.subjects.includes(r.category)).length,7);
const temp=await mkdtemp(tmpdir()+'/reposhelf-taxonomy-'),root=pathToFileURL(temp+'/');
try{await mkdir(new URL('dist/',root));await writeFile(new URL('dist/catalog.json',root),JSON.stringify({updatedAt:project.lastCheckedAt,repositories:[project]}));const first=await reclassifyCatalog(root),second=await reclassifyCatalog(root);assert.equal(first.checked,1);assert.equal(second.changed,0,'Repeated local passes are deterministic');const saved=JSON.parse(await readFile(new URL('dist/catalog.json',root)));assert.equal(saved.updatedAt,project.lastCheckedAt);assert.equal(saved.repositories[0].lastCheckedAt,project.lastCheckedAt);assert(saved.repositories[0].classification.version===T.version)}finally{await rm(root,{recursive:true,force:true})}
console.log('PASS versioned overlapping subjects, conservative evidence, Spaces, administrator overrides, facets, stable shelf IDs and idempotent backfill without artificial freshness.');
