import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import {importXCandidates, validatedXCandidate, mergeXProvenance} from '../scripts/x-imports.mjs';
import {applyListingControls} from '../lib/listing-policy.mjs';
import {compactProject} from '../lib/browse-index.mjs';
const require=createRequire(import.meta.url),T=require('../dist/taxonomy.js'),B=require('../dist/browse.js');
const at=Date.parse('2026-10-08T12:00:00Z'),date=new Date(at).toISOString(),full='team/app',demo='https://app.example.test';
const source={kind:'x',name:'As Seen On X.com',url:'https://x.com/i/web/status/123456'};
const src='previews/'+createHash('sha256').update(full).digest('hex').slice(0,24)+'.jpg';
const row={full,name:'App',category:'Productivity',availability:'available',demo,lastCheckedAt:date,demoHealth:{url:demo,status:'working',checkedAt:date},screenshots:[{src,kind:'demo',url:demo,capturedAt:date}],discoveredVia:[source]};
assert(validatedXCandidate(row,at));
assert(!validatedXCandidate({...row,lastCheckedAt:new Date(at-49*3600000).toISOString()},at));
assert(!validatedXCandidate({...row,lastCheckedAt:new Date(at+3600000).toISOString()},at));
assert(!validatedXCandidate({...row,screenshots:[{...row.screenshots[0],src:'previews/../../unsafe.jpg'}]},at));
assert(!validatedXCandidate({...row,discoveredVia:[{...source,url:'https://x.com.evil.test/user/status/123'}]},at));
assert(T.names(row).includes('As Seen On X.com'));
assert(T.names(row).includes('Productivity'));
assert(T.matches(row,'As Seen On X.com'));
assert(!T.matches({...row,discoveredVia:[]},'As Seen On X.com'));
assert(T.subjects.includes('As Seen On X.com'));
assert(T.names(T.annotate(row,{force:true})).includes('As Seen On X.com'),'Category survives reclassification');
assert.equal(compactProject(row,at).discoveredVia[0].url,source.url);
assert(T.matches(compactProject(row,at),'As Seen On X.com'),'Category survives compact public responses');
assert.equal(mergeXProvenance(row,row).discoveredVia.length,1);
let screenshots=0,imports=0;
const manifest={schema:1,repositories:[row,row]};
const options={now:()=>at,importer:async(name,provenance,prior)=>{imports++;return {...row,...prior,discoveredVia:prior?.discoveredVia||[]}},capture:async(path)=>{assert.equal(path,src);screenshots++}};
const imported=await importXCandidates(manifest,{repositories:[{...row,discoveredVia:[]}]},options);
assert.equal(imported.catalog.repositories.length,1);
assert.equal(imported.catalog.repositories[0].discoveredVia[0].url,source.url);
assert.equal(imports,1);assert.equal(screenshots,1);
const hidden=await importXCandidates(manifest,{repositories:[]},{...options,controls:entries=>applyListingControls(entries,[{project_id:full,visibility:'excluded'}])});
assert.equal(hidden.catalog.repositories.length,0);assert.equal(imports,1);
const changed=await importXCandidates(manifest,{repositories:[]},{...options,importer:async()=>({...row,demo:'https://new.example.test'})});
assert.equal(changed.catalog.repositories.length,0);assert.equal(screenshots,1);
const failedImage=await importXCandidates(manifest,{repositories:[]},{...options,capture:async()=>{throw Error('invalid jpeg')}});
assert.equal(failedImage.catalog.repositories.length,0);
const stale=await importXCandidates({schema:1,repositories:[{...row,lastCheckedAt:new Date(at-49*3600000).toISOString()}]},{repositories:[]},options);
assert.equal(stale.results.length,0);
console.log('PASS X intake freshness, moderation, screenshot paths, canonical deduplication and additional category.');
