import {randomBytes,createHash} from 'node:crypto';
export class AccountError extends Error{constructor(status,code,message){super(message);this.status=status;this.code=code}}
export const fail=(status,code,message)=>{throw new AccountError(status,code,message)};
export function accountConfig(env=process.env){return {url:env.SUPABASE_URL||env.NEXT_PUBLIC_SUPABASE_URL,key:env.SUPABASE_ANON_KEY||env.SUPABASE_PUBLISHABLE_KEY||env.NEXT_PUBLIC_SUPABASE_ANON_KEY,serviceKey:env.SUPABASE_SERVICE_ROLE_KEY||env.SUPABASE_SECRET_KEY,origin:env.REPOSHELF_PUBLIC_URL||'https://reposhelf.vercel.app'}}
export function createAccounts({config=accountConfig(),fetcher=fetch}={}){
config={...config,origin:new URL(config.origin).origin};const ready=Boolean(config.url&&config.key),secure=new URL(config.origin).protocol==='https:',prefix=secure?'__Host-reposhelf-':'reposhelf-';
const cookies=req=>Object.fromEntries((req.headers.cookie||'').split(';').map(x=>x.trim().split(/=(.*)/s)).filter(x=>x.length>1).map(([k,v])=>[k,decodeURIComponent(v)]));
function cookie(res,name,value,maxAge){const old=res.getHeader('Set-Cookie')||[];res.setHeader('Set-Cookie',[...Array.isArray(old)?old:[old],`${prefix}${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${secure?'; Secure':''}`])}
function clear(res){for(const name of ['access','refresh','verifier','return'])cookie(res,name,'',0)}
function requireReady(){if(!ready)fail(503,'accounts_not_configured','Account sign-in is being set up. Existing browser collections are still available.')}
function origin(req){if(req.headers.origin!==config.origin)fail(403,'origin_not_allowed','Use this action from RepoShelf.')}
async function request(path,{token,service=false,method='GET',body}={}){requireReady();const key=service?config.serviceKey:config.key;if(!key)fail(503,'analytics_not_configured','Analytics storage is not configured.');const headers={apikey:key,'Content-Type':'application/json'};if(token)headers.Authorization=`Bearer ${token}`;else if(/^eyJ/.test(key))headers.Authorization=`Bearer ${key}`;const response=await fetcher(new URL(path,config.url),{method,headers,body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(10000),redirect:'error'});let data;try{data=await response.json()}catch{data=null}if(!response.ok){if(response.status===400&&path.startsWith('/auth/v1/token'))fail(401,'session_expired','Please sign in again.');if(response.status===401)fail(401,'session_expired','Please sign in again.');if(response.status===403||data?.code==='42501')fail(403,'forbidden','Administrator access is required.');if(data?.code==='40001'||response.status===409)fail(409,'edit_conflict','This row changed. Refresh before editing it again.');if(response.status===429||data?.code==='PGRST003')fail(429,'rate_limited','Too many requests. Try again shortly.');fail(503,'database_unavailable','Saved account data is temporarily unavailable. Please try again.')}return data}
async function user(req,res,{optional=false}={}){if(!ready){if(optional)return null;requireReady()}const c=cookies(req);let token=c[prefix+'access'],refresh=c[prefix+'refresh'];if(!token&&!refresh){if(optional)return null;fail(401,'sign_in_required','Sign in to use your synced collection.')}let person;
try{if(token)person=await request('/auth/v1/user',{token})}catch(e){if(e.status!==401)throw e}
if(!person&&refresh){try{const session=await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:refresh}});token=session.access_token;refresh=session.refresh_token;person=await request('/auth/v1/user',{token});cookie(res,'access',token,session.expires_in||3600);cookie(res,'refresh',refresh,1209600)}catch(e){if(e.status!==401)throw e;clear(res)}}
if(!person?.id){clear(res);if(optional)return null;fail(401,'session_expired','Please sign in again.')}return {id:person.id,token,name:person.user_metadata?.user_name||person.user_metadata?.preferred_username||person.user_metadata?.name||'Your account'};
}
async function isAdmin(person){if(!person)return false;return Boolean(await request('/rest/v1/rpc/reposhelf_is_admin',{token:person.token,method:'POST',body:{}}))}
async function admin(req,res){const person=await user(req,res);if(!await isAdmin(person))fail(403,'forbidden','Administrator access is required.');return person}
async function start(req,res){requireReady();const verifier=randomBytes(48).toString('base64url'),challenge=createHash('sha256').update(verifier).digest('base64url');cookie(res,'verifier',verifier,600);const returnTo=new URL(req.url,config.origin).searchParams.get('return');cookie(res,'return',returnTo==='/admin.html'?returnTo:'/',600);const url=new URL('/auth/v1/authorize',config.url);url.searchParams.set('provider','github');url.searchParams.set('redirect_to',config.origin+'/api/auth?action=callback');url.searchParams.set('code_challenge',challenge);url.searchParams.set('code_challenge_method','s256');res.writeHead(302,{Location:url.href,'Cache-Control':'private, no-store'});res.end()}
async function callback(req,res){requireReady();const c=cookies(req),u=new URL(req.url,config.origin),code=u.searchParams.get('code'),verifier=c[prefix+'verifier'];cookie(res,'verifier','',0);cookie(res,'return','',0);try{if(!code||!verifier)fail(400,'invalid_callback','Sign-in could not be completed.');const session=await request('/auth/v1/token?grant_type=pkce',{method:'POST',body:{auth_code:code,code_verifier:verifier}});if(!session.access_token||!session.refresh_token)fail(401,'invalid_session','Sign-in could not be completed.');await request('/auth/v1/user',{token:session.access_token});cookie(res,'access',session.access_token,session.expires_in||3600);cookie(res,'refresh',session.refresh_token,1209600);res.writeHead(302,{Location:c[prefix+'return']==='/admin.html'?'/admin.html':'/','Cache-Control':'private, no-store'});res.end()}catch{clear(res);res.writeHead(302,{Location:'/?signin=failed','Cache-Control':'private, no-store'});res.end()}}
async function signout(req,res){origin(req);const person=await user(req,res,{optional:true});try{if(person)await request('/auth/v1/logout?scope=local',{token:person.token,method:'POST'})}finally{clear(res)}}
return {config,ready,request,user,admin,isAdmin,origin,start,callback,signout};
}
export function respond(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(data))}
export function accountFailure(res,error){respond(res,error.status||503,{error:{code:error.code||'temporarily_unavailable',message:error.status?error.message:'This service is temporarily unavailable. Please try again.'}})}
export async function readBody(req){const limit=32768;if(Number(req.headers['content-length']||0)>limit)fail(413,'body_too_large','Request is too large.');let body=req.body;if(body===undefined){let size=0,parts=[];for await(const chunk of req){size+=Buffer.byteLength(chunk);if(size>limit)fail(413,'body_too_large','Request is too large.');parts.push(Buffer.from(chunk))}body=Buffer.concat(parts).toString()}if(Buffer.byteLength(typeof body==='string'?body:JSON.stringify(body))>limit)fail(413,'body_too_large','Request is too large.');try{return typeof body==='string'?JSON.parse(body):body}catch{fail(400,'invalid_json','Request must be valid JSON.')}}
export function only(req,methods){if(!methods.includes(req.method))fail(405,'method_not_allowed','Method is not supported.')}
