import {applyListingControls,createListingControls} from './listing-policy.mjs';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import {createBrowseIndex,projectKey} from './browse-index.mjs';
import {fail,createAccounts} from './accounts.mjs';
const require=createRequire(import.meta.url),B=require('../dist/browse.js'),P=require('../dist/providers.js');
export function createBrowseService({root=new URL('../',import.meta.url),controls=createListingControls({root,accounts:createAccounts()}),popularity=async()=>({})}={}){
 let pending,communityPending;
 const read=async(path,fallback)=>{try{return JSON.parse(await readFile(new URL(path,root),'utf8'))}catch(e){if(e.code==='ENOENT'&&fallback!==undefined)return fallback;throw e}};
 async function dataset(){if(!pending)pending=(async()=>{try{return {index:await read('data/browse/index.json')}}catch(e){if(e.code!=='ENOENT')throw e;const [catalog,spaces,community]=await Promise.all([read('dist/catalog.json',{repositories:[]}),read('dist/spaces.json',{repositories:[]}),read('dist/community.json',{mentions:[]})]);return createBrowseIndex(catalog,spaces,community)}})().catch(e=>{pending=null;throw e});return pending}
 async function detail(id){if(typeof id!=='string'||!(P.validId(id)||id.startsWith('hf:')&&P.validId(id.slice(3))))fail(400,'invalid_id','Use owner/repository or hf:owner/space.');const d=await dataset(),r=d.index.repositories.find(r=>r.full.toLowerCase()===id.toLowerCase());if(!r||!applyListingControls([r],await controls()).length||r.availability==='unavailable')fail(404,'not_found','Project is not available in the saved catalogue.');const repo=d.projects?d.projects.find(p=>p.full.toLowerCase()===id.toLowerCase()):await read(`data/browse/projects/${projectKey(r.full)}.json`);const C=require('../dist/community.js');return {catalogVersion:d.index.version,repo:C.attach(applyListingControls([repo],await controls()),(await community()).mentions)[0]}}
 async function community(){if(!communityPending)communityPending=(async()=>{const d=await dataset();return d.community||await read('data/browse/community.json',{mentions:[]})})().catch(e=>{communityPending=null;throw e});return communityPending}
 function options(input){if(!input||typeof input!=='object'||Array.isArray(input))fail(400,'invalid_query','Invalid browsing request.');const o={q:input.q||'',category:input.category||'',technology:input.technology||'',source:input.source||'all',sort:input.sort||'popular',demos:input.demos!==false,storefront:input.storefront===true,seed:input.seed||'',ranks:input.ranks||{},exclude:input.exclude||[],limit:input.limit??48};if(!['all','github','huggingface'].includes(o.source)||!['popular','reposhelf','featured','trending','releases','stars','forks','newest','updated','name'].includes(o.sort)||!Number.isSafeInteger(o.limit)||o.limit<1||o.limit>48||!Array.isArray(o.exclude)||o.exclude.length>5000||o.exclude.some(id=>typeof id!=='string'||id.length>220)||typeof o.ranks!=='object'||Array.isArray(o.ranks)||Object.values(o.ranks).some(rank=>!['popular','trending'].includes(rank)))fail(400,'invalid_query','Invalid browsing filters.');for(const key of ['q','category','technology','seed'])if(typeof o[key]!=='string'||o[key].length>(key==='q'?500:100))fail(400,'invalid_query','Invalid browsing filters.');if(input.demos!==undefined&&typeof input.demos!=='boolean')fail(400,'invalid_query','Choose whether to show live demos only.');return o}
 async function search(input,editorial){const o=options(input),base=await dataset(),settings=await controls(),d={...base,index:{...base.index,repositories:applyListingControls(base.index.repositories,settings),version:createHash('sha256').update(base.index.version+JSON.stringify(settings)).digest('hex').slice(0,20)}};if(o.sort==='reposhelf'||o.storefront&&editorial.rows?.some(r=>r.enabled&&r.mode==='reposhelf')){const counts=await popularity();d.index.repositories=d.index.repositories.map(r=>({...r,repoShelfClicks:counts[r.full.toLowerCase()]||0}));d.index.version=createHash('sha256').update(d.index.version+JSON.stringify(counts)).digest('hex').slice(0,20)}const query=createHash('sha256').update(JSON.stringify(o)).digest('hex').slice(0,20);o.offset=0;if(input.cursor){try{if(typeof input.cursor!=='string'||input.cursor.length>500)throw Error();const c=JSON.parse(Buffer.from(input.cursor,'base64url').toString());if(c.version!==d.index.version)fail(409,'catalog_changed','The catalogue has changed. Search again for current results.');if(c.query!==query||!Number.isSafeInteger(c.offset)||c.offset<0||c.offset>d.index.repositories.length)throw Error();o.offset=c.offset}catch(e){if(e.status===409)throw e;fail(400,'invalid_cursor','This page belongs to a different search.')}}const mentions=o.storefront?(await community()).mentions:[];const result=B.select(d.index.repositories,o,editorial,mentions);const nextCursor=result.nextOffset===null?null:Buffer.from(JSON.stringify({version:d.index.version,query,offset:result.nextOffset})).toString('base64url');delete result.nextOffset;return {...result,nextCursor,catalogVersion:d.index.version,snapshots:d.index.snapshots}}
 return {search,detail,community,dataset};
}
