import {createCheckpointStore} from './checkpoint-store.mjs';
const qualityCheckpoint=createCheckpointStore();
import {readFile} from 'node:fs/promises';import {createRequire} from 'node:module';
import {respond,readBody,only,fail} from './accounts.mjs';import {requireLegal} from './legal.mjs';import {validListing} from './listing-policy.mjs';import {qualityOverview} from './catalog-quality.mjs';import {workerAccess} from './submissions.mjs';
const E=createRequire(import.meta.url)('../dist/editorial.js'),reasons=['broken_demo','misleading','inappropriate','ownership','copyright','other'];
export async function editorialLaunch(req,res,{accounts,browse,action,params,key=process.env.REPOSHELF_SUBMISSION_SYNC_KEY,checkpoint=qualityCheckpoint}){
 if(action==='sync-controls'){only(req,['POST']);workerAccess(req,key);const items=await accounts.request('/rest/v1/rpc/reposhelf_public_listing_controls',{service:true,method:'POST',body:{}});return respond(res,200,{items})}
 if(req.method!=='GET')accounts.origin(req);const person=action==='report'?await accounts.user(req,res):await accounts.admin(req,res);
 if(action==='report'){only(req,['POST']);if(!person.githubId)fail(403,'github_required','Connect your GitHub account to report a listing.');await requireLegal(accounts,person);const input=await readBody(req);if(!validListing(input?.id)||!reasons.includes(input.reason)||typeof input.explanation!=='string'||input.explanation.length>2000)fail(400,'invalid_report','Choose a reason and keep your explanation under 2,000 characters.');const data=await accounts.request('/rest/v1/rpc/reposhelf_report_listing',{token:person.token,method:'POST',body:{project:input.id,report_reason:input.reason,details:input.explanation.trim()}});return respond(res,202,data)}
 if(action==='quality'){only(req,['GET']);const offset=Number(params.get('offset')||0),q=params.get('q')||'',issue=params.get('issue')||'';if(!Number.isSafeInteger(offset)||offset<0||offset>1000000||q.length>200||issue.length>40)fail(400,'invalid_query','Invalid quality filters.');const [dataset,controls,rows,analytics]=await Promise.all([browse.dataset(),accounts.request('/rest/v1/rpc/reposhelf_public_listing_controls',{token:person.token,method:'POST',body:{}}),accounts.request('/rest/v1/editorial_ribbons?select=*',{token:person.token}),accounts.request('/rest/v1/rpc/reposhelf_analytics',{token:person.token,method:'POST',body:{days:30}})]);const savedQuality=await checkpoint.json('data/catalogue-quality.json',5000);const current=savedQuality?.schema===1&&Array.isArray(savedQuality.entries)&&Number.isFinite(Date.parse(savedQuality.at))?savedQuality:null;const entries=(current?.entries||dataset.index.repositories).map(r=>current?{...r,...r.previewCandidate?{previewCandidate:{...r.previewCandidate,displaySrc:'https://raw.githubusercontent.com/sparx1981/RepoShelf/reposhelf-checkpoints/dist/'+r.previewCandidate.src}}:{},screenshots:(r.screenshots||[]).map(s=>({...s,src:s.src?.startsWith('previews/')?'https://raw.githubusercontent.com/sparx1981/RepoShelf/reposhelf-checkpoints/dist/'+s.src:s.src}))}:r);for(const c of controls)if(!entries.some(r=>r.full.toLowerCase()===c.project_id.toLowerCase()))entries.push({full:c.project_id,name:c.project_id,availability:'unavailable'});const data=qualityOverview(entries,controls,{offset,q,issue,featured:E.resolve(rows).filter(r=>['hero','picks'].includes(r.builtin_key)&&r.enabled).flatMap(r=>r.items),views:Object.fromEntries((analytics.topListings||[]).map(r=>[r.project_id,r.views]))});let history=[];try{history=JSON.parse(await readFile(new URL('../dist/growth.json',import.meta.url),'utf8')).snapshots||[]}catch(e){if(e.code!=='ENOENT')throw e}return respond(res,200,{...data,qualitySource:current?'Latest saved sync':'Deployed catalogue',qualityAsOf:current?.at||dataset.index.snapshots?.catalog||null,history:history.slice(-30).map(r=>({at:r.at,published:r.published,records:r.records,withScreenshot:r.withScreenshot,withDemo:r.withDemo,unavailable:r.unavailable}))})}
 if(action==='reports'){only(req,['GET']);const status=params.get('status')||'open',offset=Number(params.get('offset')||0);if(!['open','reviewed','dismissed','all'].includes(status)||!Number.isSafeInteger(offset)||offset<0||offset>1000000)fail(400,'invalid_query','Invalid report filters.');const items=await accounts.request('/rest/v1/listing_reports?select=*&order=created_at.desc,id.desc&limit=30&offset='+offset+(status==='all'?'':'&status=eq.'+status),{token:person.token});return respond(res,200,{items,nextOffset:items.length===30?offset+30:null})}
 if(action==='audit'){only(req,['GET']);if(!validListing(params.get('id')))fail(400,'invalid_project','Choose a listing.');const items=await accounts.request('/rest/v1/listing_moderation_audit?select=*&project_id=eq.'+encodeURIComponent(params.get('id'))+'&order=created_at.desc,id.desc&limit=30',{token:person.token});return respond(res,200,{items})}
 only(req,['POST']);const input=await readBody(req);if(action==='review-report'){if(!/^[a-f\d-]{36}$/i.test(input?.id)||!Number.isSafeInteger(input.revision)||!['reviewed','dismissed'].includes(input.status)||typeof input.note!=='string'||input.note.length>2000)fail(400,'invalid_review','Check the report and review note.');const updated=await accounts.request('/rest/v1/rpc/reposhelf_review_report',{token:person.token,method:'POST',body:{report:input.id,expected_revision:input.revision,review_status:input.status,admin_note:input.note.trim()}});return respond(res,200,{updated})}
 if(!validListing(input?.id)||!Number.isSafeInteger(input.revision)||input.revision<0||!['visible','hidden','excluded'].includes(input.visibility)||typeof input.description!=='string'||input.description.length>2000||typeof input.category!=='string'||input.category.length>100||typeof input.note!=='string'||input.note.length>2000||typeof input.rejectPreview!=='boolean'||typeof input.refresh!=='boolean'||input.preview!==null&&(typeof input.preview!=='string'||input.preview.length>2048))fail(400,'invalid_control','Check the listing settings.');const control=await accounts.request('/rest/v1/rpc/reposhelf_moderate_listing',{token:person.token,method:'POST',body:{project:input.id,expected_revision:input.revision,settings:{visibility:input.visibility,description:input.description.trim(),category:input.category.trim(),preview_rejected:input.rejectPreview,rejected_preview:input.preview,refresh:input.refresh},admin_note:input.note.trim()}});return respond(res,200,{control});
}
