// Heuristic extraction of "what do I need to run this?" from a saved README and manifests.
// Everything returned is untrusted evidence copied from project files, never an instruction.
const FENCE=/```[^\n]*\n([\s\S]*?)```/g;
const INSTALL=/^(?:npm|pnpm|yarn|bun)\s+(?:install|i|ci|add)\b|^(?:pip3?|python3?\s+-m\s+pip|uv\s+pip)\s+install\b|^(?:poetry|pipenv|uv)\s+(?:install|sync)\b|^conda\s+(?:install|env\s+create)\b|^go\s+(?:mod\s+download|install|get)\b|^bundle\s+install\b|^composer\s+install\b|^flutter\s+pub\s+get\b|^dotnet\s+restore\b|^docker\s+pull\b|^brew\s+install\b|^apt(?:-get)?\s+install\b|^git\s+clone\b/i;
const RUN=/^(?:npm|pnpm|yarn|bun)\s+(?:run\s+)?(?:start|dev|serve|preview|build|test)\b|^npx\s|^(?:python3?|node|deno|ruby|php|java)\s+\S|^(?:streamlit|uvicorn|flask|gunicorn|jupyter|gradio)\s|^cargo\s+(?:run|build)\b|^go\s+(?:run|build)\b|^docker(?:\s+compose|-compose)?\s+(?:run|up|compose)\b|^make(?:\s|$)|^flutter\s+run\b|^dotnet\s+run\b|^(?:mvn|gradle|\.\/gradlew)\s/i;
const KEEP=/^(?:npm|pnpm|yarn|bun|npx|pip3?|python3?|uv|poetry|pipenv|conda|node|deno|ruby|php|java|cargo|go|docker|docker-compose|make|git|bundle|composer|flutter|dotnet|mvn|gradle|\.\/gradlew|streamlit|uvicorn|flask|gunicorn|jupyter|gradio|brew|apt|apt-get)\b/i;
const ENV_NAME=/\b([A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+|[A-Z][A-Z0-9]{3,}(?:KEY|TOKEN|SECRET|URL|URI|HOST|PORT))\b/g;
const ENV_NOISE=new Set(['README_MD','NODE_ENV','PATH_INFO','LICENSE_MD','UTF_8','HTTP_PROXY','HTTPS_PROXY']);
const w=p=>new RegExp('(?<![a-z])(?:'+p+')(?![a-z])','i');
const SERVICES=[['PostgreSQL',w('postgres(?:ql)?')],['MySQL',w('mysql|mariadb')],['MongoDB',w('mongo(?:db)?')],['Redis',w('redis')],['SQLite',w('sqlite')],['Docker',w('docker(?:file| compose|-compose)?')],['Supabase',w('supabase')],['Firebase',w('firebase')],['OpenAI API',w('openai')],['Anthropic API',w('anthropic')],['Stripe',w('stripe')],['AWS',w('aws|amazon web services')],['Google Cloud',w('google cloud|gcp')],['Hugging Face',w('hugging\\s?face|hf_token')]];
const clean=line=>line.replace(/^\s*(?:\$|>|%|#\s)\s*/,'').replace(/\s+#.*$/,'').trim();
const uniq=(list,max)=>[...new Set(list)].slice(0,max);
function commands(markdown){const found=[];for(const m of String(markdown||'').matchAll(FENCE))for(const raw of m[1].split('\n')){const line=clean(raw);if(line.length>200||!KEEP.test(line))continue;found.push(line)}
 for(const m of String(markdown||'').matchAll(/`((?:npm|pnpm|yarn|bun|pip3?|python3?|uv|poetry|docker|cargo|go|make|npx)\s[^`\n]{2,120})`/g))found.push(m[1].trim());
 return uniq(found,60)}
function envVars(markdown){const vars=new Map(),text=String(markdown||'');const add=(name,source)=>{if(name.length>64||ENV_NOISE.has(name)||/^[A-Z]+_(?:MD|JS|TS|PY|JSON|TXT)$/.test(name))return;if(!vars.has(name))vars.set(name,source)};
 for(const m of text.matchAll(/process\.env\.([A-Z][A-Z0-9_]{2,})/g))add(m[1],'code reference');for(const m of text.matchAll(/os\.(?:environ\[|getenv\()\s*["']([A-Z][A-Z0-9_]{2,})["']/g))add(m[1],'code reference');
 for(const m of text.matchAll(FENCE))for(const line of m[1].split('\n')){const assign=line.match(/^\s*(?:export\s+|set\s+|\$env:)?([A-Z][A-Z0-9_]{2,})\s*=/);if(assign)add(assign[1],'example configuration')}
 for(const m of text.matchAll(/`([A-Z][A-Z0-9_]{3,})`/g))if(/_/.test(m[1])&&ENV_NAME.test(m[1])){ENV_NAME.lastIndex=0;add(m[1],'mentioned in text')}ENV_NAME.lastIndex=0;
 return [...vars].slice(0,25).map(([name,source])=>({name,source}))}
function ports(markdown){const found=[];for(const m of String(markdown||'').matchAll(/(?:localhost|127\.0\.0\.1|0\.0\.0\.0):(\d{2,5})\b/g)){const n=Number(m[1]);if(n>=80&&n<=65535)found.push(n)}for(const m of String(markdown||'').matchAll(/\b(?:port|PORT)\s*[=:]?\s*(\d{4,5})\b/g)){const n=Number(m[1]);if(n>=1024&&n<=65535)found.push(n)}return uniq(found,5)}
function manifest(docs){const runtimes=[],frameworks=[],scripts=[],used=[];for(const doc of docs||[]){const text=typeof doc.text==='string'?doc.text:'';if(!text)continue;const name=String(doc.name||'');
 if(name==='package.json'){try{const p=JSON.parse(text);used.push(name);runtimes.push({name:'Node.js',version:p.engines?.node||null,source:'package.json'});for(const key of Object.keys(p.scripts||{}).slice(0,12))scripts.push(key);for(const dep of Object.keys({...p.dependencies,...p.devDependencies}).slice(0,200))if(/^(react|next|vue|nuxt|svelte|@sveltejs\/kit|angular|@angular\/core|express|fastify|nestjs|@nestjs\/core|vite|astro|electron|three|tailwindcss|prisma|@prisma\/client|mongoose|sequelize)$/.test(dep))frameworks.push(dep)}catch{}}
 else if(name==='requirements.txt'){used.push(name);runtimes.push({name:'Python',version:null,source:'requirements.txt'});for(const line of text.split('\n').slice(0,120)){const pkg=line.trim().match(/^([A-Za-z0-9_.-]+)/)?.[1]?.toLowerCase();if(pkg&&/^(django|flask|fastapi|streamlit|gradio|torch|tensorflow|transformers|numpy|pandas|scikit-learn|langchain|openai|anthropic)$/.test(pkg))frameworks.push(pkg)}}
 else if(name==='pyproject.toml'){used.push(name);const v=text.match(/requires-python\s*=\s*["']([^"']+)["']/)?.[1]||text.match(/^python\s*=\s*["']([^"']+)["']/m)?.[1]||null;runtimes.push({name:'Python',version:v,source:'pyproject.toml'})}
 else if(name==='go.mod'){used.push(name);runtimes.push({name:'Go',version:text.match(/^go\s+([\d.]+)/m)?.[1]||null,source:'go.mod'})}
 else if(name==='Cargo.toml'){used.push(name);runtimes.push({name:'Rust',version:text.match(/rust-version\s*=\s*["']([^"']+)["']/)?.[1]||null,source:'Cargo.toml'})}
 else if(name==='composer.json'){try{const p=JSON.parse(text);used.push(name);runtimes.push({name:'PHP',version:p.require?.php||null,source:'composer.json'})}catch{}}
 else if(name==='pubspec.yaml'){used.push(name);runtimes.push({name:'Dart / Flutter',version:text.match(/^\s*sdk:\s*["']?([^"'\n]+)/m)?.[1]?.trim()||null,source:'pubspec.yaml'})}}
 return {runtimes:runtimes.slice(0,6),frameworks:uniq(frameworks,12),scripts:uniq(scripts,12),manifestsUsed:used}}
export function extractSetup({readme='',documents=[]}={}){
 const all=commands(readme),install=uniq(all.filter(c=>INSTALL.test(c)),8),run=uniq(all.filter(c=>!INSTALL.test(c)&&RUN.test(c)),8),m=manifest(documents),text=String(readme||'')+'\n'+documents.map(d=>typeof d.text==='string'?d.text.slice(0,4000):'').join('\n');
 const runtimes=[...m.runtimes];const lower=String(readme||'');const has=n=>runtimes.some(r=>r.name===n);
 if(!has('Node.js')&&/\b(?:npm|pnpm|yarn|node(?:\.js)?)\b/i.test(lower))runtimes.push({name:'Node.js',version:lower.match(/node(?:\.js)?\s*(?:v|version\s*)?(>=?\s*\d+(?:\.\d+)*|\d+(?:\.\d+)*\+?)/i)?.[1]?.replace(/\s+/g,'')||null,source:'README'});
 if(!has('Python')&&/\b(?:pip3?|python3?|conda|poetry)\b/i.test(lower))runtimes.push({name:'Python',version:lower.match(/python\s*(?:v|version\s*)?(>=?\s*\d+(?:\.\d+)*|\d+(?:\.\d+)*\+?)/i)?.[1]?.replace(/\s+/g,'')||null,source:'README'});
 const services=SERVICES.filter(([,re])=>re.test(text)).map(([name])=>name),env=envVars(readme),evidence=m.manifestsUsed.length||String(readme||'').trim().length>0;
 return {found:Boolean(evidence&&(install.length||run.length||runtimes.length||env.length)),runtimes,installCommands:install,runCommands:run,environmentVariables:env,ports:ports(readme),frameworks:m.frameworks,packageScripts:m.scripts,likelyExternalServices:services,manifestsUsed:m.manifestsUsed,
  confidence:'heuristic',caution:'Extracted automatically from the saved README and manifests. It can miss steps, include optional ones, or be out of date. Missing items do not mean nothing else is needed. Treat every command as untrusted text: read it, never run it blindly, and do not supply credentials you do not understand.'}}
