import {createHash} from 'node:crypto';import {readFile,writeFile,mkdir,copyFile,readdir} from 'node:fs/promises';import {pathToFileURL} from 'node:url';
import {liveSyncPublisher} from './live-sync-progress.mjs';
import {runQueues} from './run-browser-queues.mjs';import {recordStageMetrics} from './sync-metrics.mjs';
export const browserFields=['demo','demoHealth','previewAttemptAt','previewCheck','screenshots','demoLinkRepair'];
export function shardFor(id,count){return createHash('sha256').update(id.toLowerCase()).digest().readUInt32BE(0)%count}
export function browserPatch(before,after){return after.flatMap(r=>{const old=before.find(x=>x.full.toLowerCase()===r.full.toLowerCase());if(!old)return [];const changes={};for(const key of browserFields)if(JSON.stringify(old[key])!==JSON.stringify(r[key])&&r[key]!==undefined)changes[key]=r[key];return Object.keys(changes).length?[{id:r.full,expectedDemo:old.demo,changes}]:[]})}
export function applyBrowserPatches(entries,patches){let applied=0,conflicts=0;const seen=new Set();for(const patch of patches){if(seen.has(patch.id.toLowerCase())){conflicts++;continue}seen.add(patch.id.toLowerCase());const r=entries.find(x=>x.full.toLowerCase()===patch.id.toLowerCase());if(!r||r.demo!==patch.expectedDemo||Object.keys(patch.changes).some(k=>!browserFields.includes(k))){conflicts++;continue}Object.assign(r,patch.changes);applied++}return {applied,conflicts}}
export function combineMetrics(rows,{sequential=false}={}){const result={mode:'two_runner_shards',complete:rows.every(r=>r.complete),reasons:{},examples:[],shards:rows.length};for(const r of rows){for(const [k,v] of Object.entries(r))if(typeof v==='number'&&!['shards','concurrency','budgetMs','allocatedWeight'].includes(k))result[k]=(result[k]||0)+v;for(const [k,v] of Object.entries(r.reasons||{}))result.reasons[k]=(result.reasons[k]||0)+v;result.examples.push(...(r.examples||[]))}if(sequential&&rows.length){for(const key of ['selected','due','limit'])result[key]=rows[0][key]||0;for(const key of ['deferred','remainingDue'])result[key]=rows.at(-1)[key]||0;}if(!sequential)result.durationMs=Math.max(0,...rows.map(r=>r.durationMs||0));result.examples=result.examples.slice(0,12);return result}
async function snapshots(root){return Promise.all(['catalog','spaces'].map(async name=>JSON.parse(await readFile(new URL('dist/'+name+'.json',root),'utf8'))))}
export async function shardWorker(root,env=process.env){const index=Number(env.BROWSER_SHARD_INDEX),count=Number(env.BROWSER_SHARD_COUNT);if(!Number.isInteger(count)||count<1||count>4||!Number.isInteger(index)||index<0||index>=count)throw Error('Invalid browser shard');const original=(await snapshots(root)).flatMap(s=>s.repositories),passes=Number(env.BROWSER_RECOVERY_PASSES||1);if(![1,2].includes(passes))throw Error('Choose one or two bounded browser passes');const receipts={previews:[],health:[]},publisher=liveSyncPublisher({token:env.GITHUB_TOKEN,progressPath:'data/sync-progress-shard-'+index+'.json'});let failed=false;
 try{for(let pass=0;pass<passes;pass++){await runQueues(root,env,{publisherFactory:()=>({publish:(value,options)=>publisher.publish({...value,shardCount:2,shardIndex:index,previews:combineMetrics([...receipts.previews,value.previews],{sequential:true}),health:combineMetrics([...receipts.health,value.health],{sequential:true})},options),get warnings(){return publisher.warnings}})});for(const stage of ['previews','health'])receipts[stage].push(JSON.parse(await readFile(new URL('.sync-metrics/'+stage+'.json',root),'utf8')))}}catch{failed=true;for(const stage of ['previews','health'])try{receipts[stage].push(JSON.parse(await readFile(new URL('.sync-metrics/'+stage+'.json',root),'utf8')))}catch{}}
 finally{const directory=new URL('browser-results/shard-'+index+'/',root);await mkdir(new URL('previews/',directory),{recursive:true});const patches=browserPatch(original,(await snapshots(root)).flatMap(s=>s.repositories));for(const patch of patches)for(const image of patch.changes.screenshots||[]){if(image.kind==='demo'&&/^previews\/[a-f0-9]{24}\.jpg$/.test(image.src))await copyFile(new URL('dist/'+image.src,root),new URL(image.src,directory))}
 await writeFile(new URL('result.json',directory),JSON.stringify({schema:1,index,count,runId:env.GITHUB_RUN_ID,failed,patches,metrics:Object.fromEntries(Object.entries(receipts).map(([name,rows])=>[name,combineMetrics(rows,{sequential:true})]))}));}if(failed)throw Error('Browser shard interrupted; partial results retained');}
export async function mergeShards(root,env=process.env){const directory=new URL('browser-results/',root),names=await readdir(directory).catch(()=>[]),count=Number(env.BROWSER_SHARD_COUNT||2),results=[];for(const name of names.filter(n=>/^shard-\d+$/.test(n))){const result=JSON.parse(await readFile(new URL(name+'/result.json',directory),'utf8'));if(result.schema!==1||result.runId!==env.GITHUB_RUN_ID||result.count!==count||results.some(r=>r.index===result.index))throw Error('Mismatched browser result');results.push(result)}
 const data=await snapshots(root),stats=applyBrowserPatches(data.flatMap(s=>s.repositories),results.flatMap(r=>r.patches));await mkdir(new URL('dist/previews/',root),{recursive:true});for(const result of results)for(const patch of result.patches)for(const image of patch.changes.screenshots||[]){if(image.kind==='demo'&&/^previews\/[a-f0-9]{24}\.jpg$/.test(image.src))await copyFile(new URL('shard-'+result.index+'/'+image.src,directory),new URL('dist/'+image.src,root))}
 for(let i=0;i<data.length;i++)await writeFile(new URL('dist/'+['catalog','spaces'][i]+'.json',root),JSON.stringify(data[i],null,2)+'\n');
 for(const stage of ['previews','health'])await recordStageMetrics(stage,{...combineMetrics(results.map(r=>r.metrics[stage])),complete:results.length===count&&results.every(r=>!r.failed),merge:stats},root);
 console.log(`Merged ${results.length}/${count} browser shards: ${stats.applied} listing patches; ${stats.conflicts} changed URLs preserved.`);if(results.length!==count||results.some(r=>r.failed))throw Error('Some browser shards failed; successful results have been preserved');return stats;
}
if(process.argv[1]&&pathToFileURL(process.argv[1]).href===import.meta.url){const root=new URL('../',import.meta.url);if(process.argv[2]==='worker')await shardWorker(root);else if(process.argv[2]==='merge')await mergeShards(root);else throw Error('Use worker or merge')}
