import {readFileSync,existsSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
for(const file of ['dist/index.html','dist/style.css','dist/app.js','dist/discovery.js','dist/storefront.js','dist/catalog.json','dist/spaces.json','dist/providers.js','dist/quality.js','dist/community.js'])if(!existsSync(file))throw new Error(`Missing ${file}`);
for(const file of ['api/submissions.mjs','lib/submissions.mjs','dist/submissions.js','scripts/import-submissions.mjs','scripts/submission-imports.mjs','scripts/verify-submissions-ui.mjs','dist/outgoing-links.js','api/promotions.mjs','lib/promotion-payments.mjs','lib/promotion-health.mjs','dist/promotions.js','scripts/sync-promotions.mjs','scripts/verify-promotions-ui.mjs','scripts/verify-legal-ui.mjs','lib/legal.mjs','dist/legal.js','api/open.mjs','scripts/sync-history.mjs','api/sync-log.mjs','api/forks.mjs','dist/app.js','dist/account.js','dist/admin.js','dist/admin-help.js','api/admin-users.mjs','lib/accounts.mjs','api/auth.mjs','api/collection.mjs','api/editorial.mjs','api/analytics.mjs','scripts/record-growth.mjs','dist/discovery.js','scripts/index-catalog.mjs','scripts/catalog-health.mjs','scripts/serve.mjs','dist/storefront.js','scripts/enrich-catalog.mjs','scripts/capture-previews.mjs','scripts/verify-ui.mjs','dist/providers.js','scripts/source-imports.mjs','scripts/import-sources.mjs','scripts/readme-overviews.mjs','scripts/enrich-overviews.mjs','dist/quality.js','scripts/demo-health.mjs','scripts/check-demo-health.mjs','scripts/project-insights.mjs','scripts/ai-overviews.mjs','scripts/generate-ai-overviews.mjs','scripts/bluesky-stream.mjs','scripts/community-sources.mjs','scripts/import-community.mjs','dist/community.js'])execFileSync(process.execPath,['--check',file],{stdio:'inherit'});
JSON.parse(readFileSync('dist/catalog.json','utf8'));
const html=readFileSync('dist/index.html','utf8');
for(const path of ['style.css','discovery.js','storefront.js','providers.js','quality.js','community.js','account.js','app.js'])if(!html.includes(path))throw new Error(`Missing HTML reference to ${path}`);
JSON.parse(readFileSync('vercel.json','utf8'));
console.log('RepoShelf static build validated. Output: dist/');
