import {createRequire} from 'node:module';const require=createRequire(import.meta.url),C=require('../dist/community.js');
const RESERVED=new Set(['features','topics','collections','marketplace','settings','login','signup','search','orgs','users','sponsors','explore','events','notifications','new','about','pricing','security','site']);
export function githubLinks(...texts){const ids=new Map();for(const text of texts){const decoded=String(text||'').replace(/&amp;/g,'&');for(const match of decoded.matchAll(/https?:\/\/(?:www\.)?github\.com\/([\w.-]+)\/([\w.-]+)/gi)){const owner=match[1],name=match[2].replace(/\.git$/i,'').replace(/[.,]+$/,'');if(RESERVED.has(owner.toLowerCase())||!name||name==='.'||name==='..')continue;const full=`${owner}/${name}`;ids.set(full.toLowerCase(),full)}}return [...ids.values()].slice(0,8)}
export function hackerNewsPosts(hits,now=Date.now()){const out=[];for(const hit of hits||[]){const id=String(hit.objectID||'');if(!/^\d+$/.test(id)||hit._tags?.includes('comment'))continue;const publishedAt=hit.created_at||(Number.isFinite(Number(hit.created_at_i))?new Date(Number(hit.created_at_i)*1000).toISOString():null);if(!publishedAt)continue;const fulls=githubLinks(hit.url,hit.story_text);for(const full of fulls){const post={source:'hackernews',id,full,url:`https://news.ycombinator.com/item?id=${id}`,title:String(hit.title||'Repository discussion').slice(0,240),author:String(hit.author||'').slice(0,160),publishedAt,points:Math.max(0,Number(hit.points)||0),comments:Math.max(0,Number(hit.num_comments)||0),checkedAt:new Date(now).toISOString()};if(C.validPost(post,now))out.push(post)}}return out}
function embedLinks(embed){return [embed?.external?.uri,embed?.record?.embeds?.map(x=>x.external?.uri).join(' '),embed?.media?.external?.uri].filter(Boolean)}
export function blueskyPosts(posts,now=Date.now()){const out=[];for(const post of posts||[]){const uri=String(post.uri||'').match(/^at:\/\/(did:[a-z0-9]+:[A-Za-z0-9._:%-]+)\/app\.bsky\.feed\.post\/([a-zA-Z0-9]+)$/);if(!uri||post.author?.did!==uri[1])continue;const r=post.record||{},links=(r.facets||[]).flatMap(f=>(f.features||[]).filter(x=>x.$type==='app.bsky.richtext.facet#link').map(x=>x.uri));const fulls=githubLinks(r.text,...links,...embedLinks(r.embed),...embedLinks(post.embed));for(const full of fulls){const entry={source:'bluesky',id:post.uri,full,url:`https://bsky.app/profile/${uri[1]}/post/${uri[2]}`,title:String(r.text||'Repository discussion').slice(0,240),author:uri[1],authorName:String(post.author.handle||'').slice(0,160),publishedAt:r.createdAt,engagementKnown:[post.likeCount,post.replyCount,post.repostCount].every(n=>typeof n==='number'&&Number.isFinite(n)),likes:Math.max(0,Number(post.likeCount)||0),replies:Math.max(0,Number(post.replyCount)||0),reposts:Math.max(0,Number(post.repostCount)||0),checkedAt:new Date(now).toISOString()};if(C.validPost(entry,now))out.push(entry)}}return out}
async function json(url,fetcher){const response=await fetcher(url,{signal:AbortSignal.timeout(15000)});if(!response.ok)throw Object.assign(Error(`HTTP ${response.status}`),{status:response.status});return response.json()}
export async function collectCommunity(prior=[],{fetcher=fetch,now=Date.now(),pages=3,streamCollector}={}){const mentions=new Map(prior.filter(p=>C.validPost(p,now)).map(p=>[`${p.source}:${p.id}:${p.full.toLowerCase()}`,p])),sources={};const cutoff=new Date(now-C.WINDOW).toISOString();
for(const source of ['hackernews','bluesky']){let found=0;try{let cursor;for(let page=0;page<Math.min(3,Math.max(1,pages));page++){let data,entries;if(source==='hackernews'){const u=new URL('https://hn.algolia.com/api/v1/search_by_date');u.search=new URLSearchParams({query:'github.com',tags:'story',numericFilters:`created_at_i>${Math.floor((now-C.WINDOW)/1000)}`,hitsPerPage:'100',page:String(page)});data=await json(u.href,fetcher);if(!Array.isArray(data.hits))throw Error('Invalid search response');entries=hackerNewsPosts(data.hits,now);if(page+1>=data.nbPages||!data.hits.length)cursor=false;else cursor=true;}else{const u=new URL('https://public.api.bsky.app/xrpc/app.bsky.feed.searchPosts');u.search=new URLSearchParams({q:'github.com',sort:'latest',limit:'100',since:cutoff,...(cursor?{cursor}:{})});data=await json(u.href,fetcher);if(!Array.isArray(data.posts))throw Error('Invalid search response');entries=blueskyPosts(data.posts,now);const next=typeof data.cursor==='string'?data.cursor:null;cursor=next!==cursor?next:null;}
for(const p of entries){mentions.set(`${p.source}:${p.id}:${p.full.toLowerCase()}`,p);found++}if(!cursor)break}sources[source]={status:'ok',checkedAt:new Date(now).toISOString(),mentionsFound:found};}catch(e){sources[source]={status:'retry',attemptedAt:new Date(now).toISOString(),reason:e.status?`http_${e.status}`:'temporary',mentionsFound:found};if(source==='bluesky'&&[401,403].includes(e.status)){try{const collect=streamCollector||(await import('./bluesky-stream.mjs')).collectBlueskyStream;const stream=await collect({now,fetcher});for(const [key,p]of mentions)if((stream.removed||[]).includes(p.id))mentions.delete(key);for(const p of stream.mentions)mentions.set(`${p.source}:${p.id}:${p.full.toLowerCase()}`,p);sources[source]={status:'ok',method:'public-stream',checkedAt:new Date(now).toISOString(),mentionsFound:stream.mentions.length,searchStatus:`http_${e.status}`,eventsScanned:stream.eventsScanned,sampleSince:stream.sampleSince,partial:stream.partial};}catch{sources[source].reason='search_restricted_and_stream_unavailable';}}}}
return {mentions:[...mentions.values()].sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt)).slice(0,2000),sources};}
