import {readFile,writeFile} from 'node:fs/promises';import {createRequire} from 'node:module';const require=createRequire(import.meta.url);const S=require('../dist/storefront.js');
const file=new URL('../dist/catalog.json',import.meta.url);const catalog=JSON.parse(await readFile(file,'utf8'));const now=Date.now();const at=new Date(now).toISOString();const headers={Accept:'application/vnd.github+json','User-Agent':'RepoShelf-catalog'};if(process.env.GITHUB_TOKEN)headers.Authorization=`Bearer ${process.env.GITHUB_TOKEN}`;
for(let i=0;i<catalog.repositories.length;i++){let r=catalog.repositories[i];r={...r,technologies:S.technologies(r)};if(r.lastCheckedAt&&now-Date.parse(r.lastCheckedAt)<24*3600000)r=S.recordMetrics(r,Date.parse(r.lastCheckedAt));catalog.repositories[i]=r}
const candidates=catalog.repositories.filter(r=>r.availability!=='unavailable'&&(!r.enrichmentAttemptAt||now-Date.parse(r.enrichmentAttemptAt)>24*3600000)).sort((a,b)=>(Date.parse(a.enrichmentAttemptAt)||0)-(Date.parse(b.enrichmentAttemptAt)||0)||S.popularity(b)-S.popularity(a)).slice(0,Number(process.env.CATALOG_ENRICH_BATCH||80));let failed=0;
for(const r of candidates){r.enrichmentAttemptAt=at;try{const res=await fetch(`https://api.github.com/repos/${r.full}/releases/latest`,{headers,signal:AbortSignal.timeout(10000)});if(res.status===403||res.status===429){failed++;break}if(res.ok){const release=await res.json();r.latestRelease={name:release.name||release.tag_name,tag:release.tag_name,publishedAt:release.published_at,url:release.html_url};r.releaseCheckedAt=at}else if(res.status===404){r.latestRelease=null;r.releaseCheckedAt=at}else failed++}catch{failed++}
try{const res=await fetch(`https://raw.githubusercontent.com/${r.full}/${encodeURIComponent(r.branch||'main')}/package.json`,{signal:AbortSignal.timeout(7000)});if(res.ok)r.technologies=S.technologies(r,await res.json())}catch{failed++}
if(!(r.screenshots||[]).length)try{const res=await fetch(`https://raw.githubusercontent.com/${r.full}/${encodeURIComponent(r.branch||'main')}/README.md`,{signal:AbortSignal.timeout(7000)});if(res.ok)r.screenshots=S.readmeImages(await res.text(),r)}catch{failed++}
}
catalog.updatedAt=new Date().toISOString();await writeFile(file,JSON.stringify(catalog,null,2)+'\n');console.log(`Enriched ${candidates.length} projects; ${failed} temporary failures. Historical counts retained for measured trends.`);
