import {readFile,writeFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';import {dueEntries} from './catalog-health.mjs';import {checkSpace,verifySpaceSource,listCandidates,importListCandidate,readGithubReadme} from './source-imports.mjs';const require=createRequire(import.meta.url);const P=require('../dist/providers.js');
const root=new URL('../',import.meta.url);async function read(path,fallback){try{return JSON.parse(await readFile(new URL(path,root),'utf8'))}catch(e){if(e.code!=='ENOENT')throw e;return fallback}}async function save(path,data){await writeFile(new URL(path,root),JSON.stringify(data,null,2)+'\n')}
const github=await read('dist/catalog.json',{repositories:[]}),snapshot=await read('dist/spaces.json',{repositories:[]}),config=await read('sources.config.json',{lists:[]}),cache=await read('.sources-cache.json',{});const repos=new Map(github.repositories.map(r=>[r.full.toLowerCase(),r])),spaces=new Map(snapshot.repositories.map(r=>[r.full.toLowerCase(),r]));const headers={Accept:'application/vnd.github+json','User-Agent':'RepoShelf-catalog'};if(process.env.GITHUB_TOKEN)headers.Authorization=`Bearer ${process.env.GITHUB_TOKEN}`;
async function json(url,githubRequest=false){const res=await fetch(url,{headers:githubRequest?headers:undefined,signal:AbortSignal.timeout(15000)});if(!res.ok)throw Object.assign(Error(`HTTP ${res.status} from ${new URL(url).hostname}`),{status:res.status});return res.json()}
let hfChecked=0,hfFound=0,listChecked=0,listFound=0;const stats={};
try{let paused=false;const checked=new Set();for(const prior of dueEntries([...spaces.values()],Date.now(),Number(process.env.SPACE_REVALIDATE_BATCH||100))){const result=await checkSpace(prior);spaces.set(prior.full.toLowerCase(),result.data?await verifySpaceSource(result.entry,result.data,{headers}):result.entry);checked.add(prior.spaceId);hfChecked++;if(result.stop){paused=true;break}}
if(!paused){const next=cache.spacesNext;const safeNext=typeof next==='string'&&next.startsWith('https://huggingface.co/api/spaces?')?next:null;const listing=await fetch(safeNext||'https://huggingface.co/api/spaces?sort=likes&direction=-1&limit=100&full=true',{signal:AbortSignal.timeout(15000)});if(!listing.ok)throw Error(`Spaces listing HTTP ${listing.status}`);const response=await listing.json();if(!Array.isArray(response))throw Error('Unexpected Spaces listing');const candidates=response.slice(cache.spacesOffset||0);let consumed=0;for(const item of candidates.slice(0,Number(process.env.SPACE_IMPORT_BATCH||60))){consumed++;if(!P.validId(item.id)||item.private||checked.has(item.id))continue;const key=`hf:${item.id}`.toLowerCase(),prior=spaces.get(key);if(prior?.nextCheckAt&&Date.parse(prior.nextCheckAt)>Date.now())continue;if(prior?.lastCheckedAt&&Date.now()-Date.parse(prior.lastCheckedAt)<86400000&&!prior.checkError)continue;const result=await checkSpace(prior||{full:`hf:${item.id}`,spaceId:item.id,name:item.id.split('/')[1],source:'huggingface'});hfChecked++;if(result.data){const entry=result.entry;if(entry.demo){spaces.set(key,await verifySpaceSource(entry,result.data,{headers}));hfFound++}}else if(prior)spaces.set(key,result.entry);if(result.stop){consumed--;break}}cache.spacesOffset=(cache.spacesOffset||0)+consumed;if(cache.spacesOffset>=response.length){cache.spacesOffset=0;const link=listing.headers.get('link')||'';cache.spacesNext=link.match(/<([^>]+)>;\s*rel="next"/)?.[1]||null}}
}catch(e){console.warn(`Spaces import postponed: ${e.message}`);stats.spacesError=e.message}
let limit=Number(process.env.CURATED_IMPORT_BATCH||60),stop=false;
for(const list of config.lists){if(stop||limit<=0)break;try{const metadata=await json(`https://api.github.com/repos/${list.repository}`,true);const markdown=await readGithubReadme({full:list.repository,branch:metadata.default_branch});const candidates=listCandidates(markdown,list.repository);const hash=createHash('sha256').update(markdown).digest('hex');const saved=cache[list.repository]||{};let cursor=(saved.cursor||0)%Math.max(1,candidates.length);const perList=Math.min(limit,Math.ceil(Number(process.env.CURATED_IMPORT_BATCH||60)/config.lists.length));for(let i=0;i<Math.min(perList,candidates.length);i++){const id=candidates[cursor%candidates.length];try{const entry=await importListCandidate(id,{kind:'curated-list',name:list.name,url:`https://github.com/${list.repository}`},repos.get(id.toLowerCase()),{headers});if(entry){repos.set(entry.full.toLowerCase(),entry);listFound++}}catch(e){console.warn(`List candidate postponed ${id}: ${e.message}`);if([403,429,401].includes(e.status)){stop=true;break}if(e.status!==404)break}cursor=(cursor+1)%candidates.length;listChecked++;limit--}cache[list.repository]={hash,cursor,total:candidates.length}}catch(e){console.warn(`List import postponed ${list.name}: ${e.message}`);if([403,429,401].includes(e.status))stop=true}}
await save('dist/spaces.json',{schema:1,updatedAt:new Date().toISOString(),import:{checked:hfChecked,refreshed:hfFound,...stats},repositories:[...spaces.values()]});await save('dist/catalog.json',{...github,updatedAt:new Date().toISOString(),repositories:[...repos.values()]});await save('.sources-cache.json',cache);console.log(`Sources: ${spaces.size} Spaces saved, ${hfChecked} checked, ${hfFound} refreshed; ${listChecked} curated candidates checked, ${listFound} demos found/refreshed.`);
