import {intakeSpaces,spaceCandidate} from './space-intake.mjs';
import {recordStageMetrics} from './sync-metrics.mjs';
import {savedListingControls} from '../lib/listing-policy.mjs';
import {readFile,writeFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';import {dueEntries} from './catalog-health.mjs';import {checkSpace,verifySpaceSource,listCandidates,importListCandidate,readGithubReadme} from './source-imports.mjs';const require=createRequire(import.meta.url);const P=require('../dist/providers.js');
const root=new URL('../',import.meta.url);async function read(path,fallback){try{return JSON.parse(await readFile(new URL(path,root),'utf8'))}catch(e){if(e.code!=='ENOENT')throw e;return fallback}}async function save(path,data){await writeFile(new URL(path,root),JSON.stringify(data,null,2)+'\n')}
const github=await read('dist/catalog.json',{repositories:[]}),snapshot=await read('dist/spaces.json',{repositories:[]}),config=await read('sources.config.json',{lists:[]}),cache=await read('.sources-cache.json',{});const repos=new Map(github.repositories.map(r=>[r.full.toLowerCase(),r])),spaces=new Map(snapshot.repositories.map(r=>[r.full.toLowerCase(),r]));const headers={Accept:'application/vnd.github+json','User-Agent':'RepoShelf-catalog'};if(process.env.GITHUB_TOKEN)headers.Authorization=`Bearer ${process.env.GITHUB_TOKEN}`;
async function json(url,githubRequest=false){const res=await fetch(url,{headers:githubRequest?headers:undefined,signal:AbortSignal.timeout(15000)});if(!res.ok)throw Object.assign(Error(`HTTP ${res.status} from ${new URL(url).hostname}`),{status:res.status});return res.json()}
const excluded=new Set((await savedListingControls()).filter(c=>c.visibility==='excluded').map(c=>c.project_id.toLowerCase()));
let hfChecked=0,hfFound=0,listChecked=0,listFound=0,listAdded=0;const stats={};
try{let paused=false;const checked=new Set();for(const prior of dueEntries([...spaces.values()],Date.now(),Number(process.env.SPACE_REVALIDATE_BATCH||100))){const result=await checkSpace(prior);spaces.set(prior.full.toLowerCase(),result.data?await verifySpaceSource(result.entry,result.data,{headers}):result.entry);checked.add(prior.spaceId);hfChecked++;if(result.stop){paused=true;break}}
if(!paused&&Number(process.env.SPACE_IMPORT_BATCH||60)>0){stats.spaceIntake=await intakeSpaces({cache,budget:Number(process.env.SPACE_IMPORT_BATCH||350),minLikes:Number(process.env.SPACE_MIN_LIKES||2),visit:async item=>{if(excluded.has(('hf:'+item.id).toLowerCase())||checked.has(item.id))return {skipped:true};const key=('hf:'+item.id).toLowerCase(),prior=spaces.get(key);if(prior?.nextCheckAt&&Date.parse(prior.nextCheckAt)>Date.now()||prior?.lastCheckedAt&&Date.now()-Date.parse(prior.lastCheckedAt)<86400000&&!prior.checkError)return {skipped:true};const result=await checkSpace(prior||{full:'hf:'+item.id,spaceId:item.id,name:item.id.split('/')[1],source:'huggingface'});hfChecked++;if(result.data&&spaceCandidate(result.data,{minLikes:Number(process.env.SPACE_MIN_LIKES||2)})&&result.entry.demo){spaces.set(key,await verifySpaceSource(result.entry,result.data,{headers}));hfFound++;return {checked:true,found:true,added:!prior,stop:result.stop}}if(prior)spaces.set(key,result.entry);return {checked:true,error:Boolean(result.entry.checkError),stop:result.stop};}})}
}catch(e){console.warn(`Spaces import postponed: ${e.message}`);stats.spacesError=e.message}
let limit=Number(process.env.CURATED_IMPORT_BATCH||60),stop=false;
const lists=config.lists||[],listOffset=(cache.curatedListCursor||0)%Math.max(1,lists.length),rotated=[...lists.slice(listOffset),...lists.slice(0,listOffset)];
cache.curatedListCursor=(listOffset+1)%Math.max(1,lists.length);
for(const list of rotated){if(stop||limit<=0)break;try{const metadata=await json(`https://api.github.com/repos/${list.repository}`,true);const markdown=await readGithubReadme({full:list.repository,branch:metadata.default_branch});const candidates=listCandidates(markdown,list.repository);const hash=createHash('sha256').update(markdown).digest('hex');const saved=cache[list.repository]||{};let cursor=(saved.cursor||0)%Math.max(1,candidates.length);const perList=Math.min(limit,Math.max(1,Math.floor(Number(process.env.CURATED_IMPORT_BATCH||60)/lists.length)));for(let i=0;i<Math.min(perList,candidates.length);i++){const id=candidates[cursor%candidates.length];try{const entry=await importListCandidate(id,{kind:'curated-list',name:list.name,url:`https://github.com/${list.repository}`},repos.get(id.toLowerCase()),{headers});if(entry){if(!repos.has(entry.full.toLowerCase()))listAdded++;repos.set(entry.full.toLowerCase(),entry);listFound++}}catch(e){console.warn(`List candidate postponed ${id}: ${e.message}`);if([403,429,401].includes(e.status)){stop=true;break}if(e.status!==404)break}cursor=(cursor+1)%candidates.length;listChecked++;limit--}cache[list.repository]={hash,cursor,total:candidates.length}}catch(e){console.warn(`List import postponed ${list.name}: ${e.message}`);if([403,429,401].includes(e.status))stop=true}}
await save('dist/spaces.json',{schema:1,updatedAt:new Date().toISOString(),import:{checked:hfChecked,refreshed:hfFound,...stats},repositories:[...spaces.values()]});await save('dist/catalog.json',{...github,updatedAt:new Date().toISOString(),repositories:[...repos.values()]});await save('.sources-cache.json',cache);console.log(`Sources: ${spaces.size} Spaces saved, ${hfChecked} checked, ${hfFound} refreshed; ${listChecked} curated candidates checked, ${listFound} demos found/refreshed.`);

await recordStageMetrics('sources',{sourceYield:{spaces:stats.spaceIntake||{inspected:0,added:0,found:0},curated:{inspected:listChecked,found:listFound,added:listAdded}},spacesChecked:hfChecked,spacesFound:hfFound,temporaryFailures:(stats.spaceIntake?.errors||0)+Number(Boolean(stats.spacesError))});
