import {searchRotation,searchCooldown} from './discovery-search.mjs';
import {recordStageMetrics} from './sync-metrics.mjs';
import {savedListingControls} from '../lib/listing-policy.mjs';
import {saveReadmeSnapshot} from './agent-snapshots.mjs';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {checkRepository,dueEntries,repositoryCheckPlan} from './catalog-health.mjs';
import {withOverview} from './readme-overviews.mjs';
import {withProjectInsights} from './project-insights.mjs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);const D=require('../dist/discovery.js');const S=require('../dist/storefront.js');
const output=new URL('../dist/catalog.json',import.meta.url),cacheFile=new URL('../.catalog-cache.json',import.meta.url),searchFile=new URL('../data/discovery-search.json',import.meta.url);
let searchState={};try{searchState=JSON.parse(await readFile(searchFile,'utf8'))}catch(e){if(e.code!=='ENOENT')throw e}
let old={repositories:[]},cache={};try{old=JSON.parse(await readFile(output,'utf8'))}catch{}try{cache=JSON.parse(await readFile(cacheFile,'utf8'))}catch{}
const excluded=new Set((await savedListingControls()).filter(c=>c.visibility==='excluded').map(c=>c.project_id.toLowerCase()));
const indexed=new Map((old.repositories||[]).filter(r=>D.demoUrl(r.demo)&&!excluded.has(r.full.toLowerCase())).map(r=>[r.full.toLowerCase(),r]));
const token=process.env.GITHUB_TOKEN;const headers={Accept:'application/vnd.github+json','User-Agent':'RepoShelf-catalog'};if(token)headers.Authorization=`Bearer ${token}`;
const maxCandidates=Number(process.env.CATALOG_BATCH_SIZE||1500),maxPages=Number(process.env.CATALOG_PAGES||10);let checked=0,found=0,failed=0,cacheHits=0,searchQueries=0,repositoryPaused=false;const started=Date.now();
const rotation=searchRotation(searchState,Date.now(),Math.min(10,maxPages)),maxQueries=Number(process.env.CATALOG_SEARCH_QUERIES||40),spacing=Math.max(4500,Number(process.env.CATALOG_SEARCH_SPACING_MS||4500));
const discoverySort=Math.floor(Date.now()/(2*3600000))%2?'updated':'stars';let searchPaused=null;
const queryYield=[];let searchTime=0;const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function request(url,opts={}){const res=await fetch(url,{...opts,signal:AbortSignal.timeout(12000)});if(!res.ok){const error=new Error(`HTTP ${res.status} for ${new URL(url).hostname}`);error.status=res.status;error.rateRemaining=res.headers.get('x-ratelimit-remaining');error.rateReset=res.headers.get('x-ratelimit-reset');error.retryAfter=res.headers.get('retry-after');throw error}return res}
async function readme(repo){for(const path of ['README.md','readme.md','README.MD','README.rst']){try{return {markdown:await (await request(`https://raw.githubusercontent.com/${repo.full}/${encodeURIComponent(repo.branch)}/${path}`)).text(),sourceUrl:`https://github.com/${repo.full}/blob/${encodeURIComponent(repo.branch)}/${path}`}}catch(e){if(e.status!==404)throw e}}return {markdown:'',sourceUrl:`https://github.com/${repo.full}`} }
async function pool(items,fn){let i=0;await Promise.all(Array.from({length:6},async()=>{while(i<items.length){const item=items[i++];await fn(item)}}))}
const seen=new Set();
const healthStats={checked:0,unavailable:0,temporaryFailures:0};let repositoryPlan=null,repositoryDue=0,repositoryStopReason=null;
async function revalidate(){const entries=[...indexed.values()];let remaining=null;
try{const response=await fetch('https://api.github.com/rate_limit',{headers,signal:AbortSignal.timeout(10000)});if(response.ok){const data=await response.json();const value=data.resources?.core?.remaining;if(Number.isFinite(value))remaining=value}}catch{}
repositoryPlan=repositoryCheckPlan(entries,{remaining,authenticated:Boolean(token),batch:process.env.CATALOG_REVALIDATE_BATCH||'auto'});
const dueAll=dueEntries(entries,Date.now(),entries.length);repositoryDue=dueAll.length;const due=dueAll.slice(0,repositoryPlan.limit),deadline=Date.now()+360000;
if(dueAll.length&&!due.length){repositoryStopReason='api_budget';console.warn('Revalidation deferred to preserve GitHub API headroom.');return true}

// Sequential checks allow us to stop promptly if GitHub rejects authentication or throttles us.
for(const prior of due){if(Date.now()>=deadline){repositoryStopReason='time_budget';break}const result=await checkRepository(prior,{headers});healthStats.checked++;if(result.notModified)healthStats.notModified=(healthStats.notModified||0)+1;if(result.entry.availability==='unavailable')healthStats.unavailable++;if(result.entry.checkError)healthStats.temporaryFailures++;
let entry=result.entry;if(result.data&&entry.availability==='available')entry={...entry,...D.mapRepo(result.data),demo:prior.demo,lastDemoCheckedAt:prior.lastDemoCheckedAt};if((result.data||result.notModified)&&entry.availability==='available')entry=S.recordMetrics(entry);indexed.set(prior.full.toLowerCase(),entry);
if(entry.full.toLowerCase()!==prior.full.toLowerCase()){indexed.delete(prior.full.toLowerCase());indexed.set(entry.full.toLowerCase(),entry)}
if(result.stop){repositoryStopReason=result.entry.checkError?.kind||'temporary';console.warn('Revalidation paused; saved records preserved for retry.');return true}}
console.log(`Revalidation: ${healthStats.checked} checked, ${healthStats.unavailable} unavailable, ${healthStats.temporaryFailures} temporary failures.`);return false}

try{const paused=await revalidate();repositoryPaused=paused;
if(Date.parse(rotation.state.nextAllowedAt)>Date.now())searchPaused={...rotation.state.cooldown,nextAllowedAt:rotation.state.nextAllowedAt};
while(!paused&&!searchPaused&&searchQueries<maxQueries&&checked<maxCandidates){const task=rotation.next();if(!task)break;await sleep(Math.max(0,spacing-(Date.now()-searchTime)));searchTime=Date.now();let data;try{searchQueries++;data=await (await request(`https://api.github.com/search/repositories?q=${encodeURIComponent(task.q)}&sort=${task.sort}&order=desc&per_page=100&page=${task.page}`,{headers})).json()}catch(e){failed++;searchPaused={status:e.status||null,rateRemaining:e.rateRemaining??null,rateReset:e.rateReset??null};console.warn(`Search paused: ${e.message}; remaining=${e.rateRemaining??'unknown'}, reset=${e.rateReset??'unknown'}. Saved entries retained.`);if([401,403,429].includes(e.status)){const cooldown=searchCooldown(e);rotation.retry(task);rotation.state.nextAllowedAt=cooldown.nextAllowedAt;rotation.state.cooldown=cooldown;searchPaused={...searchPaused,...cooldown};break}searchPaused=null;continue}
rotation.state.nextAllowedAt=null;rotation.state.cooldown=null;rotation.complete(task,data);
const fresh=(data.items||[]).filter(r=>!seen.has(r.full_name.toLowerCase())&&!excluded.has(r.full_name.toLowerCase()));fresh.forEach(r=>seen.add(r.full_name.toLowerCase()));const queryStats={query:task.q,page:task.page,inspected:0,found:0,added:0,cacheHits:0,errors:0};queryYield.push(queryStats);const remaining=maxCandidates-checked;await pool(fresh.slice(0,remaining),async d=>{const r=D.mapRepo(d),key=r.full.toLowerCase(),prior=indexed.get(key)||{},at=new Date().toISOString();let entry=S.recordMetrics({...prior,...r,demo:prior.demo,availability:'available',lastCheckedAt:at,lastAttemptAt:at,lastAvailableAt:at});entry.technologies=S.technologies(entry);delete entry.unavailableSince;delete entry.unavailableReason;delete entry.checkError;delete entry.nextCheckAt;const hit=cache[key];if(hit&&hit.parserVersion===2&&(!hit.demo||D.demoUrl(hit.demo))&&hit.updated===r.updated&&Date.now()-hit.checked<7*86400000){cacheHits++;queryStats.cacheHits++;if(hit.demo){if(prior.availability!=='available'||prior.checkError||!prior.lastCheckedAt||Date.now()-Date.parse(prior.lastCheckedAt)>=48*3600000||prior.updated!==r.updated)indexed.set(key,{...entry,demo:hit.demo,lastDemoCheckedAt:new Date(hit.checked).toISOString()});}else indexed.delete(key);return}checked++;queryStats.inspected++;try{const {markdown,sourceUrl}=await readme(r);r.demo=D.extractDemo(markdown,r.homepage);if(r.demo)entry={...withProjectInsights(withOverview(entry,markdown,sourceUrl),markdown,sourceUrl),overviewRepoUpdated:r.updated,readmeSnapshot:await saveReadmeSnapshot(r,markdown,sourceUrl)};cache[key]={parserVersion:2,updated:r.updated,checked:Date.now(),demo:r.demo};if(r.demo){indexed.set(key,{...entry,demo:r.demo,lastDemoCheckedAt:at});found++;queryStats.found++;if(!prior.full)queryStats.added++}else indexed.delete(key)}catch(e){failed++;queryStats.errors++;if(indexed.has(key))indexed.set(key,entry);console.warn(`Skipped ${r.full}: ${e.message}`)}});
rotation.observe(task,queryStats);
}
}finally{const repositories=[...indexed.values()].sort((a,b)=>(b.stars||0)-(a.stars||0));await writeFile(output,JSON.stringify({...old,schema:2,updatedAt:new Date().toISOString(),revalidation:healthStats,discovery:{checked,found,temporaryFailures:failed,sort:discoverySort,searchPaused},repositories},null,2)+'\n');await writeFile(cacheFile,JSON.stringify(cache));await mkdir(new URL('../data/',import.meta.url),{recursive:true});await writeFile(searchFile,JSON.stringify(rotation.finish(),null,2)+'\n');await recordStageMetrics('catalog',{repositoryChecks:healthStats.checked,repositoryNotModified:healthStats.notModified||0,repositoryPaused,repositoryPlan,repositoryDue,repositorySelected:Math.min(repositoryDue,repositoryPlan?.limit||0),repositoryRemainingDue:dueEntries(repositories,Date.now(),repositories.length).length,repositoryStopReason,repositoryObserved48h:repositories.filter(r=>r.availability!=='unavailable'&&r.lastCheckedAt&&Date.now()-Date.parse(r.lastCheckedAt)<=2*86400000).length,repositoryObserved24h:repositories.filter(r=>r.availability!=='unavailable'&&r.lastCheckedAt&&Date.now()-Date.parse(r.lastCheckedAt)<=86400000).length,candidateLimit:maxCandidates,candidatesChecked:checked,demosFound:found,cacheHits,queryYield,sourceYield:{github:{inspected:checked,found,added:queryYield.reduce((n,r)=>n+r.added,0),errors:failed}},searchQueries,searchQueryLimit:maxQueries,searchSpacingMs:spacing,searchCursor:rotation.state.cursor,searchPaused,temporaryFailures:failed+healthStats.temporaryFailures,durationMs:Date.now()-started});console.log(`Catalog: ${repositories.length} saved records (${repositories.filter(D.isAvailable).length} available); ${checked} checked, ${found} found/refreshed, ${failed} temporary failures.`);}
if(!indexed.size&&failed)process.exitCode=1;
