import {withProjectInsights} from './project-insights.mjs';
import {withOverview,readOverviewReadme} from './readme-overviews.mjs';
import {createRequire} from 'node:module';const require=createRequire(import.meta.url);const P=require('../dist/providers.js');const D=require('../dist/discovery.js');const S=require('../dist/storefront.js');
export function listCandidates(markdown,list){return [...new Set([...String(markdown).matchAll(/https:\/\/github\.com\/([A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+)(?=[\s)#?\]"<>]|$)/g)].map(m=>m[1].replace(/\.git$/,'')).filter(id=>P.validId(id)&&id.toLowerCase()!==list.toLowerCase()&&!/\/awesome(?:-|$)/i.test(id)))]}
export function explicitGithub(markdown,card={}){const candidates=[card.source_repo,card.source_repository,card.github_repo];for(const line of String(markdown).split('\n'))if(/\[(?:source(?: code)?|code|github(?: repository)?|repository)\]\(https:\/\/github\.com\//i.test(line)){const m=line.match(/\[(?:source(?: code)?|code|github(?: repository)?|repository)\]\(https:\/\/github\.com\/([\w.-]+\/[\w.-]+)\/?\)/i);if(m)candidates.push(`https://github.com/${m[1]}`)}for(const candidate of candidates){const m=String(candidate||'').match(/^https:\/\/github\.com\/([\w.-]+\/[\w.-]+)\/?$/);if(m&&P.validId(m[1]))return m[1]}return null}
export async function checkSpace(prior,{fetcher=fetch,now=Date.now()}={}){const at=new Date(now).toISOString();try{const res=await fetcher(`https://huggingface.co/api/spaces/${prior.spaceId}`,{signal:AbortSignal.timeout(15000)});if([404,410].includes(res.status))return {entry:{...prior,availability:'unavailable',unavailableReason:'not_found',unavailableSince:prior.unavailableSince||at,lastCheckedAt:at,lastAttemptAt:at,checkError:undefined,nextCheckAt:undefined},stop:false};if(!res.ok)throw Object.assign(Error('Space unavailable'),{status:res.status});const data=await res.json();return {entry:P.normalizeSpace(data,prior,now),data,stop:false}}catch(e){return {entry:{...prior,lastAttemptAt:at,checkError:{kind:[429,403].includes(e.status)?'rate_limit':'temporary',at},nextCheckAt:new Date(now+6*3600000).toISOString()},stop:[429,403].includes(e.status)}}}
export async function readGithubReadme(repo,options={}){return (await readOverviewReadme(repo,options)).markdown}
export async function importListCandidate(full,provenance,prior,{fetcher=fetch,headers={},now=Date.now()}={}){const response=await fetcher(`https://api.github.com/repos/${full}`,{headers,signal:AbortSignal.timeout(12000)});if(!response.ok)throw Object.assign(Error(`Repository HTTP ${response.status}`),{status:response.status});const data=await response.json();if(data.private||data.visibility&&data.visibility!=='public'||!P.validId(data.full_name))return null;const repo=D.mapRepo(data),{markdown,sourceUrl}=await readOverviewReadme(repo,{fetcher}),demo=D.extractDemo(markdown,repo.homepage);if(!demo&&!prior)return null;const at=new Date(now).toISOString();const entry=S.recordMetrics({...prior,...repo,demo,availability:'available',lastCheckedAt:at,lastAttemptAt:at,lastAvailableAt:at,lastDemoCheckedAt:at,discoveredVia:[...(prior?.discoveredVia||[]).filter(p=>p.url!==provenance.url),provenance]});delete entry.checkError;delete entry.nextCheckAt;delete entry.unavailableSince;delete entry.unavailableReason;entry.technologies=S.technologies(entry);return {...withProjectInsights(withOverview(entry,markdown,sourceUrl,now),markdown,sourceUrl,now),overviewRepoUpdated:repo.updated}}

export async function verifySpaceSource(entry,data,{fetcher=fetch,headers={},now=Date.now()}={}){try{const response=await fetcher(`https://huggingface.co/spaces/${entry.spaceId}/raw/main/README.md`,{signal:AbortSignal.timeout(12000)});if(!response.ok&&response.status!==404)return entry;const markdown=response.ok?await response.text():'';entry={...withProjectInsights(withOverview(entry,markdown,`https://huggingface.co/spaces/${entry.spaceId}/blob/main/README.md`,now),markdown,`https://huggingface.co/spaces/${entry.spaceId}/blob/main/README.md`,now),overviewRepoUpdated:entry.updated};const full=explicitGithub(markdown,data.cardData||data.carddata||{});if(!full){const copy={...entry};delete copy.githubFull;return copy}const repo=await fetcher(`https://api.github.com/repos/${full}`,{headers,signal:AbortSignal.timeout(12000)});if([404,410].includes(repo.status)){const copy={...entry};delete copy.githubFull;return copy}if(!repo.ok)return entry;const metadata=await repo.json();const copy={...entry,githubCheckedAt:new Date(now).toISOString()};if(metadata.private===false&&(!metadata.visibility||metadata.visibility==='public')&&P.validId(metadata.full_name))copy.githubFull=metadata.full_name;else delete copy.githubFull;return copy}catch{return entry}}
