import {readFile,writeFile,mkdir} from 'node:fs/promises';import {createRequire} from 'node:module';import {createHash} from 'node:crypto';
const require=createRequire(import.meta.url),P=require('../dist/providers.js'),Q=require('../dist/quality.js');
export const stageNames={sources:'Spaces and curated lists',community:'Community discoveries',catalog:'GitHub discovery and revalidation',enrich:'Releases and technologies',overviews:'README overviews',context:'Supporting documents',ai:'Optional AI overviews',browser:'Screenshot browser installation',verify:'Storefront verification',health:'Demo health',previews:'Preview screenshots',growth:'Growth history',validate:'Application checks',dependencies:'Dependencies',checkpoint_publish:'Discovery publication',publish:'Final publication'};
const read=async(path,fallback)=>{try{return JSON.parse(await readFile(path,'utf8'))}catch(e){if(e.code==='ENOENT')return fallback;throw e}};
async function entries(root){const [gh,hf]=await Promise.all(['catalog.json','spaces.json'].map(n=>read(new URL('dist/'+n,root),{repositories:[]})));return P.mergeCatalog(gh.repositories||[],hf.repositories||[])}
const fingerprints=repos=>Object.fromEntries(repos.map(r=>[r.full.toLowerCase(),createHash('sha256').update(JSON.stringify(r)).digest('hex')]));
export async function snapshot(root){return fingerprints(await entries(root))}
export function demoCount(repos){return repos.filter(r=>r.availability!=='unavailable'&&Q.hasLiveDemo(r)).length}
export function measure(before,after){const a=Object.keys(after),b=Object.keys(before);return {before:b.length,after:a.length,added:a.filter(id=>!(id in before)).length,updated:a.filter(id=>id in before&&before[id]!==after[id]).length,removed:b.filter(id=>!(id in after)).length}}
export function summarizeStages(steps,logs={}){return Object.entries(stageNames).filter(([id])=>steps[id]).map(([id,name])=>{const log=logs[id]||'',totals=log.split('\n').filter(line=>!/^\s*(?:Demo|Preview) progress:/.test(line)).join('\n'),progress=[...log.matchAll(/(?:Demo|Preview) progress: (\d+)\/\d+ checked/g)].at(-1),counts=[...log.matchAll(/(\d+) (?:temporary failures|postponed|failed)(?:\.|\s|$)/g)].map(m=>Number(m[1]));return {id,name,status:steps[id].outcome,temporaryFailures:counts.reduce((a,b)=>a+b,0),checked:[...totals.matchAll(/(\d+) checked/g)].reduce((n,m)=>n+Number(m[1]),0)||Number(progress?.[1]||0),unavailableResponses:[...totals.matchAll(/(\d+) unavailable(?: responses)?/g)].reduce((n,m)=>n+Number(m[1]),0),inconclusiveChecks:[...totals.matchAll(/(\d+) inconclusive/g)].reduce((n,m)=>n+Number(m[1]),0),warnings:(log.match(/(?:import|overview|candidate|enrichment|Preview) postponed(?:[^\n]*?:)/gi)||[]).length+(log.match(/(?:hackernews|bluesky): retry/g)||[]).length}})}
export async function run(mode,root=new URL('../',import.meta.url),env=process.env){const baseline=new URL('.sync-before.json',root);if(mode==='start'){await writeFile(baseline,JSON.stringify({startedAt:new Date().toISOString(),records:await snapshot(root)}));return}if(mode!=='finish')throw Error('Use start or finish');const before=await read(baseline,null);if(!before)throw Error('Missing sync baseline');const steps=JSON.parse(env.SYNC_STEP_RESULTS||'{}'),logs={};for(const id of Object.keys(stageNames)){try{logs[id]=await readFile(new URL('.sync-logs/'+id+'.log',root),'utf8')}catch(e){if(e.code!=='ENOENT')throw e}}
const stages=summarizeStages(steps,logs),runId=env.GITHUB_RUN_ID;if(!/^\d+$/.test(runId||''))throw Error('Missing GitHub run ID');const after=await entries(root),stats={...measure(before.records,fingerprints(after)),withDemo:demoCount(after)};const row={schema:3,phase:env.SYNC_REPORT_PHASE||'complete',publication:steps.checkpoint_publish?.outcome==='success'?'discovery_saved':'pending',id:runId,attempt:Number(env.GITHUB_RUN_ATTEMPT||1),startedAt:before.startedAt,recordedAt:new Date().toISOString(),trigger:env.GITHUB_EVENT_NAME||'unknown',status:stages.some(s=>s.status==='failure')?'failure':stages.some(s=>s.status==='cancelled')?'cancelled':'success',counts:stats,temporaryFailures:stages.reduce((n,s)=>n+s.temporaryFailures,0),stages};const directory=new URL('data/sync-runs/',root);await mkdir(directory,{recursive:true});await writeFile(new URL(runId+'.json',directory),JSON.stringify(row,null,2)+'\n');console.log(`Sync history: ${stats.added} added, ${stats.updated} updated; ${row.temporaryFailures} reported temporary failures.`)}
if(process.argv[1]&&new URL('file://'+process.argv[1]).href===import.meta.url)await run(process.argv[2]);
