-- Ribbon edit conflicts now raise PT409 (HTTP 409) instead of 40001. A conflict here is deterministic: the same call can never
-- succeed until the caller reloads. 40001 is Postgres's "serialization failure, retry" code, and on 2026-10-09 a stale save and an
-- unsatisfiable reorder were retried at about 100 calls a second for two and a half hours, saturating the database CPU.
-- The functions are otherwise unchanged. Grants are preserved by create or replace. Safe to run twice.
begin;
create or replace function public.reposhelf_save_ribbon(row_id uuid,expected_revision integer,row_title text,row_description text,row_category text,row_mode text,row_enabled boolean,row_items jsonb,row_shuffle text default 'off') returns public.editorial_ribbons language plpgsql security definer set search_path='' as $$declare saved public.editorial_ribbons;begin
if not public.reposhelf_is_admin() then raise insufficient_privilege;end if;
perform pg_advisory_xact_lock(71883001);
if row_shuffle is null or row_shuffle not in ('off','load','daily') then raise check_violation;end if;
if jsonb_typeof(row_items)<>'array' or exists(select 1 from jsonb_array_elements_text(row_items) p where p!~'^(hf:)?[a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+$' or length(p)>220) or (select count(*)<>count(distinct p) from jsonb_array_elements_text(row_items) p) then raise check_violation;end if;
if row_id is null then insert into public.editorial_ribbons(title,description,category,mode,enabled,items,shuffle,position) values(row_title,row_description,row_category,row_mode,row_enabled,row_items,row_shuffle,(select coalesce(max(position),0)+1 from public.editorial_ribbons)) returning * into saved;
else update public.editorial_ribbons set title=row_title,description=row_description,category=row_category,mode=row_mode,enabled=row_enabled,items=row_items,shuffle=row_shuffle,revision=revision+1,updated_at=now() where id=row_id and revision=expected_revision returning * into saved;if not found then raise exception using errcode='PT409',message='Ribbon changed';end if;end if;
if row_enabled and saved.builtin_key is null then update public.editorial_settings set custom_rows=true where id=true;end if;return saved;end$$;
create or replace function public.reposhelf_delete_ribbon(row_id uuid,expected_revision integer) returns void language plpgsql security definer set search_path='' as $$begin if not public.reposhelf_is_admin() then raise insufficient_privilege;end if;perform pg_advisory_xact_lock(71883001);delete from public.editorial_ribbons where id=row_id and revision=expected_revision;if not found then raise exception using errcode='PT409',message='Ribbon changed';end if;end$$;
create or replace function public.reposhelf_reorder_ribbons(ordered_ids uuid[]) returns void language plpgsql security definer set search_path='' as $$begin if not public.reposhelf_is_admin() then raise insufficient_privilege;end if;perform pg_advisory_xact_lock(71883001);if cardinality(ordered_ids)<>(select count(*) from public.editorial_ribbons) or cardinality(ordered_ids)<>(select count(distinct x) from unnest(ordered_ids) x) or exists(select 1 from unnest(ordered_ids) x where not exists(select 1 from public.editorial_ribbons where id=x)) then raise exception using errcode='PT409',message='Ribbon order changed';end if;update public.editorial_ribbons r set position=ids.pos,revision=revision+1,updated_at=now() from unnest(ordered_ids) with ordinality ids(id,pos) where r.id=ids.id;end$$;
commit;
