import {createMcpHandler} from '@modelcontextprotocol/server';import {toNodeHandler} from '@modelcontextprotocol/node';import {timingSafeEqual,createHash} from 'node:crypto';import {createRepoShelfMcp,MCP_TOOLS,MCP_PROMPTS} from '../lib/mcp-server.mjs';import {createGate} from '../lib/mcp-gate.mjs';import {createAccounts} from '../lib/accounts.mjs';import {createMcpKeys,KEY_PATTERN} from '../lib/mcp-keys.mjs';import {authorize,send} from '../lib/http-auth.mjs';
// The connector is a members-only feature. Signed-in members create personal keys on the Connect page and paste one into
// their assistant as an Authorization: Bearer header. REPOSHELF_API_KEY (the operator key) keeps working for the operator.
const LIMIT=120,WINDOW=60000,hits=new Map(),misses=new Map();
export function rateLimited(req,{now=Date.now(),limit=LIMIT,window=WINDOW,key,store=hits,record=true}={}){const id=key||String(req.headers['x-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0].trim()||'unknown',recent=(store.get(id)||[]).filter(t=>now-t<window);if(recent.length>=limit){store.set(id,recent);return true}if(record)recent.push(now);store.set(id,recent);if(store.size>5000)for(const [k,times] of store)if(!times.some(t=>now-t<window))store.delete(k);return false}
const usageName=body=>{const call=Array.isArray(body)?body[0]:body;if(call?.method==='tools/call'&&MCP_TOOLS.includes(call.params?.name))return call.params.name;if(call?.method==='prompts/get'&&MCP_PROMPTS.includes(call.params?.name))return 'prompt_'+call.params.name;return null};
const digest=s=>createHash('sha256').update(s).digest();
const unauthorized=(res,message)=>send(res,401,{error:{code:'unauthorized',message}},{'WWW-Authenticate':'Bearer realm="RepoShelf"'});
export function createMcpEndpoint({service,auth={},keys,gate}={}){const accounts=createAccounts(),members=keys||createMcpKeys(accounts),limiter=gate||createGate({accounts,fallback:(req,identity)=>rateLimited(req,{key:identity?'member:'+identity:undefined})});const handler=toNodeHandler(createMcpHandler(()=>createRepoShelfMcp(service),{responseMode:'json'}));return async(req,res)=>{
 // origin policy only; identity is decided below
 if(!authorize(req,res,{...auth,open:true}))return;
 res.setHeader('Cache-Control','private, no-store');
 const operatorKey=auth.key??process.env.REPOSHELF_API_KEY,header=String(req.headers.authorization||''),candidate=header.startsWith('Bearer ')?header.slice(7).trim():'';
 let identity=null;
 if(candidate&&candidate.length<=4096){
  if(operatorKey&&operatorKey.length>=32&&timingSafeEqual(digest(candidate),digest(operatorKey)))identity='operator';
  else if(KEY_PATTERN.test(candidate)){
   if(rateLimited(req,{limit:30,store:misses,record:false})){res.setHeader('Retry-After','60');send(res,429,{error:{code:'rate_limited',message:'Too many failed attempts. Please wait a minute and try again.'}});return}
   try{identity=await members.verify(candidate)}catch{send(res,503,{error:{code:'temporarily_unavailable',message:'Connector keys are temporarily unavailable. Please try again shortly.'}});return}
   if(!identity)rateLimited(req,{limit:30,store:misses})}}
 if(!identity){unauthorized(res,candidate?'This connector key is not valid. It may have been revoked. Create a new one on the Connect page of RepoShelf.':'The RepoShelf connector is for signed-in members. Create a personal key on the Connect page of RepoShelf and send it as an Authorization: Bearer header.');return}
 const length=Number(req.headers['content-length']||0);if(length>65536){send(res,413,{error:{code:'request_too_large',message:'MCP requests must be at most 64 KiB.'}});return}let body=req.body;try{if(req.method==='POST'){if(body===undefined){const chunks=[];let bytes=0;for await(const chunk of req){bytes+=Buffer.byteLength(chunk);if(bytes>65536){send(res,413,{error:{code:'request_too_large',message:'MCP requests must be at most 64 KiB.'}});return}chunks.push(Buffer.from(chunk))}body=JSON.parse(Buffer.concat(chunks).toString())}else{if(Buffer.byteLength(typeof body==='string'?body:JSON.stringify(body))>65536){send(res,413,{error:{code:'request_too_large',message:'MCP requests must be at most 64 KiB.'}});return}if(typeof body==='string')body=JSON.parse(body)}}const verdict=await limiter.check(req,usageName(body),identity);if(!verdict.allowed){res.setHeader('Retry-After','60');send(res,429,{error:{code:'rate_limited',message:'Too many requests. Please wait a minute and try again.'}});return}await handler(req,res,body)}catch{if(!res.headersSent)send(res,400,{jsonrpc:'2.0',error:{code:-32700,message:'Invalid MCP request.'},id:null});else if(!res.writableEnded)res.end()}}}
export default createMcpEndpoint();
