import {createHash,timingSafeEqual} from 'node:crypto';
import {createAccounts,respond,accountFailure,readBody,only,fail} from '../lib/accounts.mjs';
import {requireLegal} from '../lib/legal.mjs';import {createCatalogService} from '../lib/catalog-service.mjs';
import {OFFER,paymentConfig,requireTest,verifyEvent,createPayments} from '../lib/promotion-payments.mjs';import {demoAvailable} from '../lib/promotion-health.mjs';
export const config={api:{bodyParser:false}};
const valid=s=>typeof s==='string'&&/^[a-zA-Z0-9_.-]+\/[a-zA-Z0-9_.-]+$/.test(s)&&s.length<=220,uuid=s=>typeof s==='string'&&/^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/i.test(s);
const safeEqual=(a,b)=>timingSafeEqual(createHash('sha256').update(a).digest(),createHash('sha256').update(b).digest());
export function createPromotionHandler({accounts=createAccounts(),catalog=createCatalogService(),settings=paymentConfig(),fetcher=fetch,payments=createPayments(settings,{fetcher}),demoCheck=demoAvailable}={}){
const write=(operation,payload)=>accounts.request('/rest/v1/rpc/reposhelf_promotion_write',{service:true,method:'POST',body:{operation,payload}});
async function rows(query,token){return accounts.request('/rest/v1/promotions?select=*&'+query,{...(token?{token}:{service:true})})}
async function github(id,person){if(!valid(id))fail(400,'invalid_repository','Choose a GitHub repository.');const headers={Accept:'application/vnd.github+json','User-Agent':'RepoShelf-promotions'};if(person?.githubToken)headers.Authorization='Bearer '+person.githubToken;let r;try{let target=new URL('https://api.github.com/repos/'+id);for(let hop=0;hop<3;hop++){r=await fetcher(target.href,{headers,signal:AbortSignal.timeout(4000),redirect:'manual'});if(![301,302,307,308].includes(r.status))break;const next=new URL(r.headers.get('location'),target);if(next.origin!=='https://api.github.com'||next.username||next.password||!/^\/(?:repos\/[a-zA-Z0-9_.-]+\/[a-zA-Z0-9_.-]+|repositories\/\d+)$/.test(next.pathname))throw Error('Invalid redirect');target=next}}catch{fail(503,'ownership_unavailable','GitHub ownership could not be checked. Try again later.')}if([404,410].includes(r.status))return null;if(!r.ok)fail(503,'ownership_unavailable','GitHub ownership could not be checked. Try again later.');return r.json()}
async function eligible(id,person){const repo=await github(id,person);if(!repo||repo.private||repo.owner?.type!=='User'||String(repo.owner.id)!==person.githubId)fail(403,'not_repository_owner','Only the verified personal GitHub owner can promote this repository.');if(repo.archived||repo.disabled)fail(400,'repository_ineligible','Archived or disabled repositories cannot be promoted.');const found=await catalog.project({id:repo.full_name});const p=found.project;if(p.repositoryAvailability?.status==='unavailable'||!p.demo?.url||p.demoHealth?.status==='unavailable')fail(400,'demo_required','Promotion needs an available catalogue listing with a live demo.');return {repo,project:p,snapshot:{full:repo.full_name,name:p.name,description:p.description,category:p.category,language:p.language,demo:p.demo.url,color:'#25392f',ink:'#d1e5c5'}}}
async function one(id,person,{admin=false}={}){if(!uuid(id))fail(400,'invalid_promotion','Choose a valid promotion.');const result=await rows('id=eq.'+id+'&limit=1',person.token);const p=result[0];if(!p||!admin&&p.user_id!==person.id)fail(404,'promotion_not_found','Promotion not found.');return p}
async function health(p){try{const repo=await github(p.repo_name);if(!repo||repo.private)return {health:'unavailable',reason:'Repository unavailable'};if(String(repo.id)!==p.repo_id||String(repo.owner?.id)!==p.owner_id||repo.owner?.type!=='User')return {health:'unavailable',reason:'Repository ownership changed'};if(repo.archived||repo.disabled)return {health:'unavailable',reason:'Repository archived or disabled'};let project;try{project=(await catalog.project({id:p.repo_name})).project}catch(e){if(e.status===404)return {health:'unavailable',reason:'Listing unavailable in catalogue'};throw e}if(!project.demo?.url||project.repositoryAvailability?.status==='unavailable'||project.demoHealth?.status==='unavailable')return {health:'unavailable',reason:'Repository or demo unavailable'};if(project.demo.url!==p.snapshot.demo)return {health:'unavailable',reason:'Demo link changed; request an administrator refund before submitting again'};const demo=await Promise.race([demoCheck(project.demo.url),new Promise(resolve=>{const timer=setTimeout(()=>resolve('temporary'),6000);timer.unref?.()})]);return {health:demo,reason:demo==='unavailable'?'Demo returned not found':demo==='temporary'?'Availability check will be retried':null}}catch{return {health:'temporary',reason:'Availability check will be retried'}}}
async function settle(p,session){if(session.livemode!==false||session.mode!=='payment'||session.metadata?.promotion_id!==p.id||session.metadata?.attempt!==p.checkout_attempt||session.client_reference_id!==p.id||session.amount_total!==OFFER.amount||session.currency!==OFFER.currency)fail(400,'payment_mismatch','Payment does not match this test promotion.');if(session.payment_status==='paid'){if(typeof session.payment_intent!=='string'||!session.payment_intent.startsWith('pi_'))fail(400,'payment_mismatch','Invalid payment reference.');p=await write('paid',{id:p.id,session:session.id,attempt:session.metadata.attempt,payment:session.payment_intent,amount:session.amount_total,currency:session.currency});return write('health',{id:p.id,...await health(p)})}if(session.status==='expired')return write('checkout_expired',{id:p.id,session:session.id});return p}
async function checkout(p){requireTest(settings);const s=p.checkout_session?await payments.session(p.checkout_session):await payments.create(p,accounts.config.origin);if(!p.checkout_session)p=await write('session',{id:p.id,attempt:p.checkout_attempt,session:s.id});await settle(p,s);return s}
async function sync(){requireTest(settings);const list=await rows('status=in.(active,paused,checkout,paid_waiting)&order=paid_at.asc.nullslast,created_at.asc&limit=20');const results=await Promise.allSettled(list.map(async p=>{if(p.status==='checkout')await checkout(p);else await write('health',{id:p.id,...await health(p)})}));return {checked:results.filter(r=>r.status==='fulfilled').length,failed:results.filter(r=>r.status==='rejected').length,total:list.length}}
return async(req,res)=>{try{const u=new URL(req.url,accounts.config.origin),action=u.searchParams.get('action')||'mine';only(req,['GET','POST']);
if(action==='webhook'){only(req,['POST']);requireTest(settings);const buffers=[];let size=0;for await(const chunk of req){size+=Buffer.byteLength(chunk);if(size>131072)fail(413,'body_too_large','Payment event is too large.');buffers.push(Buffer.from(chunk))}const event=verifyEvent(Buffer.concat(buffers),req.headers['stripe-signature'],settings.webhook);if(event.livemode!==false)fail(400,'live_payments_disabled','Real payments are disabled.');if(['checkout.session.completed','checkout.session.async_payment_succeeded','checkout.session.expired'].includes(event.type)){const s=event.data?.object;if(!uuid(s?.metadata?.promotion_id))fail(400,'invalid_event','Missing promotion reference.');const result=await rows('id=eq.'+s.metadata.promotion_id+'&limit=1');if(!result.length)fail(404,'promotion_not_found','Promotion not found.');await settle(result[0],s)}if(event.type==='charge.refunded'){const charge=event.data?.object;if(charge?.refunded===true&&charge.amount_refunded===OFFER.amount&&charge.amount===OFFER.amount&&charge.currency===OFFER.currency&&typeof charge.payment_intent==='string'&&/^pi_[a-zA-Z0-9]+$/.test(charge.payment_intent)){const list=await rows('payment_intent=eq.'+charge.payment_intent+'&limit=1');if(list.length)await write('payment_refunded',{id:list[0].id,payment:charge.payment_intent});else if(charge.metadata?.promotion_id)fail(503,'payment_not_recorded','Payment completion must be recorded before the refund. Retry later.')}}return respond(res,200,{received:true})}
if(action==='sync'){only(req,['POST']);const auth=req.headers.authorization||'';if(settings.syncKey.length<32||!safeEqual(auth,'Bearer '+settings.syncKey))fail(401,'sync_key_required','Invalid promotion sync key.');return respond(res,200,await sync())}
if(action==='feed'){only(req,['GET']);if(!accounts.ready||!accounts.config.serviceKey)return respond(res,200,{items:[],mode:'test'});let list;try{list=await rows('status=eq.active&order=paid_at.asc&limit=5')}catch(e){if(e.code==='database_unavailable'||e.code==='migration_required')return respond(res,200,{items:[],mode:'test'});throw e}const viewer=await accounts.user(req,res,{optional:true});if(!viewer||!await accounts.isAdmin(viewer))return respond(res,200,{items:[],mode:'test'});const items=[];for(const p of list){const remaining=Number(p.remaining_seconds)-(p.active_since?(Date.now()-Date.parse(p.active_since))/1000:0);if(remaining<=0)continue;try{const r=(await catalog.project({id:p.repo_name})).project;if(r.repositoryAvailability?.status==='unavailable'||!r.demo?.url||r.demoHealth?.status==='unavailable'||r.demo.url!==p.snapshot.demo)continue;items.push({...p.snapshot,id:p.id,sponsored:true})}catch{}}// Test purchases are never represented as real sponsorship on the public store.
return respond(res,200,{items,mode:'test'})}
if(req.method==='POST')accounts.origin(req);const manage=action==='manage'||['review','refund','admin-sync'].includes(action),person=manage?await accounts.admin(req,res):await accounts.user(req,res);if(req.method==='POST')await requireLegal(accounts,person);
if(action==='eligibility'){only(req,['GET']);try{await eligible(u.searchParams.get('repo'),person);return respond(res,200,{eligible:true})}catch(e){if(e.status===403||e.status===400||e.status===404)return respond(res,200,{eligible:false,reason:e.message});throw e}}
if(action==='mine'||action==='manage'){only(req,['GET']);const cursor=u.searchParams.get('cursor');if(cursor&&!uuid(cursor))fail(400,'invalid_cursor','Invalid page.');const list=await rows((manage?'':'user_id=eq.'+person.id+'&')+'order=id.asc&limit=50'+(cursor?'&id=gt.'+cursor:''),person.token);return respond(res,200,{items:list,nextCursor:list.length===50?list.at(-1).id:null,offer:OFFER,checkoutReady:/^sk_test_/.test(settings.key)&&/^whsec_/.test(settings.webhook),admin:await accounts.isAdmin(person)})}
const b=await readBody(req);only(req,['POST']);
if(action==='request'){const {repo,snapshot}=await eligible(b?.repo,person);const p=await write('request',{user_id:person.id,repo_name:repo.full_name,repo_id:String(repo.id),owner_id:person.githubId,snapshot});return respond(res,200,{promotion:p})}
if(action==='review'){const p=await one(b?.id,person,{admin:true});if(!['approved','rejected'].includes(b.decision)||typeof b.note!=='string'||b.note.length>500||b.decision==='rejected'&&!b.note.trim())fail(400,'invalid_review','Choose a decision and explain any rejection.');if(b.decision==='approved'){const h=await health(p);if(h.health!=='available')fail(409,'listing_not_ready','The repository and demo must pass availability checks before approval.')}return respond(res,200,{promotion:await write('review',{id:p.id,reviewer:person.id,decision:b.decision,note:b.note.trim()})})}
if(action==='checkout'){requireTest(settings);let p=await one(b?.id,person);const {repo,project}=await eligible(p.repo_name,person);if(String(repo.owner.id)!==p.owner_id||project.demo.url!==p.snapshot.demo)fail(409,'approval_changed','Ownership or the demo changed since approval. Ask the administrator to reject this unpaid request, then submit it again.');if(String(repo.id)!==p.repo_id)fail(409,'repository_changed','Repository changed. Submit a new request.');p=await write('reserve',{id:p.id,user_id:person.id});const session=await checkout(p);if(session.status==='expired')return respond(res,200,{refresh:true});if(session.payment_status==='paid')return respond(res,200,{refresh:true});if(!session.url||new URL(session.url).origin!=='https://checkout.stripe.com')fail(503,'invalid_checkout','Checkout is temporarily unavailable.');return respond(res,200,{url:session.url})}
if(action==='refresh'){const p=await one(b?.id,person);if(p.status==='checkout')await checkout(p);else if(['active','paused','paid_waiting'].includes(p.status))await write('health',{id:p.id,...await health(p)});return respond(res,200,{updated:true})}
if(action==='refund'){requireTest(settings);const p=await one(b?.id,person,{admin:true});if(!p.payment_intent)fail(400,'no_payment','This promotion has no payment.');const result=await payments.refund(p);if(result.status!=='succeeded')fail(503,'refund_pending','Refund is pending. Check Stripe before trying again.');return respond(res,200,{promotion:await write('refund',{id:p.id,reviewer:person.id})})}
if(action==='admin-sync')return respond(res,200,await sync());fail(404,'not_found','Unknown promotion action.');
}catch(e){accountFailure(res,e)}}
}
export default createPromotionHandler();
