import {fetchSyncProgress} from '../lib/sync-progress.mjs';
import {catalogueSchedule,createWorkflowControl} from '../lib/workflow-control.mjs';
import publicationHandler from '../lib/publication-handler.mjs';
import maintenanceHandler from '../lib/maintenance-handler.mjs';
import {publicationSummary} from '../lib/publication-policy.mjs';
import {createCheckpointStore} from '../lib/checkpoint-store.mjs';
import {diagnoseSync,syncFreshness,syncHealth,deploymentStatus} from '../lib/sync-diagnostics.mjs';
import {readFile,readdir} from 'node:fs/promises';import {createAccounts,respond,accountFailure,only,fail} from '../lib/accounts.mjs';
export async function savedSyncRuns(){let names;try{names=await readdir(new URL('../data/sync-runs/',import.meta.url))}catch(e){if(e.code==='ENOENT')return [];throw e}return Promise.all(names.filter(n=>/^\d+\.json$/.test(n)).map(async n=>JSON.parse(await readFile(new URL('../data/sync-runs/'+n,import.meta.url),'utf8'))))}
const OTHER_WORKFLOWS=['recovery.yml','publication.yml','submissions.yml','launch-acceleration.yml'],CATALOGUE_WORKFLOWS=['Refresh demo catalog','Recover incomplete catalogue listings'];
export function createSyncLogHandler({accounts=createAccounts(),saved=savedSyncRuns,fetcher=fetch,checkpoint=createCheckpointStore({fetcher}),control=createWorkflowControl({fetcher}),progress=()=>fetchSyncProgress({fetcher}),serverToken=process.env.REPOSHELF_ACTIONS_TOKEN||process.env.REPOSHELF_SUBMISSION_WORKFLOW_TOKEN}={}){return async(req,res)=>{try{only(req,['GET']);const person=await accounts.admin(req,res),token=person.githubToken||serverToken||null,url=new URL(req.url,accounts.config.origin),page=Number(url.searchParams.get('page')||1);if(!Number.isSafeInteger(page)||page<1||page>10000)fail(400,'invalid_page','Choose a valid log page.');let history=await saved();let live=null,notice=null;try{const githubHeaders={Accept:'application/vnd.github+json','User-Agent':'RepoShelf'};const historyURL='https://api.github.com/repos/sparx1981/RepoShelf/actions/workflows/catalog.yml/runs?per_page=20&page='+page;const deadline=Date.now()+5000;let response=await fetcher(historyURL,{headers:{...githubHeaders,...token?{Authorization:'Bearer '+token}:{}},redirect:'error',signal:AbortSignal.timeout(5000)});if(token&&[401,403].includes(response.status)&&Date.now()<deadline){response=await fetcher(historyURL,{headers:githubHeaders,redirect:'error',signal:AbortSignal.timeout(Math.max(1,deadline-Date.now()))})}if(!response.ok)throw Error('GitHub run history is temporarily unavailable. Saved sync reports are still shown.');live=await response.json();try{const extras=await Promise.allSettled(OTHER_WORKFLOWS.map(async file=>{const extra=await fetcher('https://api.github.com/repos/sparx1981/RepoShelf/actions/workflows/'+file+'/runs?per_page=20&page='+page,{headers:{...githubHeaders,...token?{Authorization:'Bearer '+token}:{}},redirect:'error',signal:AbortSignal.timeout(3000)});return extra.ok?extra.json():null})),merged=new Map((live.workflow_runs||[]).map(r=>[String(r.id),r]));let total=live.total_count;for(const result of extras){const data=result.status==='fulfilled'?result.value:null;if(!data)continue;total+=data.total_count||0;for(const r of data.workflow_runs||[])merged.set(String(r.id),r)}live={total_count:total,workflow_runs:[...merged.values()].sort((a,b)=>Date.parse(b.created_at)-Date.parse(a.created_at))}}catch{}}catch{notice='GitHub run history is temporarily unavailable. Saved sync reports are still shown.'}
const latestReports=await checkpoint.reports(live?.workflow_runs?live.workflow_runs.map(r=>String(r.id)):null);const combined=new Map(history.map(r=>[String(r.id),r]));for(const report of latestReports){const prior=combined.get(String(report.id));if(!prior||report.attempt>prior.attempt||report.attempt===prior.attempt&&(!prior.recordedAt||Date.parse(report.recordedAt)>=Date.parse(prior.recordedAt)))combined.set(String(report.id),report)}history=[...combined.values()];
const jobDetails=new Map();if(live?.workflow_runs){const deadline=Date.now()+5000;const pending=live.workflow_runs.filter(r=>r.conclusion!=='success');let cursor=0;await Promise.all(Array.from({length:Math.min(4,pending.length)},async()=>{while(cursor<pending.length&&Date.now()<deadline){const run=pending[cursor++];try{const response=await fetcher('https://api.github.com/repos/sparx1981/RepoShelf/actions/runs/'+run.id+'/attempts/'+run.run_attempt+'/jobs?per_page=100',{headers:{Accept:'application/vnd.github+json','User-Agent':'RepoShelf',...token?{Authorization:'Bearer '+token}:{}},redirect:'error',signal:AbortSignal.timeout(Math.min(2500,Math.max(1,deadline-Date.now())))});if(response.ok){const data=await response.json();if(Array.isArray(data.jobs))jobDetails.set(String(run.id),data.jobs)}}catch{}}}))}
let deployment=null;if(page===1&&live?.workflow_runs?.length){try{const response=await fetcher('https://api.github.com/repos/sparx1981/RepoShelf/commits/main/status',{headers:{Accept:'application/vnd.github+json','User-Agent':'RepoShelf'},redirect:'error',signal:AbortSignal.timeout(3000)});deployment=deploymentStatus(response.ok?await response.json():null)}catch{deployment=deploymentStatus(null)}}
let publication={...publicationSummary(null),...catalogueSchedule(),controlConfigured:control.configured};try{const [state,cadence]=await Promise.all([checkpoint.json?.('data/publication.json'),checkpoint.json?.('data/launch-cadence.json')]);publication={...publicationSummary(state),...catalogueSchedule(Date.now(),cadence),controlConfigured:control.configured}}catch{}
let browserProgress=null;if(page===1&&live?.workflow_runs?.some(r=>r.status!=='completed'))try{browserProgress=await progress()}catch{}
const byId=new Map(history.map(r=>[String(r.id),r]));const runs=live?.workflow_runs?live.workflow_runs.map(r=>{const candidate=byId.get(String(r.id)),report=candidate?.attempt===r.run_attempt?candidate:null;return {diagnostics:diagnoseSync(r,jobDetails.get(String(r.id)),report,browserProgress?.runId===String(r.id)&&browserProgress.attempt===r.run_attempt?browserProgress:null),browserProgress:browserProgress?.runId===String(r.id)&&browserProgress.attempt===r.run_attempt?browserProgress:null,id:String(r.id),workflow:r.name||null,attempt:r.run_attempt,startedAt:r.run_started_at||r.created_at,finishedAt:r.status==='completed'?r.updated_at:null,status:r.conclusion||r.status,trigger:r.display_title==='Automatic catch-up sync'?'automatic recovery':r.event,url:'https://github.com/sparx1981/RepoShelf/actions/runs/'+r.id,...report?{phase:report.phase,work:report.work||null,counts:report.counts,temporaryFailures:report.temporaryFailures,stages:report.stages,recordedAt:report.recordedAt}: {counts:null,temporaryFailures:null,stages:[]}}}):history.sort((a,b)=>Date.parse(b.startedAt)-Date.parse(a.startedAt)).slice((page-1)*20,page*20).map(r=>({...r,finishedAt:r.finishedAt||(r.phase==='complete'&&Number.isFinite(Date.parse(r.recordedAt))?r.recordedAt:null),url:'https://github.com/sparx1981/RepoShelf/actions/runs/'+r.id}));const catalogueRuns=runs.filter(r=>!r.workflow||CATALOGUE_WORKFLOWS.includes(r.workflow));return respond(res,200,{runs,page,deployment,publication,health:page===1?syncHealth(catalogueRuns,{live:Boolean(live)}):null,freshness:page===1&&live?syncFreshness(catalogueRuns):null,hasMore:live?live.total_count>page*20:history.length>page*20,notice})}catch(e){accountFailure(res,e)}}}
export function createSyncRouter({sync=createSyncLogHandler(),publication=publicationHandler,maintenance=maintenanceHandler}={}){return (req,res)=>{const action=new URL(req.url,'https://reposhelf.invalid').searchParams.get('action');return action==='maintenance'?maintenance(req,res):['publish','publication-status'].includes(action)?publication(req,res):sync(req,res)}}
export default createSyncRouter();
